ALTER INDEX public.comment_likes_user_id_idx RENAME TO "_user_like_comment_B_index";
ALTER TABLE public.comment_likes RENAME CONSTRAINT comment_likes_user_id_fkey TO "_user_like_comment_B_fkey";
ALTER TABLE public.comment_likes RENAME CONSTRAINT comment_likes_comment_id_fkey TO "_user_like_comment_A_fkey";
ALTER TABLE public.comment_likes RENAME CONSTRAINT comment_likes_pkey TO "_user_like_comment_AB_pkey";
ALTER TABLE public.comment_likes RENAME COLUMN user_id TO "B";
ALTER TABLE public.comment_likes RENAME COLUMN comment_id TO "A";
ALTER TABLE public.comment_likes RENAME TO _user_like_comment;

ALTER TABLE public.user_field_permissions RENAME COLUMN allow_mask TO "allowMask";
ALTER TABLE public.role_field_permissions RENAME COLUMN allow_mask TO "allowMask";
ALTER INDEX public.field_permission_mappings_entity_bit_index_key RENAME TO "field_permission_mappings_entity_bitIndex_key";
ALTER TABLE public.field_permission_mappings RENAME COLUMN is_relation TO "isRelation";
ALTER TABLE public.field_permission_mappings RENAME COLUMN bit_index TO "bitIndex";

ALTER TYPE public.activity_type RENAME TO "ActivityType";
ALTER TYPE public.edit_action_type RENAME TO "EditActionType";
ALTER TYPE public.edit_relation_type RENAME TO "EditRelationType";
ALTER TYPE public.game_character_blood_type RENAME TO "GameCharacterBloodType";
ALTER TYPE public.game_character_gender RENAME TO "GameCharacterGender";
ALTER TYPE public.game_character_role RENAME TO "GameCharacterRole";
ALTER TYPE public.game_download_resource_report_reason RENAME TO "GameDownloadResourceReportReason";
ALTER TYPE public.game_download_resource_report_status RENAME TO "GameDownloadResourceReportStatus";
ALTER TYPE public.game_download_resource_simulator RENAME TO "GameDownloadResourceSimulator";
ALTER TYPE public.game_relation_type RENAME TO "GameRelationType";
ALTER TYPE public.game_upload_session_status RENAME TO "GameUploadSessionStatus";
ALTER TYPE public.hash_algorithm RENAME TO "HashAlgorithm";
ALTER TYPE public.malware_scan_case_status RENAME TO "MalwareScanCaseStatus";
ALTER TYPE public.malware_scan_decision_source RENAME TO "MalwareScanDecisionSource";
ALTER TYPE public.message_tone RENAME TO "MessageTone";
ALTER TYPE public.message_type RENAME TO "MessageType";
ALTER TYPE public.moderate_category_key RENAME TO "ModerateCategoryKey";
ALTER TYPE public.moderation_decision RENAME TO "ModerationDecision";
ALTER TYPE public.permission_entity RENAME TO "PermissionEntity";
ALTER TYPE public.report_malicious_level RENAME TO "ReportMaliciousLevel";
ALTER TYPE public.sponsor_order_status RENAME TO "SponsorOrderStatus";
ALTER TYPE public.user_lang RENAME TO "UserLang";
ALTER TYPE public.user_upload_quota_record_action RENAME TO "UserUploadQuotaRecordAction";
ALTER TYPE public.user_upload_quota_record_field RENAME TO "UserUploadQuotaRecordField";
ALTER TYPE public.user_upload_quota_record_status RENAME TO "UserUploadQuotaRecordStatus";
ALTER TYPE public.walkthrough_status RENAME TO "WalkthroughStatus";
