INSERT INTO field_permission_mappings (entity, field, bit_index, is_relation, updated) VALUES
  ('game', 'IDS', 0, false, CURRENT_TIMESTAMP),
  ('game', 'TITLES', 1, false, CURRENT_TIMESTAMP),
  ('game', 'INTROS', 2, false, CURRENT_TIMESTAMP),
  ('game', 'ALIASES', 3, false, CURRENT_TIMESTAMP),
  ('game', 'RELEASE', 4, false, CURRENT_TIMESTAMP),
  ('game', 'TYPE', 5, false, CURRENT_TIMESTAMP),
  ('game', 'PLATFORMS', 6, false, CURRENT_TIMESTAMP),
  ('game', 'EXTRA', 7, false, CURRENT_TIMESTAMP),
  ('game', 'TAGS', 8, false, CURRENT_TIMESTAMP),
  ('game', 'STAFFS', 9, false, CURRENT_TIMESTAMP),
  ('game', 'MANAGE_LINKS', 10, true, CURRENT_TIMESTAMP),
  ('game', 'MANAGE_COVERS', 11, true, CURRENT_TIMESTAMP),
  ('game', 'MANAGE_IMAGES', 12, true, CURRENT_TIMESTAMP),
  ('game', 'MANAGE_DEVELOPERS', 13, true, CURRENT_TIMESTAMP),
  ('game', 'MANAGE_CHARACTERS', 14, true, CURRENT_TIMESTAMP),
  ('game', 'STATUS', 15, false, CURRENT_TIMESTAMP),
  ('game', 'NSFW', 16, false, CURRENT_TIMESTAMP),
  ('game', 'VIEWS', 17, false, CURRENT_TIMESTAMP),
  ('game', 'MANAGE_RELATIONS', 18, true, CURRENT_TIMESTAMP),
  ('character', 'IDS', 0, false, CURRENT_TIMESTAMP),
  ('character', 'NAMES', 1, false, CURRENT_TIMESTAMP),
  ('character', 'INTROS', 2, false, CURRENT_TIMESTAMP),
  ('character', 'ALIASES', 3, false, CURRENT_TIMESTAMP),
  ('character', 'IMAGE', 4, false, CURRENT_TIMESTAMP),
  ('character', 'BODY_METRICS', 5, false, CURRENT_TIMESTAMP),
  ('character', 'AGE_BIRTHDAY', 6, false, CURRENT_TIMESTAMP),
  ('character', 'BLOOD_TYPE', 7, false, CURRENT_TIMESTAMP),
  ('character', 'GENDER', 8, false, CURRENT_TIMESTAMP),
  ('developer', 'IDS', 0, false, CURRENT_TIMESTAMP),
  ('developer', 'NAME', 1, false, CURRENT_TIMESTAMP),
  ('developer', 'ALIASES', 2, false, CURRENT_TIMESTAMP),
  ('developer', 'INTROS', 3, false, CURRENT_TIMESTAMP),
  ('developer', 'EXTRA', 4, false, CURRENT_TIMESTAMP),
  ('developer', 'LOGO', 5, false, CURRENT_TIMESTAMP),
  ('developer', 'WEBSITE', 6, false, CURRENT_TIMESTAMP)
ON CONFLICT (entity, field) DO UPDATE SET bit_index = EXCLUDED.bit_index, is_relation = EXCLUDED.is_relation, updated = CURRENT_TIMESTAMP;

INSERT INTO role_field_permissions (role, entity, allow_mask, updated) VALUES
  (1, 'game', 718, CURRENT_TIMESTAMP),
  (2, 'game', 270334, CURRENT_TIMESTAMP),
  (3, 'game', 524287, CURRENT_TIMESTAMP),
  (1, 'character', 494, CURRENT_TIMESTAMP),
  (2, 'character', 510, CURRENT_TIMESTAMP),
  (3, 'character', 511, CURRENT_TIMESTAMP),
  (1, 'developer', 94, CURRENT_TIMESTAMP),
  (2, 'developer', 126, CURRENT_TIMESTAMP),
  (3, 'developer', 127, CURRENT_TIMESTAMP)
ON CONFLICT (role, entity) DO UPDATE SET allow_mask = EXCLUDED.allow_mask, updated = CURRENT_TIMESTAMP;
