ALTER TYPE public."ActivityType" RENAME TO activity_type;
ALTER TYPE public."EditActionType" RENAME TO edit_action_type;
ALTER TYPE public."EditRelationType" RENAME TO edit_relation_type;
ALTER TYPE public."GameCharacterBloodType" RENAME TO game_character_blood_type;
ALTER TYPE public."GameCharacterGender" RENAME TO game_character_gender;
ALTER TYPE public."GameCharacterRole" RENAME TO game_character_role;
ALTER TYPE public."GameDownloadResourceReportReason" RENAME TO game_download_resource_report_reason;
ALTER TYPE public."GameDownloadResourceReportStatus" RENAME TO game_download_resource_report_status;
ALTER TYPE public."GameDownloadResourceSimulator" RENAME TO game_download_resource_simulator;
ALTER TYPE public."GameRelationType" RENAME TO game_relation_type;
ALTER TYPE public."GameUploadSessionStatus" RENAME TO game_upload_session_status;
ALTER TYPE public."HashAlgorithm" RENAME TO hash_algorithm;
ALTER TYPE public."MalwareScanCaseStatus" RENAME TO malware_scan_case_status;
ALTER TYPE public."MalwareScanDecisionSource" RENAME TO malware_scan_decision_source;
ALTER TYPE public."MessageTone" RENAME TO message_tone;
ALTER TYPE public."MessageType" RENAME TO message_type;
ALTER TYPE public."ModerateCategoryKey" RENAME TO moderate_category_key;
ALTER TYPE public."ModerationDecision" RENAME TO moderation_decision;
ALTER TYPE public."PermissionEntity" RENAME TO permission_entity;
ALTER TYPE public."ReportMaliciousLevel" RENAME TO report_malicious_level;
ALTER TYPE public."SponsorOrderStatus" RENAME TO sponsor_order_status;
ALTER TYPE public."UserLang" RENAME TO user_lang;
ALTER TYPE public."UserUploadQuotaRecordAction" RENAME TO user_upload_quota_record_action;
ALTER TYPE public."UserUploadQuotaRecordField" RENAME TO user_upload_quota_record_field;
ALTER TYPE public."UserUploadQuotaRecordStatus" RENAME TO user_upload_quota_record_status;
ALTER TYPE public."WalkthroughStatus" RENAME TO walkthrough_status;

ALTER TABLE public.field_permission_mappings RENAME COLUMN "bitIndex" TO bit_index;
ALTER TABLE public.field_permission_mappings RENAME COLUMN "isRelation" TO is_relation;
ALTER INDEX public."field_permission_mappings_entity_bitIndex_key" RENAME TO field_permission_mappings_entity_bit_index_key;
ALTER TABLE public.role_field_permissions RENAME COLUMN "allowMask" TO allow_mask;
ALTER TABLE public.user_field_permissions RENAME COLUMN "allowMask" TO allow_mask;

ALTER TABLE public._user_like_comment RENAME TO comment_likes;
ALTER TABLE public.comment_likes RENAME COLUMN "A" TO comment_id;
ALTER TABLE public.comment_likes RENAME COLUMN "B" TO user_id;
ALTER TABLE public.comment_likes RENAME CONSTRAINT "_user_like_comment_AB_pkey" TO comment_likes_pkey;
ALTER TABLE public.comment_likes RENAME CONSTRAINT "_user_like_comment_A_fkey" TO comment_likes_comment_id_fkey;
ALTER TABLE public.comment_likes RENAME CONSTRAINT "_user_like_comment_B_fkey" TO comment_likes_user_id_fkey;
ALTER INDEX public."_user_like_comment_B_index" RENAME TO comment_likes_user_id_idx;
