/* eslint-disable quotes */
export const game_characters = [
  {
    id: 1,
    b_id: '74284',
    v_id: 'c87837',
    image: 'character/1/image/352bd5b4-8209-4a5d-9434-fe2a95310329.webp',
    name_jp: '和泉妃愛',
    name_zh: '和泉妃爱',
    name_en: 'Izumi Hiyori',
    aliases: [
      '和泉 妃愛',
      'いずみ ひより',
      'Izumi Hiyori',
      'Hiyorin',
      'ひよりん',
      'Koizumi Hiyori',
      '小泉 妃愛',
    ],
    intro_jp:
      '智宏の妹にして子役上がりの覇権声優。\r\n一家の稼ぎ頭であり、家計を完全掌握している。\r\nその結果、ガチャを回すため平身低頭に徹する智宏と\r\nそれを甘やかす妃愛、という構図が完全に出来上がってしまった。\r\n実のところ、智宏のお世話をしないと調子が狂うのは妃愛の方だが、\r\nそれを知るのは智宏ただ一人。',
    intro_zh: '',
    intro_en:
      "Creative Skill: Voice Actress\nSpecial Skill: Rock Paper Scissors\nFavorite Food: Onii-chan's Chinese Fried Rice\nHobby: Housework\n\n[url=https://vndb.org/c87836]Tomohiro[/url]'s little sister, and a child star turned successful voice actress.\nAs the breadwinner of their family, she manages their household finances.\nIt ends up that in their household, she often spoils Tomohiro when he prostrates to her asking for money to roll gacha.\nIn reality, she's the one who would go crazy if she doesn't pamper Tomohiro, but he's the only one who knows that.\n\n\"So Onii is the student council president now?\nThis imouto always believed that you could succeed if you tried.\"\n\n[From the [url=https://madosoft.net/hamidashi/character]official website[/url]]\n\nShe voices characters in the gacha game Tomohiro plays, and is also a singer who [url=https://vndb.org/c87840]Shio[/url] is a fan of. Of course, her voice can also be found in the latest anime.",
    blood_type: null,
    height: null,
    weight: 40,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [9, 5],
    gender: '{f,f}',
  },
  {
    id: 2,
    b_id: '74285',
    v_id: 'c87838',
    image: 'character/2/image/ed45c908-271c-4929-bc7c-588f7c1be99e.webp',
    name_jp: '常磐華乃',
    name_zh: '常磐华乃',
    name_en: 'Tokiwa Kano',
    aliases: ['常磐 華乃', 'ときわ かの', 'Tokiwa Kano', 'かのちん', 'ののか'],
    intro_jp:
      '今年度の頭に智宏のクラスへとやって来た謎の転入生。\r\n転入２日目から不登校になり、その謎に一層深みが増した。\r\nその正体は、世間でも知られた人気イラストレーター。\r\n最近はソシャゲの仕事をしながらSNSに落書きをアップし\r\n自尊心を満たしている。\r\n過去に智宏と面識があるらしいが……？\r\n好物はたこ焼き。好き過ぎて自画像がたこ焼き化している。',
    intro_zh: '',
    intro_en:
      "Creative Skill: Illustrator\nSpecial Skill: Sewing\nFavorite Food: Takoyaki\nHobby: Sleeping\n\nThe mysterious transfer student who transferred into class at the beginning of the year, and went truant on her second day.\nShe's actually a world-famous illustrator.\nRecently she's been working on art for social games while posting sketches online to maintain her pride.\nIt seems she's made acquaintance with [url=https://vndb.org/c87836]Tomohiro[/url] in the past.\nShe loves takoyaki. She loves it so much she set it as her profile picture.\n\n\"You know, I wasn't even planning on eating until now.\nBut of course I'll want to eat takoyaki if you tempt me like that!\"\n\n[From the [url=https://madosoft.net/hamidashi/character]official website[/url]]\n\nAs an illustrator she's known as Nonoka, who Tomohiro is a huge fan of. \nIn the gacha game he plays, she illustrates a character who [url=https://vndb.org/c87837]Hiyori[/url] voices.\nShe also illustrated the VTuber [url=https://vndb.org/c101936]Yukige Shiki[/url] and they both admire each other's work.\nShe works on games, anime, manga, eroge, and the like.",
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [1, 31],
    gender: '{f,f}',
  },
  {
    id: 3,
    b_id: '74286',
    v_id: 'c87839',
    image: 'character/3/image/05a250a8-8dd9-4117-94fc-a7e2c366d7f2.webp',
    name_jp: '錦あすみ',
    name_zh: '锦明日海',
    name_en: 'Nishiki Asumi',
    aliases: ['にしき　あすみ', 'Nishiki Asumi', 'すみぴっぴ'],
    intro_jp: '',
    intro_zh:
      '智宏在便利店偶遇到的后辈。\r\n然而，在学校几乎无法遇到。\r\n外表和性格都是非常稀有的“好孩子”角色，\r\n正因如此，对她不上学的理由一无所知。\r\n正在以雪景四季的名字，开展Vtuber活动。\r\n不输给专业人士歌喉的口碑，\r\n使她的的频道订阅数飞速增长。\r\n深爱肉包，哪怕盛夏都不会使她的爱变质。',
    intro_en:
      "Creative Skill: Vtuber\nSpecial Skill: Massaging\nFavorite Food: Steamed Meat Buns\nHobby: Singing\n\n[url=https://vndb.org/c87836]Tomohiro[/url]'s junior, she met him at a convenience store.\nYou won't often find her at school.\nLike a rare character, her appearances and personality are great, yet it's a mystery as to why she's truant.\nUnbeknownst to anyone, she's the face behind the Vtuber [url=https://vndb.org/c101936]Yukigeshiki[/url].\nWith her singing skills that put pros to shame, her subscriber count is skyrocketing. \nHer love for steamed meat buns doesn't fade even in the sweltering summer months.\n\n\"I'm not good at dealing with guys,\nBut I don't sense any obscenity from you, senpai...\"\n\n[From the [url=https://madosoft.net/hamidashi/character]official website[/url]]",
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [12, 1],
    gender: '{f,f}',
  },
  {
    id: 4,
    b_id: '74287',
    v_id: 'c87840',
    image: 'character/4/image/6074c5b8-6f2b-4321-93eb-082ae72b8724.webp',
    name_jp: '鎌倉詩桜',
    name_zh: '镰仓诗樱',
    name_en: 'Kamakura Shio',
    aliases: [
      '鎌倉 詩桜',
      'かまくら しお',
      'Kamakura Shio',
      'Hoshi Shion',
      '星しをん',
      'Shiopoyo',
      'しおぽよ',
      'Miura Daikon-senpai',
      '三浦大根先輩',
      'Shogun',
      '将軍',
    ],
    intro_jp:
      '智宏が災難を被る羽目になった元凶であり、またの役職名を 前生徒会長 。\r\n会長職にあった当時は高いカリスマ性を誇り、他校にもファンがいたほど。\r\nただし、他の役員を全員クビにした経験を持つなど性根はねじれている。\r\n職業作家でもあり、自分の経験を描写に活かすタイプで、\r\n会長職もその一環だった。\r\n「名字から歴史ネタでいじられがち」な事を密かに気にしている。',
    intro_zh: '',
    intro_en:
      "Creative Skill: Novelist\nSpecial Skill: Ear Cleaning\nFavorite Food: Noodles, Local Specialties when Travelling\nHobby: Observing People, Fishing\n\nThe former student council president, she's the cause of [url=https://vndb.org/c87836]Tomohiro[/url]'s problems.\nWhen she was student council president, her charisma earned her fans even in other schools, let alone their own.\nBut she has a twisted personality, having fired all the other council members.\nIn her eyes, the student council presidency was just one of the life experiences that she draws upon to use in her works as a professional novelist.\nShe's annoyed that people make history jokes about her surname Kamakura, but she keeps that a secret.\n\n\"The pitch accent is wrong. It's not shi-o (→ ↑, salt), it's Shi-o (↑ ↑). \nAlthough it's true that my way of doing things makes some people salty...\"\n\n[From the [url=https://madosoft.net/hamidashi/character]official website[/url]]",
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [2, 18],
    gender: '{f,f}',
  },
  {
    id: 5,
    b_id: '74288',
    v_id: null,
    image: '',
    name_jp: '和泉智宏',
    name_zh: '和泉智宏',
    name_en: null,
    aliases: ['和泉 智宏', 'いずみ ともひろ', 'Izumi Tomohiro'],
    intro_jp: '',
    intro_zh:
      '本作男主人公，典型自闭症。\r\n在班中形如空气，不幸抓阄抽中了学生会长，一日之内连升三级。',
    intro_en: '',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{}',
  },
  {
    id: 6,
    b_id: '78074',
    v_id: 'c91566',
    image: 'character/6/image/674ebd7b-8e44-4a4e-86a9-2c73e32477a6.webp',
    name_jp: '竜閑天梨',
    name_zh: '龙闲天梨',
    name_en: 'Ryuukan Ameri',
    aliases: ['竜閑 天梨', 'りゅうかん あめり'],
    intro_jp:
      '智宏の同級生にして、クラスのカースト最上位。\r\n読モとしても活動中で、雑誌の表紙を飾るなど\r\nグングン人気を伸ばしている。\r\nただ、最近は仕事と友達付き合いの\r\nバランスに困っているようで……？',
    intro_zh: '',
    intro_en:
      "Creative Point: Fashion Model\nSpecial Skill: Makeup, Taking and Editing Pictures\nFavorite Food: Potato Salad\nHobby: Photo-based Social Media\n\nA popular model in fashion magazines. She's often featured on magazine covers, and recently was invited to a fashion show.\nShe was at the top of the school pecking order, but recently she's been too busy to meet with her friends.\nA savvy and experienced social media user, she doesn't seem to complement [url=https://vndb.org/c87836]Tomohiro[/url] at all. Yet for some reason, she's been hanging out with the student council lately.\n\n\"Uhmmm, I do like crowds, you know? Also, festival!\nIt's the very definition of 'enjoying your summer.'\"\n\n[From the [url=https://madosoft.net/hamidashi_totsu/character]official website[/url]]",
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [3, 17],
    gender: '{f,f}',
  },
  {
    id: 7,
    b_id: '78075',
    v_id: 'c91567',
    image: 'character/7/image/8995bbc3-39db-4a8b-ac8f-82a7b2ecdae2.webp',
    name_jp: '和泉里',
    name_zh: '和泉 里',
    name_en: 'Izumi Miri',
    aliases: ['和泉 里', 'いずみ みり', 'ミリ'],
    intro_jp:
      '智宏の従姉。クラスの担任であり、生徒会の顧問も兼任。\r\n学生時代は読モをやっていたというのも納得の美貌で、\r\n今日も男子学生の目を奪っている。\r\nまだまだ若いのか、言葉遣いはちょっと前のギャルそのもの。',
    intro_zh: '',
    intro_en:
      "[url=https://vndb.org/c87836]Tomohiro[/url]'s cousin, she serves as his homeroom teacher and the student council advisor.\nWith her beauty, it's no surprise she was a magazine fashion model in her student days. Even now, she attracts the attention of the male students.\nShe's still young, but her speech resembles that of a gal from the past.\n\n[From the [url=https://madosoft.net/hamidashi/sub_character]official website[/url]]",
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [4, 16],
    gender: '{f,f}',
  },
  {
    id: 8,
    b_id: '78076',
    v_id: 'c91568',
    image: 'character/8/image/a273d8a7-5b3b-4130-8b98-1d0ccf2d2e69.webp',
    name_jp: '新川広夢',
    name_zh: '新川广梦',
    name_en: 'Shinkawa Hiromu',
    aliases: ['新川 広夢', 'しんかわ ひろむ'],
    intro_jp:
      '智宏の席の後ろに座る男子。\r\nクラスでも珍しく智宏へ積極的に絡んでくる。\r\nその可愛らしい顔立ちは、中性的というよりもはや女の子。\r\n体格もさほど大きくなく、声色も適度に明るいため、\r\nドギマギさせられることもしばしば。',
    intro_zh: '',
    intro_en:
      "The boy who sits behind [url=https://vndb.org/c87836]Tomohiro[/url] in class.\nHe's strangely proactive about interacting with our protagonist.\nThat cute face is androgynous, and in fact some would say it's girly.\nYou might even find yourself flustered with that small build and somewhat bright voice.\n\n[Translated from the [url=https://madosoft.net/hamidashi/sub_character]official website[/url]]\n\n[spoiler]He's the face behind the popular VTuber Rema-chan (レマちゃん), who consistently gets over 100,000 views on her daily morning horoscopes. In addition, he's a famous crossplayer known as Mare-san (稀礼さん).[/spoiler]",
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [12, 22],
    gender: '{m,m}',
  },
  {
    id: 9,
    b_id: '78077',
    v_id: 'c91569',
    image: 'character/9/image/6da6c061-1579-40a6-888d-7b6751a4a6c4.webp',
    name_jp: '聖莉々子',
    name_zh: '圣莉莉子',
    name_en: 'Hijiri Ririko',
    aliases: ['聖 莉々子', 'ひじり りりこ'],
    intro_jp:
      '千玉随一のお嬢様校・百合ヶ峰学園の生徒会長。\r\n丁寧ながらやや上から目線な喋り方と、\r\nそのステータスの高さから、\r\n学生の間では同調圧力の鬼と化している。\r\n詩桜に対してライバル意識を持っているが、\r\n当の詩桜からはいい知り合いと思われている。',
    intro_zh: '',
    intro_en:
      "The student council president at Yurigamine Academy, the most prestigious girls' school in Chidama.\nOwing to that polite and slightly condescending tone in tandem with her high status, she's thought of as a demon of conformity as she always seeks the unanimous agreement of those present.\nIt seems she's thought of as a good acquaintance by [url=https://vndb.org/c87840]Shio[/url].\n\n[From the [url=https://madosoft.net/hamidashi/sub_character]official website[/url]]",
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [8, 15],
    gender: '{f,f}',
  },
  {
    id: 10,
    b_id: '170114',
    v_id: 'c148006',
    image: 'character/10/image/4f9b1a6a-d972-4110-a04a-44e3d2802aa9.webp',
    name_jp: '美倉礼良',
    name_zh: '美仓礼良',
    name_en: 'Mikura Rara',
    aliases: ['美倉礼良', 'みくら らら'],
    intro_jp:
      '聖家お抱えの家事代行で、自称「メイドさん」。\r\n莉々子の居住空間の清掃・片付けを担当しているものの、\r\nほとんどの業務を平日の日中に行うため、\r\n莉々子本人と接する機会はあまり無い。\r\n勤務態度は非常に真面目だが、\r\n勤務時間外は不真面目との目撃情報も。',
    intro_zh: '',
    intro_en:
      'She is a housekeeper for the Hijiri family and calls herself a "maid".\nAlthough she is in charge of cleaning and tidying up Ririko\'s living space,\nbut since she does most of her work during the weekdays, she doesn\'t have much contact with Ririko herself,\nshe does not have much opportunity to interact with Ririko herself.\nHer work attitude is very serious,\nHowever, there are some witnesses who say that she is not so serious outside of working hours.',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [11, 28],
    gender: '{f,f}',
  },
  {
    id: 11,
    b_id: '104139',
    v_id: 'c104918',
    image: 'character/11/image/71cf0f46-4bc0-43b5-b349-6c74a9d79d28.webp',
    name_jp: 'ルビイ',
    name_zh: null,
    name_en: 'Ruby',
    aliases: ['Ruby'],
    intro_jp:
      '敵組織《メデューサ》の女性幹部。\r\n主人公ソーマを「兄ぃ」と呼ぶ幼馴染でもある。\r\n組織きっての脅威として知られ、その犠牲となった\r\n命の数は計り知れない。フリギア軍の認定した\r\nコードネームは特級戦力《紅玉》。\r\n昔のよしみかソーマに対しては人懐っこく甘える\r\nものの、クラスメイトのことは酷く敵視している。',
    intro_zh: '',
    intro_en:
      '"Let\'s play together again like in the old days, Nii?"\n\n- Affiliation: Medusa.\n- Birthday: January 24.\n- Height: 157cm.\n- Three Size: B88(F)/W57/H89.\n- Likes: Waffles/Her brother, Souma.\n- Dislikes: ???\n- Will/Gem: "Red, Brilliant Crimson Fruit of Wrath" Red Berry Pigeon\'s Blood\nCrystallizes blood plasma and produces rubies. It can even turn all the blood flowing inside a target into a blade, making it unrivaled in its ability to kill in terms of lethality.\n\nShe is a female leader of the enemy organization, Medusa.\nShe is also a childhood friend of the main protagonist Souma, whom she calls "Ani".\nShe is known as one of the greatest threats in the organization, and the number of lives she has sacrificed is immeasurable.\nHer code name recognized by the Phrygian Military Army is "Kogyoku" which means "special strength".\nAlthough she is friendly and has sweet affection towards to Souma for old childhood times, she is very antagonistic to Souma\'s classmates.\n\n[Translated from [url=https://cabbage-soft.com/products/jewelry/character/]Official Website[/url]]',
    blood_type: null,
    height: 157,
    weight: null,
    bust: 88,
    waist: 57,
    hips: 89,
    cup: 'F',
    age: null,
    birthday: [1, 24],
    gender: '{f,f}',
  },
  {
    id: 12,
    b_id: '105042',
    v_id: 'c104902',
    image: 'character/12/image/bb90d3a7-cf75-4019-8b48-1ea4ee7c6fc6.webp',
    name_jp: 'アリアンナ',
    name_zh: null,
    name_en: 'Arianna Heartbell',
    aliases: ['Arianna Heartbell'],
    intro_jp:
      '「クラス・ペガサス」学級長となる女の子。\r\n足並みの揃わないクラスにおける唯一の良心で、\r\nまとまりのない連中を組織する苦労人。\r\n実は名門貴族のお嬢様なのだが、生来の優しさと\r\nフレンドリーさからいい意味で壁を感じさせない。\r\n伝説と謳われる『ダイヤモンド』の意志を持つ、\r\n世界でただ一人の人物。',
    intro_zh: '',
    intro_en:
      '"Let\'s go, everyone! Let\'s give it hit with all of our strenght!"\n\n- Affiliation: Pegasus Class.\n- Birthday: July 12.\n- Height: 162cm.\n- Three Size: B84(C)/W63/H87.\n- Likes: Fairy tale books.\n- Dislikes: Snakes.\n- Will/Gem: "Wings of Hope in the sky" Diamond Hope.\n"I want to fly in the sky" The power of hope. Grows shining and strong diamond wings of brilliant. It enables to fly and protects oneself and others by covering them.\n\nA girl who becomes the head of her class in Pegasus Class.\nShe is the sole conscience of the class and hard worker who organizes the disorganized group.\nShe is actually the daughter of a prestigious noble family, but her innate kindness and friendliness make her feel no barriers in a good way.\nShe is the only person in the world who possesses the legendary "Diamond" will.\n\n[Translated from [url=https://cabbage-soft.com/products/jewelry/character/]Official Website[/url]]',
    blood_type: null,
    height: 162,
    weight: null,
    bust: 84,
    waist: 63,
    hips: 87,
    cup: 'C',
    age: null,
    birthday: [7, 12],
    gender: '{f,f}',
  },
  {
    id: 13,
    b_id: '105043',
    v_id: 'c104905',
    image: 'character/13/image/3644010d-b7e1-4155-af14-5cf87bc65d43.webp',
    name_jp: 'ベルカ・トリアーデ',
    name_zh: null,
    name_en: 'Berka Triade',
    aliases: ['Berka Triade'],
    intro_jp:
      '怜悧かつスポーティなペガサス組のクラスメイト。\r\n剣の道を極めるべくアカデミアへ入学した。\r\n同性すらなびかせる美しい容姿とは裏腹に、\r\nとにかく「強い相手と闘って勝つ」以外のことに\r\n興味を示さない超マイペース女子。',
    intro_zh: '',
    intro_en:
      '"Hey. If you\'re going to fight, can I join you?"\n\n- Affiliation: Pegasus Class\n- Birthday: September 30\n- Height: 166 cm\n- Three Size: B85(C)/W62/H83\n- Likes: Strong enemies\n- Dislikes: Enemies of beauty\n- Will/Gem: "A Thousand Feathers, A Thousand Cuts" Alexandrite Sword\nA power that prides itself on "not losing to anyone when it comes to swordsmanship". All the abilities necessary for sword fights are sharpened, including awareness, sharpness, and judgment. At the end of the day, she is able to reach a state of being like a sixth sense.\n\nShe is a classmate of the Pegasus Class who has sharp sense and sporty.\nShe is enrolls to the Jewerly Academia to master the art of swordsmanship.\nDespite her beautiful appearance that even her own gender is attracted to, she is a very self-paced girl who shows no interest in anything other than "fighting strong opponents and winning".\n\n[Translated from [url=https://cabbage-soft.com/products/jewelry/character/]Official Website[/url]]',
    blood_type: null,
    height: 166,
    weight: null,
    bust: 85,
    waist: 62,
    hips: 83,
    cup: 'C',
    age: null,
    birthday: [9, 30],
    gender: '{f,f}',
  },
  {
    id: 14,
    b_id: '105044',
    v_id: 'c104910',
    image: 'character/14/image/a1de4481-58e1-479d-a2bb-73928f6c66a5.webp',
    name_jp: 'メア・アシュリーペッカー',
    name_zh: null,
    name_en: 'Mare Ashley-Pecker',
    aliases: ['Mare Ashley-Pecker'],
    intro_jp:
      'トップの成績でアカデミアへ入学した稀代の才媛。\r\n神学・修辞学・物理学・生物学などあらゆる学問に通じており、彼女の意志もまたその知性に裏打ちされたものだという。猫タイプの獣人種。\r\n幼く可愛げな容姿ながら、常に生意気で毒舌なポーカーフェイス。仲間や人情などには「興味がない」というスタンスを崩さない。',
    intro_zh: '',
    intro_en:
      '"I can record data from all of you even after you die. Just do whatever you want."\n\n- Affiliation: Pegasus Class\n- Birthday: March 4\n- Height: 144 cm\n- Three Size: B70(A)/W54/H60\n- Likes: Fried chicken\n- Dislikes: Humanity\n- Will/Gem: "Fearless is the Princess of Wisdom" Topaz Reason. [spoiler]After Chatoyancy: "Chains of Love, Courage and Wisdom" Santa Maria Aquamarine Endless Chain[/spoiler]\n\nThe power of wisdom that "fears nothing". Based on the theory that the unknown is the root of fear, she can instantly analyze the data of any object she shines her light on.\n\nShe is a cat-type beast and a rare talented girl who entered academia with top grades.\nShe is well versed in theology, rhetoric, physics, biology, and all other studies, and her will is also backed by her intellect.\nDespite her young and cute appearance, she always has a poker face with a cheeky and sharp-tongued.\nShe never breaks her stance that she is "not interested" in friends or humanity.\n\n[Translated from [url=https://cabbage-soft.com/products/jewelry/character/]Official Website[/url]]',
    blood_type: null,
    height: 144,
    weight: null,
    bust: 70,
    waist: 54,
    hips: 60,
    cup: 'A',
    age: null,
    birthday: [3, 4],
    gender: '{f,f}',
  },
  {
    id: 15,
    b_id: '106144',
    v_id: null,
    image: 'character/15/image/eb81fc2d-ea65-4660-ad98-f90d207ec4c1.webp',
    name_jp: 'ソーマ・ジェイス',
    name_zh: null,
    name_en: null,
    aliases: ['Soma Jace'],
    intro_jp:
      'アカデミアへ入学する主人公。その正体は組織\r\n《宵闇連盟》に属するスパイ・エージェント。\r\n学園に眠る『賢者の石』なるアイテムを探るべく送り込まれた。\r\n優秀な頭脳で入試2位の成績を収める──も、なぜか最上級「クラス・ダイヤ」ではなく新設の「クラス・ペガサス」に振り分けられてしまう。',
    intro_zh: '',
    intro_en: '',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{}',
  },
  {
    id: 16,
    b_id: '106145',
    v_id: 'c104911',
    image: 'character/16/image/3c580b27-6e5b-4170-aab2-f1ef1e91e4d6.webp',
    name_jp: 'ヴェオ',
    name_zh: null,
    name_en: 'Veo',
    aliases: ['Veo'],
    intro_jp:
      '狼タイプのセリオンにしてクラスの問題児。\r\nよく他クラスとのいざこざを引き起こす。\r\nアカデミアの校則は「決闘」を禁じているものの、\r\n本人はあくまで「ただの喧嘩」と言い張っている。\r\n獣人嫌いのマークスとは文字通り犬猿の仲。\r\n一触即発のムードになるのを、\r\nしばしばアリアンナになだめられている。',
    intro_zh: '',
    intro_en:
      '"I don\'t hate guys like you, I don\'t like them"\n\n- Affiliation: Pegasus Class.\n- Birthday: Mid-October.\n- Height: 175cm.\n- Likes: Dried meat.\n- Dislikes: Group activities.\n\nHe is a wolf-type Therion and the problem child of the class that often causes conflicts with other classes.\nAlthough the academia school rules forbid "dueling", he insists that he is "just a fight".\nHe literally has a dog-monkey relationship with Markus, who hates beastmen.\nArianna often calms him down when he gets into a volatile mood.\n\n[Translated from [url=https://cabbage-soft.com/products/jewelry/character/]Official Website[/url]]',
    blood_type: null,
    height: 175,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{m,m}',
  },
  {
    id: 17,
    b_id: '106146',
    v_id: 'c104912',
    image: 'character/17/image/01d2572d-4730-4adf-b42f-fa1802f0efdb.webp',
    name_jp: 'マークス・フォン・レオンシュタイン',
    name_zh: null,
    name_en: 'Markus von Leonstein',
    aliases: ['Markus von Leonstein'],
    intro_jp:
      'フリギア王族・レオンシュタイン家の第四王子。\r\nその誇り高き血統とプライドから最上級クラスを\r\n志願するも、ペガサス組へ配属されてしまった。\r\n王子として常に甘やかされてきたマークスだが、\r\nアカデミアに集う頑固者たちは誰も彼を忖度してく\r\nれないため、初の環境に翻弄されることになる。\r\n妹であるノアを溺愛している。',
    intro_zh: '',
    intro_en:
      '"Do you treat me, a prince, as if I were a beast?"\n\n- Affiliation: Pegasus Class.\n- Birthday: April 22.\n- Height: 177 cm.\n- Likes: Tea.\n- Dislikes: Beastmen (Therion).\n\nThe fourth prince of the Phrygian royal family, the Leonsteins family.\nDue to his proud in blood lineage and pride, he applied for the Diamond Class. But he was assigned to the Pegasus Class.\nAs a prince, Markus has always been pampered. However, the stubborn people who gather at the academy do not take him seriously and he finds himself at the mercy of his first environment.\nHe loves his sister, Noah, very much.\n\n[Translated from [url=https://cabbage-soft.com/products/jewelry/character/]Official Website[/url]]',
    blood_type: null,
    height: 177,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [4, 22],
    gender: '{m,m}',
  },
  {
    id: 18,
    b_id: '106147',
    v_id: 'c104913',
    image: 'character/18/image/468857d1-4590-40e2-a8d8-ef5ca5ed08c8.webp',
    name_jp: 'シャーロット先生',
    name_zh: null,
    name_en: 'Charlotte Jerome',
    aliases: ['Charlotte Jerome', 'シャーロット先生 (Charlotte-sensei)'],
    intro_jp:
      '服装も性格もラフなクラス・ペガサス担任教師。\r\nよく言えば放任主義だが、悪く言えばズボラで、\r\n真面目でよく働くアリアンナに連絡や雑務を任せっ\r\nきりにしがち。\r\n担当科目は宝石学。アカデミア特有とも言える\r\n教科で、鉱物学的な研究から意志の解明まで、\r\n幅広い分野に渡る学問となっている。',
    intro_zh: '',
    intro_en:
      '"For the best teacher like me to be in charge of this class, I suppose this is the best class, right?"\n\n- Affiliation: Academy Teacher/Pegasus Class Homeroom Teacher\n- Birthday: October 5\n- Height: 168cm\n- Three Size: B89(D)/W64/H92\n- Likes: Holidays\n- Dislikes: Homecoming\n[spoiler]- Will/Gem: "Lighting Flash Spiral Storm" Tourmaline Tornado[/spoiler]\n\nThe casual-like homeroom teacher of Pegasus Class in both personality and attire.\nKindly speaking, she is a laissez-faire type of person. Badly speaking, she is a sloppy person. She tends to leave any communication related and trivial tasks to the diligent, hardworking Arianna.\nHer subject in charge is Gemology. It is a unique subject to Academia, covering a wide field from mineralogical researches to Will elucidations.\n\n[Translated from [url=https://cabbage-soft.com/products/jewelry/character/]Official Website[/url]]',
    blood_type: null,
    height: 168,
    weight: null,
    bust: 89,
    waist: 64,
    hips: 92,
    cup: 'D',
    age: null,
    birthday: [10, 5],
    gender: '{f,f}',
  },
  {
    id: 19,
    b_id: '106148',
    v_id: 'c104915',
    image: 'character/19/image/50372da2-363f-4a98-9c76-10530dfa1b8e.webp',
    name_jp: 'キャロライナ・マクラクラン',
    name_zh: null,
    name_en: 'Carolina McLachlan',
    aliases: ['Carolina McLachlan', 'キャロちゃん', 'キャロちゃん (Caro-chan)'],
    intro_jp:
      'アカデミアの広大な図書室を一人で管理する司書。\r\n地味な見た目のメガネなドジっ子で、せわしなく\r\n図書室中を駆け回る姿がしばしば目撃されている。\r\n生徒からも「キャロちゃん」とあだ名で親しまれて\r\nいるが、図書室内で騒いだり本を粗末に扱ったり\r\nすると天雷が落ちるといわれる。',
    intro_zh: '',
    intro_en:
      '"The greatest crime sin in the library is to return the books you have taken back on the safe textile shelves. It\'s worth every million deaths."\n\n- Affiliation: Academy Librarian Teacher\n- Birthday: June 27\n- Height: 152 cm\n- Three Size: B75(A)/W59/H76\n- Likes: History books, dramas\n- Dislikes: Bad manners in her library\n\nThe librarian who alone manages the vast library of the Academia.\nShe is a plain-looking, bespectacled, clumsy girl who is often seen running around the library busily.\nShe is nicknamed "Caro-chan" by the students. It is said that if anyone make noise or treat books roughly poor in the library, thunder will strike them.\n\n[Translated from [url=https://cabbage-soft.com/products/jewelry/character/]Official Website[/url]]',
    blood_type: null,
    height: 152,
    weight: null,
    bust: 75,
    waist: 59,
    hips: 76,
    cup: 'A',
    age: null,
    birthday: [6, 27],
    gender: '{f,f}',
  },
  {
    id: 20,
    b_id: '106149',
    v_id: 'c104916',
    image: 'character/20/image/1dd84051-bfe5-4dc0-b446-32f9fa857c33.webp',
    name_jp: 'カーラ・S・クィンバーン',
    name_zh: null,
    name_en: 'Carla Sylvia Quinburn',
    aliases: ['Carla Sylvia Quinburn'],
    intro_jp:
      '最上級クラス「クラス・ダイヤ」の学級委員長。\r\n由緒ある家柄で紛れもないお嬢様のはずだが、\r\nそうと思えぬほど言葉遣いが汚い。\r\n同じ令嬢としてアリアンナを強くライバル視してお\r\nり、事あるごとに突っかかってくる。\r\nただし大体は空回りして自滅してしまう。',
    intro_zh: '',
    intro_en:
      '"The restroom crickets who have fallen behind are yelping and peevishly screaming about something, and it\'s not pretty. Oh-ho-ho!"\n\n- Affiliation: Diamond Class\n- Birthday: December 24th\n- Height: 161 cm\n- Three Size: B85(C)/W63/H89\n- Likes: Baccarat\n- Dislikes: Unfriendly things\n\nShe is the class president of the most advanced class, Diamond Class.\nAlthough she comes from a family with a long history and is a lady in her own right, her language is so foul that it is hard to believe that she is a lady.\nAs a daughter of the same family, she sees Arianna as a strong rival, and she pokes fun at her at every opportunity.\nHowever, she usually spins out of control and destroys herself.\n\n[Translated from [url=https://cabbage-soft.com/products/jewelry/character/]Official Website[/url]]',
    blood_type: null,
    height: 161,
    weight: null,
    bust: 85,
    waist: 63,
    hips: 89,
    cup: 'C',
    age: null,
    birthday: [12, 24],
    gender: '{f,f}',
  },
  {
    id: 21,
    b_id: '106150',
    v_id: 'c104917',
    image: 'character/21/image/72ab6ae4-c6bc-47f5-bf09-0c9fe688420b.webp',
    name_jp: 'ノア・フォン・レオンシュタイン',
    name_zh: null,
    name_en: 'Noa von Leonstein',
    aliases: ['Noa von Leonstein'],
    intro_jp:
      'マークスの妹にしてフリギア王家の第一王女。\r\nアカデミア附属校トップの超エリートでもある。\r\n楚々とした佇まいに高貴な立ち居振る舞いは、\r\nまさしく華やかな姫君そのもの。\r\n附属生ながら侮れない大人びた一面も覗かせる。\r\n「兄に見合わずよくできた妹」というのが、\r\n大体の共通認識。',
    intro_zh: '',
    intro_en:
      '"Eheh, thank you to all Pegasus members for all the help you\'ve given to my brother."\n\n- Affiliation: Academia Affiliated School\n- Birthday: February 14\n- Height: 150cm\n- Three Size: B78(B)/W58/H80\n- Likes: Her brother\'s paintings\n- Dislikes: Courtly ties\n[spoiler]- Will/Gem: "Velvet Dandelion Flower Snowstorm" Rhodonite Lion Heart[/spoiler]\n\nThe first princess of Phrygia\'s royal family, Markus\' younger sister.\nShe is also top-elite of Academia Affiliated School.\nWith her graceful appearance and noble-like manner, she is indubitably the most brilliant princess in a pure sense.\nAlthough she is an affiliated student, she has a mature side that cannot be underestimated.\nPeople have a common perception that she is "The refined sister in contrast with the indecorous brother."\n\n[Translated from [url=https://cabbage-soft.com/products/jewelry/character/]Official Website[/url]]',
    blood_type: null,
    height: 150,
    weight: null,
    bust: 78,
    waist: 58,
    hips: 80,
    cup: 'B',
    age: null,
    birthday: [2, 14],
    gender: '{f,f}',
  },
  {
    id: 22,
    b_id: null,
    v_id: 'c141169',
    image: 'character/22/image/39982541-e094-48bf-9337-df6367d18730.webp',
    name_jp: 'ギメル・ロードベイン',
    name_zh: null,
    name_en: 'Gimel Lordbane',
    aliases: [],
    intro_jp: '',
    intro_zh: '',
    intro_en:
      '- Affiliation: Medusa.\n- Will/Gem: [spoiler]"Sword of an Untold Interweaving Prayer\'s Love" Gordion Chrysaor.[/spoiler]\n\nThe Ringleader of Medusa organization.',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{m,m}',
  },
  {
    id: 23,
    b_id: null,
    v_id: 'c141175',
    image: 'character/23/image/dafa1c23-b4c3-4849-a906-f800fd3ca5a9.webp',
    name_jp: '',
    name_zh: null,
    name_en: 'Keito',
    aliases: [],
    intro_jp: '',
    intro_zh: '',
    intro_en:
      '[spoiler]\n- Will/Gem:\n"The Despised Mirror" Eyes Meteorite.\n"Six-way Flawless Flames of Calamity" Perfect Star Sapphire.\n"A Glittering Disaster Against the Covetous, Brilliant Extant Hometown of Nothingness - Rubra Melia Serpentes" Dead Serpent End Brilliant Wonder World.\n\nShe was the Queen Euryale, who got turned into an ugly sapphire serpent by the ugly Empress Palace.\nAfter death, her Dying Will was left behind in the veins of land throughout Phrygia. After a vein of land parts were brought up to the surface, Euryale appeared before Arianna and others, seemingly given an order to "put an end to the war."\nHowever, it is later known that Keito has materialized in every turning point in history, being the background causes of conflicts. She also caused the Seven Years War by killing Elisha, a sub-leader who founded Medusa organization.\nShe tried to end wars by doing the reverse, which is causing conflicts between species to decrease population. Once every lifeform would be exterminated, she would be able to build a world of only herself.\n\n[Translated from [url=https://dic.pixiv.net/a/ジュエリー・ハーツ・アカデミア]Pixiv Dictionary[/url]]\n[/spoiler]',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{f,f}',
  },
  {
    id: 24,
    b_id: null,
    v_id: 'c141173',
    image: 'character/24/image/fbe9b5ed-3f74-402f-b9ab-7430ccda1eb7.webp',
    name_jp: '',
    name_zh: null,
    name_en: 'Victor Ray',
    aliases: [],
    intro_jp: '',
    intro_zh: '',
    intro_en:
      '- Will/Gem: [spoiler]"A Thousand Feathers, A Thousand Cuts" Alexandrite Sword.[/spoiler]\n\nA homeroom teacher of Diamond Class, later Pegasus Class. He is also the Shooting Club\'s advisor.\nRay and Charlotte are on good terms with each other.\n\n[Translated from [url=https://dic.pixiv.net/a/ジュエリー・ハーツ・アカデミア]Pixiv Dictionary[/url]]',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{m,m}',
  },
  {
    id: 25,
    b_id: null,
    v_id: 'c141164',
    image: 'character/25/image/5540d23d-5e37-4b6a-a98d-58984aeebb40.webp',
    name_jp: 'キルスティン・ホロウグレイヴ',
    name_zh: null,
    name_en: 'Kirsten Hollowgrave',
    aliases: [],
    intro_jp: '',
    intro_zh: '',
    intro_en:
      '- Affiliation: Medusa.\n- Will/Gem: "Lamenting the End of Those Sorrowful Squiggling Worms" Spinel End.\n\nA human, she is one of the leaders of Medusa organization. [spoiler]Possessing exceptional strength in killing Vampires because of an ability called "The Mind\'s Eye," she is only second to Gimelord in terms of combat power among all Medusa members.\nShe was a main hunting target for many Vampires because of her genotype called "Rare Blood" which caused strong attraction to them. After barely managing to escape from her imprisonment by the Vampires, she has seen that her hometown had already been destroyed by them. Since then, she has been holding an immense hatred towards the Vampire species.[/spoiler]\n\n[Translated from [url=https://dic.pixiv.net/a/ジュエリー・ハーツ・アカデミア]Pixiv Dictionary[/url]]',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{f,f}',
  },
  {
    id: 26,
    b_id: null,
    v_id: 'c141162',
    image: 'character/26/image/4cad6583-3665-4a38-924f-2a5bc1296ba2.webp',
    name_jp: '',
    name_zh: null,
    name_en: 'Maynart Sky',
    aliases: [],
    intro_jp: '',
    intro_zh: '',
    intro_en:
      '- Affiliation: Medusa.\n- Will/Gem: "Seraphic Cross Karma" Clinochlore Crisscross.\n\nA Therion, he is one of the leaders of Medusa organization. He was once an Academia student, under teachings of Victor Ray. He\'s an easygoing person while also a smooth-talker.\n[spoiler]Maynart used to wield the gem Lapis Lazuli (the Will of pursuit) when he was a student. He once went on a journey to search for the fabled Golden Lord from fairy-tales, but at the end of the journey, his gem was broken to pieces. After obtaining a new Will, he became affiliated with Medusa. He also gained an ideal that "Justice from the minority can never be acknowledged so I chose to be evil. The disadvantaged have to be tainted with vice if they want to save themselves."[/spoiler]\n\n[Translated from [url=https://dic.pixiv.net/a/ジュエリー・ハーツ・アカデミア]Pixiv Dictionary[/url]]',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{m,m}',
  },
  {
    id: 27,
    b_id: null,
    v_id: 'c141172',
    image: 'character/27/image/118a96fc-0309-488a-ac5e-21e3e04be8d4.webp',
    name_jp: 'セシリア・クランルージュ',
    name_zh: null,
    name_en: 'Cecilia CranRouge',
    aliases: [],
    intro_jp: '',
    intro_zh: '',
    intro_en:
      '[spoiler]\n- Will/Gem: "Complete Devastation Collapse Alcea Meteor" Gibeon Meteorite.\n\nA Vampire girl who was confined together with χ as a test subject for "Extreme Transmutation" experiment. Having a special ability called "Heaven\'s Eye," she could "see" the ancient karma of geological veins of land. \nThroughout her long time in confinement, she managed to see the history of Vampire species suppressing Human species. She formed a strong ideal that "The Vampire species is a malice, a disgusting existence that should not be allowed to live in this world. All of them must be exterminated." This was formed into the Gem "Meteorite."\nThe "Meteorite" that Gimel used to confront Pegasus troops was Cecilia\'s "Dying Will" that she left behind for him.\n\n[Translated from [url=https://dic.pixiv.net/a/ジュエリー・ハーツ・アカデミア]Pixiv Dictionary[/url]]\n[/spoiler]',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{f,f}',
  },
  {
    id: 28,
    b_id: null,
    v_id: 'c141166',
    image: 'character/28/image/a9b247e5-c535-49fd-acc0-3727495d26a0.webp',
    name_jp: 'Dr.ゲゼルマンⅢ世',
    name_zh: null,
    name_en: 'Dr. Gesellmann Ⅲ',
    aliases: ['Bruno Gesellmann'],
    intro_jp: '',
    intro_zh: '',
    intro_en:
      '[spoiler]\n- Affiliation: Medusa.\n- Will/Gem: "Interweaving Lifeforms Crystal Phenomenon" Crystal Pareidolia.\n\nA doctor who has been in the quest to search for the Philosopher\'s Stone through experiments called "Extreme Transmutation" by manually creating Emerald and Diamond (members of The Great Four Gemstones.)\n\n[Translated from [url=https://dic.pixiv.net/a/ジュエリー・ハーツ・アカデミア]Pixiv Dictionary[/url]]\n[/spoiler]',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: 242,
    birthday: [10, 5],
    gender: '{m,m}',
  },
  {
    id: 29,
    b_id: null,
    v_id: 'c141171',
    image: null,
    name_jp: '',
    name_zh: null,
    name_en: 'χ',
    aliases: ['Kai-kun', 'Chi'],
    intro_jp: '',
    intro_zh: '',
    intro_en:
      '[spoiler]\nIn Amber Era 1586 (around 30 years before Souma enrolled in Academia), he was a human boy confined in the basement below Academia\'s construction establishment by Dr. Gesellmann. He was named "χ", being the initial test subject for the first "Extreme Transmutation" experiment. His true identity is Gimel Lordbane.\nAfter a long period in confinement, when Gesellmann finally showed up in person, he managed to time his escape. Furthermore, he also engraved a seal on Gesellmann\'s back as a contract to be his lifetime servant.\nGimel\'s Will is accompanied by Cecilia\'s Dying Will, a Vampire who was confined with him, escaped with him, and was burned away under the sunlight.\n\n[Translated from [url=https://dic.pixiv.net/a/ジュエリー・ハーツ・アカデミア]Pixiv Dictionary[/url]]\n[/spoiler]',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{m,m}',
  },
  {
    id: 30,
    b_id: null,
    v_id: 'c141174',
    image: 'character/30/image/249a042d-e3d8-475a-8cc5-8d0c87cc5ca7.webp',
    name_jp: '',
    name_zh: null,
    name_en: 'Sgt. Nestor',
    aliases: [],
    intro_jp: '',
    intro_zh: '',
    intro_en:
      'A sergeant from Phrygia Kingdom Army. \nHe requested for personnel from the Academia to fight against Medusa. He accompanied Pegasus Class on scouting for a while. He is often seen smoking tobacco.\n\n[Translated from [url=https://dic.pixiv.net/a/ジュエリー・ハーツ・アカデミア]Pixiv Dictionary[/url]]',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{m,m}',
  },
  {
    id: 31,
    b_id: '34202',
    v_id: 'c35175',
    image: 'character/31/image/49fd2799-6ed7-4fe2-bf79-39729b5b1b89.webp',
    name_jp: '箒星ひかり',
    name_zh: '帚星光',
    name_en: 'Houkiboshi Hikari',
    aliases: ['箒星 ひかり', 'ほうきぼし ひかり', 'ぴかりん', 'Pikarin'],
    intro_jp:
      '突然 彗星のごとく帰ってきた、暁斗たちの幼なじみ。\r\n明るく前向きな性格と、「やってみよう！」の一言で行動する旺盛な好奇心の持ち主。\r\n小さい頃はいつも 暁斗・沙夜 と3人で、秘密の天文台で星を観ていた。\r\n彼女にとって天体観測とは、銀河を旅する行為。 まだ見ぬ宙の彼方へ、その好奇心はまさしく “ひかり” の速度で広がっていった。\r\nが、そんな日々は自身の引っ越しによって終わりを迎えてしまう。\r\n\r\nその後は暁斗たちと疎遠となっていたが、年月を経てついに再開。\r\n当時は活発な男の子のようだったが、可愛くてスタイルも良い女子校生へと変身。\r\nそして、再び暁斗たちと星を眺める賑やかな日々を取り戻す。\r\n\r\n「それじゃ あたしたちも行こっか。 秘密の天文台へ」',
    intro_zh: '',
    intro_en:
      "Akito's childhood friend who suddenly appeared back in his life like a comet sweeping back on its orbit.\nHikari, Akito, and Saya always used to stargaze together at the secret observatory.\nShe's cheerful and positive, always willing to try something new.\nSometimes her insatiable curiosity can cause trouble for those around her\n\nStargazing for Hikari is just like traveling the galaxy together.\nHer interest in the stars, in seeing further, farther into the unknown propels her forward at the speed of light.\nShe began to stargaze after meeting Akita and Saya, but their meetings were cut short when her family moved away and she lost touch with her friends until they met again several years later.\nBy then, tomboyish country girl Hikari had grown into a cute and stylish teenager\n\n[From [url=https://moenovel.com/a-sky-full-of-stars/]Moenovel's site[/url]]",
    blood_type: 'o',
    height: 161,
    weight: null,
    bust: 91,
    waist: 58,
    hips: 88,
    cup: null,
    age: null,
    birthday: [8, 20],
    gender: '{f,f}',
  },
  {
    id: 32,
    b_id: '34203',
    v_id: 'c35176',
    image: 'character/32/image/7297e153-0ead-4ff9-9d04-a62edbe697d6.webp',
    name_jp: '天ノ川沙夜',
    name_zh: '天之川沙夜',
    name_en: 'Amanogawa Saya',
    aliases: [
      '天河沙夜',
      'あまのがわ さや',
      '通い妻ちゃん',
      '送饭妻',
      'Albireo Princess',
      'Commuter Wife',
    ],
    intro_jp:
      '濃い青と黄色みがかったオレンジの、左右で違う色の瞳・オッドアイを持つ少女。\r\n成績優秀でまじめ、一見しっかり者のようだが、それは頑張って演じている姿。\r\n本当の彼女はどこか抜けていて、放っておけないところがある。\r\n子供の頃に転校してきた際には、都会からすごい美少女が来たと近隣で噂になるも、\r\n当時はオッドアイがコンプレックスで、必死にサングラスで隠そうとしていた。\r\nその後 暁斗やひかりと仲良くなって、一緒に天体観測をするようになる。\r\n\r\n現在も照れ屋で人見知りだが、暁斗のことになると周囲の目を忘れていくらでも大胆になる。\r\n学園の部室に住み着いている暁斗を心配して毎日せっせと差し入れを運んでおり、\r\nその姿を見た周囲からは “通い妻ちゃん” の二つ名で呼ばれることも。\r\n\r\n「……仲間はずれ、やだからね」',
    intro_zh: '',
    intro_en:
      "A pretty girl with two different colored eyes, one a brilliant blue, and the other a yellow-orange. After seeing how she dutifully brings things for Akito when he starts sleeping in the astronomy club room, the other students begin calling her his “commuter wife”.\n\nShe transferred to Akito’s school when they were kids, and everyone was talking about the pretty girl who moved from the city.\nAt the time, she had a complex about her eyes, and always tried to hide them with sunglasses. But then, she became friends with Akito and Hikari, and began stargazing with them.\n\nStudious and serious, she gives off an aura of seeming mature for her age, but that’s actually an act, she’s actually a bit clumsy and people often feel the sudden urge to take care of her.\nShe’s shy and quiet around new people. It’s only when she’s near Akito that she can forget everyone around her and be herself.\n\n[From [url=https://moenovel.com/a-sky-full-of-stars/]Moenovel's site[/url]]",
    blood_type: 'a',
    height: 154,
    weight: null,
    bust: 80,
    waist: 57,
    hips: 83,
    cup: null,
    age: null,
    birthday: [1, 16],
    gender: '{f,f}',
  },
  {
    id: 33,
    b_id: '34204',
    v_id: 'c35177',
    image: 'character/33/image/539d7284-955d-46f4-913b-68add61b628d.webp',
    name_jp: '白鳥織姫',
    name_zh: '白鸟织姬',
    name_en: 'Shiratori Orihime',
    aliases: ['しらとり おりひめ', '姫さん', '姫ちゃん', 'Hime'],
    intro_jp:
      'エスカレーター式の名門校に通う3年生。 天文部の部長を務めている。\r\n実家がお金持ちで、丁寧な口調と鷹揚な態度が品の良さを感じさせるお嬢様。\r\n正統派美人だが、茶目っ気もあり若干 天然も入っている。\r\n怪しい占いに興じているが、実はそれは自分をミステリアスに見せるための演出。\r\n\r\nラスボス感が漂っており、彼女をよく知らない人からは敬遠されてしまうことも。\r\n実際は面倒見が良く後輩思いなので慕われており、男子にも後輩女子にもモテる。\r\n\r\n一度決めたことは貫き通す強い意志の持ち主……だが、その強さを保つために他人に弱さを見せられないでいる。\r\n\r\n「私は、運命を感じずにはいられないのです」',
    intro_zh: '',
    intro_en:
      "A senior at a private escalator school,\nTall and curvy, at a glance she’s a picture of beauty.\nCompared to clubs at other schools, the astronomy club at Orihime’s school is active and has alot of supplies.\n\nShe always speaks politely, and treats everyone graciously. At the same time, she can be a little flighty and mischievous.\nShe also likes to act mysteriously, showing interest in shady fortunes.\nOrihime can also be elegant, as she comes from a rich family.\n\nThis makes her seem a bit foreboding to some people, but she’s actually very kind to her juniors.\nFor this reason, people who don’t know her well keep their distance, but her juniors all adore her.\nShe’s popular with both boys and younger girls.\n\nOrihime is also fairly strong-willed, and no matter how nice she may seem, once she makes up her mind there’s no changing it. \nThis all an act to hide her insecurities, though.\n[From [url=https://moenovel.com/a-sky-full-of-stars/]Moenovel's site[/url]]",
    blood_type: 'o',
    height: 162,
    weight: null,
    bust: 93,
    waist: 57,
    hips: 89,
    cup: null,
    age: null,
    birthday: [3, 14],
    gender: '{f,f}',
  },
  {
    id: 34,
    b_id: '34205',
    v_id: 'c35363',
    image: 'character/34/image/7e79f91e-1212-4475-b8a6-959a823f9730.webp',
    name_jp: '日下部ころな',
    name_zh: '日下部可乐娜',
    name_en: 'Kusakabe Korona',
    aliases: ['くさかべ ころな', 'メローペ', 'Merope'],
    intro_jp:
      '暁斗たちより一つ年下なだけで、何かと報われない女の子。\r\nひかりに懐いていて暁斗のことが好きなのに、歳のせいで仲間に入れなかった。\r\nそれなのにちゃっかり仲間になっている沙夜が気に食わず、何かと突っかかってしまう。\r\n暁斗を見つけて駆け寄ったらドブに落ち、そのまま発見されず泣いていたというエピソードもある。\r\n\r\nネコみたいな性格で、懐いてる相手にはとことん甘えたがる。\r\n暁斗にも必死にアピールしており、ただしお子様なので羞恥心が足りず、天然の小悪魔になる。\r\n\r\n「これに懲りたら、もうちょっかい出さないでよねっ、わかった？」',
    intro_zh: '',
    intro_en:
      "One year younger than Akito and the others, nothing quite seems to go her way.\nShe thought Hikari was nice and had a crush on Akito.\nShe wanted to be a part of their group, but she was too young.\nThen she watched as Saya immediately became close to them and that didn’t sit right.\nThat, on top of everything else, made her hate the fact that she was a year younger all the more.\n\nShe loved Akito and tried desperately to get his attention, but as she was still a child with no sense of how to act properly, it made her act a little devilish.\nHer personality is a bit cat-like and contrary, but once she decides she likes you, she showers you with affection.\n\nThat said, things rarely go her way.\nFor example, should she spot Akito and run over greet him, calling, “Heyyy, Akkyyy”, that’s exactly the moment she’ll fall out of sight in a ditch and end up crying when he doesn’t find her.\n(true story)\n\n[From [url=https://moenovel.com/a-sky-full-of-stars/]Moenovel's site[/url]]",
    blood_type: 'ab',
    height: 153,
    weight: null,
    bust: 78,
    waist: 56,
    hips: 83,
    cup: null,
    age: null,
    birthday: [9, 3],
    gender: '{f,f}',
  },
  {
    id: 35,
    b_id: '34206',
    v_id: null,
    image: 'character/35/image/01235c6e-d9e9-4acf-bcf7-b0b956df8593.webp',
    name_jp: '宙見暁斗',
    name_zh: '宙见晓斗',
    name_en: null,
    aliases: ['そらみ あきと'],
    intro_jp:
      '学園で唯一の天文部員だが、星を観ないので付いたあだ名が “星を観ない天文部員”。\r\n部活動に天文部を選んだ理由は不純で、部室を寝床とするため。\r\n小さい頃に父がくれた天体望遠鏡で、ひかりと二人で月を観たのが星との出逢い。\r\nその後 沙夜も仲間に加わり、三人で星の世界にのめり込んでいった。\r\nしかし ひかりが引っ越した後は沙夜とも疎遠になり、星を観るのをやめてしまった。\r\n\r\n現在は恩師である美晴先生の実家のコンビニでバイトをしつつ、趣味で山に登ったりしている。\r\n山頂から朝陽を眺めながら飲む一杯のインスタントコーヒーを愛している。\r\n\r\n「一瞬―― 星に手が届いたみたいな気がした」',
    intro_zh: '',
    intro_en: '',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{}',
  },
  {
    id: 36,
    b_id: '36235',
    v_id: 'c39194',
    image: 'character/36/image/90fe10e0-c118-45b5-908a-f0af078a201d.webp',
    name_jp: '早乙女美晴',
    name_zh: null,
    name_en: 'Saotome Miharu',
    aliases: ['早乙女 美晴', 'さおとめ みはる', 'Saotome Miharu'],
    intro_jp:
      '暁斗たちの元担任。\r\n優しく、時に厳しく、若くて美人だったのもあって子供たちの憧れの先生だった。\r\n暁斗たちにとっては、天文のことを教えてくれた師でもある。 天文部のOG。\r\n\r\nだが、それも昔の話。\r\n学園が廃校となった際 仕事を辞めて、実家に引きこもってニート生活をしている。\r\n\r\n「……働いてるヤツがそんなに偉いのか！」',
    intro_zh: '',
    intro_en:
      "Akito and his others' former homeroom teacher. A pretty, young teacher who was gentle, but firm. They thought she was the perfect teacher.\n\nHowever, that's all in the past. Since the school closed, she quit working and shut herself away at her parent's home.\n\nAn alumna of the astronomy club, she was the person who taught Akito and the others about astronomy.\n\n[From [url=https://moenovel.com/a-sky-full-of-stars/]Moenovel's site[/url]]\n\n\"...Is being a worker that great?!\"",
    blood_type: null,
    height: 160,
    weight: null,
    bust: 88,
    waist: 61,
    hips: 90,
    cup: null,
    age: null,
    birthday: [3, 22],
    gender: '{f,f}',
  },
  {
    id: 37,
    b_id: '36236',
    v_id: 'c41551',
    image: 'character/37/image/0dacf076-e627-400a-b469-a0b177953f9f.webp',
    name_jp: '日下部武一',
    name_zh: null,
    name_en: 'Kusakabe Takeichi',
    aliases: ['日下部 武一', 'くさかべ たけいち'],
    intro_jp:
      '昔はガキ大将だった悪友。\r\n出会った当初は暁斗のことを快くなく思っていたが、やがて以前のことを謝罪し仲直りをする。\r\nそれからはよくつるむようになり、今では一番の男友達。 いつも軽口を言い合ったりする。\r\n\r\n暁斗と同じ星野第一に通っている。\r\nバスケ部に入っていて、1年ながらレギュラー争いをしているらしい。\r\n\r\n「おかしいだろ、“星を観ない天文部員”なんて」',
    intro_zh: '',
    intro_en:
      "[url=/c36076]Akito's[/url] childhood friend and also his best friend. In the past, he used to be a bully, but when he met with Akito and the others, he apologized for his deeds and became friends with them. Also a member of the basketball club.",
    blood_type: null,
    height: 178,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [12, 12],
    gender: '{m,m}',
  },
  {
    id: 38,
    b_id: '36237',
    v_id: 'c39195',
    image: 'character/38/image/574cde67-3b4d-49b1-8e80-6d652ec270bd.webp',
    name_jp: '吉岡帆乃香',
    name_zh: null,
    name_en: 'Yoshioka Honoka',
    aliases: ['吉岡 帆乃香', 'よしおか ほのか', 'ほのほの', 'Yoshi-yoshi'],
    intro_jp:
      '明光学院に通う 1年生で、織姫から天文部部長を引き継いだ。\r\nほしのなか市内の天文部の集まりである “むつらぼしの会” では、会長である織姫を補佐する秘書のような立場になっている。\r\n\r\n織姫が夢見がちなため相対的にしっかりしているように見えるが、年相応な至って普通の女の子。\r\n意外と抜けていることもあり、織姫と一緒に あわあわ することも。\r\n\r\n「会長の補佐兼現部長を務めさせていただいております、吉岡です」',
    intro_zh: '',
    intro_en:
      "A first-year student at Meikou Academy, who takes over the position of astronomy club president from Orihime.\n\nWhen the astronomy clubs gather in Hoshinonaka City to form the 6 Stars Club, she takes the position of Orihime's secretary-like assistant.\n\nWhen compared to Orihime, who always has her head in the clouds, she seems to be rather mature, but in reality she's a normal girl for her age. There are even times when she spaces out and joins in Orihime's silliness.\n\n[From [url=https://moenovel.com/a-sky-full-of-stars/]Moenovel's site[/url]]\n\n\"I am Yoshioka, and I serve as the President's assistant and director\"",
    blood_type: null,
    height: 159,
    weight: null,
    bust: 84,
    waist: 58,
    hips: 86,
    cup: null,
    age: null,
    birthday: [7, 16],
    gender: '{f,f}',
  },
  {
    id: 39,
    b_id: '36238',
    v_id: 'c39196',
    image: 'character/39/image/2420040b-a839-42aa-828c-1cac57395cca.webp',
    name_jp: '加納紀子',
    name_zh: '加纳纪子',
    name_en: 'Kanou Noriko',
    aliases: ['かのう のりこ'],
    intro_jp:
      'ひかりの先輩で、天ノ中 の天文部部長。\r\n天文の知識がなく導いてくれる先輩もいなかったため、今まで天体観測をしたことも無かった。\r\n\r\nまじめでおとなしいように見えて、独特なリアクションをすることも。\r\n学園での ひかりの様子を知る唯一の人。\r\n\r\n「私、実は初めてなんです、観望会って。 だから、今日楽しみにして来ました」',
    intro_zh: '',
    intro_en:
      "Hikari's senpai, and the astronomy club president at Tennochu Academy. Since she's has no astronomy club or any older members to teacher, she has not done any astronomical observations.\n\nShe's serious and quiet, and also makes unique reactions. At school, she's the only one who really knows Hikari.\n\n\"This will be my first time going to an observation meeting, so I look forward to today.\"",
    blood_type: null,
    height: 156,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [5, 7],
    gender: '{f,f}',
  },
  {
    id: 40,
    b_id: '36239',
    v_id: 'c39197',
    image: 'character/40/image/6d7a83ef-01bb-446d-9485-f2a492dff7f5.webp',
    name_jp: '陣野鳴枝',
    name_zh: '阵野鸣枝',
    name_en: 'Jinno Narue',
    aliases: ['じんの なるえ'],
    intro_jp:
      '天ノ中西 の地学部の部長。\r\n天文も地学の一部ということで、天ノ中西の地学部は天文しかやっていない。\r\n\r\nこの部は代々ガジェット派で、彼女も一眼レフで天体写真を撮る活動をメインにしている。\r\n勝気でややキツイ言葉を使うことがあるが、冷静に状況を見るクールな一面も。\r\n\r\n「計画書見たよ。 ちょっと面白そうだって思った」',
    intro_zh: '',
    intro_en:
      "Amanonakanishi's Earth Science Club's president. Since Astronomy is considered a part of Earth Science, Amanokonakanishi's Earth Science Club ends up only doing astronomy.\n\nThe club has been proficient with gadgets for generations, and the club's main part of the Astronomy Group Activities is to take pictures with a single lens reflex camera. She is very determined and sometimes uses some harsh words, but is also very cool and composed.\n\n\"I looked at the plan. I thought it seemed interesting.\"",
    blood_type: null,
    height: 163,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [5, 28],
    gender: '{f,f}',
  },
  {
    id: 41,
    b_id: '36240',
    v_id: 'c41561',
    image: 'character/41/image/c0e56916-107f-4be0-9ec7-cb6355547c79.webp',
    name_jp: '田尻啓介',
    name_zh: null,
    name_en: 'Tajiri Keisuke',
    aliases: ['たじり けいすけ'],
    intro_jp:
      '工業系の男子校・諸美沢 天文部の部長。\r\nこの天文部は “高価な望遠鏡より、一人一つの双眼鏡” をモットーに活動している。\r\n\r\nがっしりした体型と体育会系のノリをしているが、強面な顔に似合わず柔らかく丁寧な表情と物腰。\r\n\r\n「うちは、今の活動で満足していますので」',
    intro_zh: '',
    intro_en: 'The president of Morumisawa Boys Academy astronomical club.',
    blood_type: null,
    height: 182,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [10, 25],
    gender: '{m,m}',
  },
  {
    id: 42,
    b_id: '43461',
    v_id: 'c40128',
    image: 'character/42/image/de38463a-895c-40b2-becb-33971d4baff9.webp',
    name_jp: '山田陽南',
    name_zh: '山田阳南',
    name_en: 'Yamada Hinami',
    aliases: ['やまだ ひなみ', 'Hinamin'],
    intro_jp:
      '星野第一の天文部に在籍する暁斗の後輩。 ころなの友人で、かなりの不思議ちゃん。\r\n何を考えているのかイマイチよく分からないが、天文には興味を持っている。\r\n常に少し眠い目をしていて、無表情で突飛なことをぼそっと言ったりするタイプ。\r\nぼーっとしてるようで、頭の中では謎の壮大なストーリーが展開していたりする。\r\n沙夜を “アルビレオのプリンセス” と崇拝している。\r\n\r\n本篇中以配角身份出场，FD刚发售时没有个人线路\r\n2016年6月16日，根据投票结果，pulltop在FD的DLC“ひなみん√アペンドパッチ”中添加了其个人线',
    intro_zh: '',
    intro_en:
      "[url=/c35363]Korona's[/url] friend who's quite eccentric. To this day Akito and the others still don't know what she's thinking. She's interested in astronomy.\n\nMost times she has a look of dead tiredness on her face, but will sometimes mumble things about flying through the sky. Basically while she looks like she's not thinking of anything at all, her head is perpetually full of fantastic stories.\n\nShe admires Saya, calling her the \"Albireo Princess\".\n\n[From [url=https://moenovel.com/a-sky-full-of-stars/]Moenovel's site[/url]]\n\n\"It's a detailed simulation of what would happen if a person was sucked into a black hole. Look...\"",
    blood_type: null,
    height: 152,
    weight: null,
    bust: 73,
    waist: 55,
    hips: 74,
    cup: null,
    age: null,
    birthday: [2, 1],
    gender: '{f,f}',
  },
  {
    id: 43,
    b_id: '77048',
    v_id: null,
    image: 'character/43/image/e6ce094c-07eb-42b5-ad70-d13659711d41.webp',
    name_jp: '恵風学園',
    name_zh: '惠风学园',
    name_en: null,
    aliases: [],
    intro_jp:
      '工学系の5年制学校で、普通の教科の他に専門科目の授業が入っており、学年が上がるごとに専門科目が増えるカリキュラム。学園の歴史は古いが、物語開始の1年前に新校舎が完成し、曲線を多用した近未来的な空間になっている。完全バリアフリーなので、車椅子の小鳥も楽に移動できる。校舎建て替えを機に女子生徒の入学優遇措置を取っており、工学系の学校には珍しく生徒の男女比率はほぼ半々。',
    intro_zh: '',
    intro_en: '',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{}',
  },
  {
    id: 44,
    b_id: '136391',
    v_id: 'c82456',
    image: 'character/44/image/390dca12-cb71-4628-9880-2df0c1a5295f.webp',
    name_jp: 'コタロウ',
    name_zh: null,
    name_en: 'Kotarou',
    aliases: ['Kotarou', 'Kota-chan', 'Kotie'],
    intro_jp: '',
    intro_zh: '',
    intro_en:
      'A Shiba Inu who is usually shy and timid. If someone he likes comes along, he will wag his tail and want to play. He especially likes Saya, who gives him a lot of attention. He likes her more than the Saotome family, his current owners.\n\nAkito and Hikari helped save him from a river when they were kids.',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{m,m}',
  },
  {
    id: 45,
    b_id: '136392',
    v_id: 'c41559',
    image: 'character/45/image/58e1b7ea-3d89-48e3-9455-b292f00b1bdc.webp',
    name_jp: '豊田',
    name_zh: null,
    name_en: 'Toyoda',
    aliases: ['Toyoda', '豊田', 'とよだ'],
    intro_jp:
      '天ノ中西 地学部所属で陣野の後輩。\r\n丁寧な口調の草食系。\r\n天体写真を撮影していて、得意分野になると饒舌になることも。\r\n「天体ガイドに投稿したので、もしかしたら……来月号に載るかもです」',
    intro_zh: '',
    intro_en:
      'A quiet junior taking the place of Club President from [url=/c39197]Narue[/url] after she graduated.',
    blood_type: null,
    height: 168,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [11, 3],
    gender: '{m,m}',
  },
  {
    id: 46,
    b_id: '136393',
    v_id: 'c41560',
    image: 'character/46/image/e3073912-1d2d-4f15-8124-8a02c98d380a.webp',
    name_jp: '川中島',
    name_zh: null,
    name_en: 'Kawanakajima',
    aliases: ['Kawanakajima', '川中島', 'かわなかじま'],
    intro_jp:
      '諸美沢 天文部所属、田尻の後輩。\r\n気配りできる気持ちのいい奴。\r\n気合いの入った容姿に似合わず、星座を見てポエムを詠むのが好き。 心は乙女。\r\n「うっす。 俺らは、星座神話をモチーフにしたポエム作りをやってました！」',
    intro_zh: '',
    intro_en:
      "A student at an all-boys' school who loves astronomical poems. He takes the place of [url=/c41561]Tajiri[/url] as Club President after he graduates.",
    blood_type: null,
    height: 172,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [4, 30],
    gender: '{m,m}',
  },
  {
    id: 47,
    b_id: '136394',
    v_id: 'c41562',
    image: 'character/47/image/ef80738e-7fe1-4c74-9155-226c33896c23.webp',
    name_jp: '森田一郎',
    name_zh: null,
    name_en: 'Morita Ichirou',
    aliases: ['Morita Ichirou', '森田 一郎', 'もりた いちろう'],
    intro_jp:
      'チャンプ爺さんの知り合いで、プラネタリウムの館長をしている人。\r\n独特の雰囲気を持った、すらっとした穏和で知的な紳士。\r\n星に対する自分の信念を持っていて、それを貫く姿勢を持っている。\r\n「うん、なかなかいい望遠鏡だ。 見せてもらってもいいですか？」',
    intro_zh: '',
    intro_en: 'The director of the planetarium.',
    blood_type: null,
    height: 174,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{m,m}',
  },
  {
    id: 48,
    b_id: '136440',
    v_id: null,
    image: 'character/48/image/50b4559a-a6b4-4111-a02e-43e2834db907.webp',
    name_jp: 'チャンプ爺さん',
    name_zh: null,
    name_en: null,
    aliases: ['チャンプ爺さん'],
    intro_jp:
      '『さをとめ』 の常連客の爺さん。\r\nエロ本を週刊漫画雑誌チャンプに重ねて買っていくことから、このあだ名がついた。\r\nシャイなところがあり、若い女性と話すのが苦手。\r\n暁斗との間には謎の友情が芽生えていたりする。\r\n実は元ガラス工芸職人で、反射望遠鏡の主鏡研磨などを行っていたこともある。\r\n「お主がいるおかげで、わしはいつも安心してエロ本が買える」',
    intro_zh: '',
    intro_en: '',
    blood_type: null,
    height: null,
    weight: null,
    bust: null,
    waist: null,
    hips: null,
    cup: null,
    age: null,
    birthday: [],
    gender: '{}',
  },
]
