export const game_links = [
  {
    id: 1,
    url: 'https://madosoft.net/rerecall/',
    label: 'Official website',
    name: 'website',
    game_id: 1,
  },
  {
    id: 2,
    url: 'https://erogamescape.dyndns.org/~ap2/ero/toukei_kaiseki/game.php?game=37533',
    label: 'ErogameScape',
    name: 'egs',
    game_id: 1,
  },
  {
    id: 3,
    url: 'https://www.bilibili.com/video/av114687488297141/',
    label: 'Official website',
    name: 'website',
    game_id: 1,
  },
  {
    id: 4,
    url: 'https://tieba.baidu.com/p/9672154092',
    label: 'Official website',
    name: 'website',
    game_id: 1,
  },
  {
    id: 5,
    url: 'https://cabbage-soft.com/products/jewelry/',
    label: 'Official website',
    name: 'website',
    game_id: 2,
  },
  {
    id: 6,
    url: 'https://erogamescape.dyndns.org/~ap2/ero/toukei_kaiseki/game.php?game=32066',
    label: 'ErogameScape',
    name: 'egs',
    game_id: 2,
  },
  {
    id: 7,
    url: 'https://www.melonbooks.co.jp/detail/detail.php?product_id=1373744',
    label: 'Melonbooks.co.jp',
    name: 'melonjp',
    game_id: 2,
  },
  {
    id: 8,
    url: 'http://www.getchu.com/soft.phtml?id=1171051',
    label: 'Getchu',
    name: 'getchu',
    game_id: 2,
  },
  {
    id: 9,
    url: 'https://www.dmm.co.jp/mono/pcgame/-/detail/=/cid=2097apc14056/',
    label: 'DMM',
    name: 'dmm',
    game_id: 2,
  },
  {
    id: 10,
    url: 'https://ja.wikipedia.org/wiki/見上げてごらん、夜空の星を',
    label: 'Wikipedia (ja)',
    name: 'jawiki',
    game_id: 3,
  },
  {
    id: 11,
    url: 'https://www.wikidata.org/wiki/Q24870119',
    label: 'Wikidata',
    name: 'wikidata',
    game_id: 3,
  },
  {
    id: 12,
    url: 'https://www.mobygames.com/game/a-sky-full-of-stars',
    label: 'MobyGames',
    name: 'mobygames',
    game_id: 3,
  },
  {
    id: 13,
    url: 'https://gamefaqs.gamespot.com/-/227797-',
    label: 'GameFAQs',
    name: 'gamefaqs_game',
    game_id: 3,
  },
  {
    id: 14,
    url: 'http://howlongtobeat.com/game.php?id=51505',
    label: 'HowLongToBeat',
    name: 'howlongtobeat',
    game_id: 3,
  },
]
