export const games = [
  {
    id: 1,
    v_id: 'v53590',
    b_id: '524427',
    title_jp: 'ハミダシクリエイティブ Re:Re:call',
    title_zh: '常轨脱离Creative Re:Re:call',
    title_en: 'HAMIDASHI CREATIVE Re:Re:call',
    aliases: ['Hamikuri Re:Re:call', 'ハミリリ', 'Hamiriri', '富婆妹FD2', '하미리리'],
    intro_jp:
      'くじ引きで生徒会長に任命された「和泉智宏」は、\r\n初めこそ安心安全を心がけ無難に業務を行っていたものの、\r\nいつの間にやら人並みの責任感を覚えはじめたばかりか、\r\n他の役員と休日に出かけるほど活動的になっていく。\r\n\r\nある日、個人サークルのスタッフとして同人誌即売会に参加させられた智宏は、\r\n本を販売し終えて、飲みものを買いに席を離れる。\r\nその途中、ふとした気の迷いで足を踏みいれた一次創作のスペースに、\r\nいるはずのない人物の姿を目撃して……？\r\n\r\nこれは本編から「ハミダシ」た、正ヒロインではない女の子の物語。',
    intro_zh: '',
    intro_en:
      'Izumi Tomohiro was appointed student council president by drawing lots. At first, he carries out his duties adequately and without risk, but before he knows it, he begins to feel a commonplace sense of commitment. He becomes so active that he even goes out on his days off with the other members.\n\nOne day, Tomohiro is forced to participate in a doujinshi sale as a staff member of a kojin circle. After selling the books, he leaves his seat to buy a drink. On the way, he wanders into the original creation space on a whim, and spots someone who shouldn\'t be there...\n\nThis is the story of a girl who is not the main heroine, and who strayed out ("hamidashi") from the main story.\n\n[Translated from the [url=https://madosoft.net/rerecall/story]official website[/url]]',
    release_date: '2025-04-24T16:00:00.000Z',
    release_date_tba: false,
    extra_info: [],
    tags: [
      'Galgame',
      'まどそふと',
      'FD',
      '废萌',
      '宇都宮つみれ',
      '2025',
      'PC',
      'R18',
      '白毛',
      '校园',
      '游戏',
      '纯爱',
      '秋野花',
      '東ノ助',
      'Mado',
      '妹',
      'GAL',
      '茜屋',
      '汉化',
      'MadoSoft',
      '甲木順之助',
      'AVG',
      'erogame',
      '欢乐',
      '治愈',
      '傲娇',
      '5分',
    ],
    staffs: [
      {
        name: '甲木順之助',
        role: '剧本',
      },
      {
        name: '宇都宮つみれ',
        role: '原画',
      },
      {
        name: 'もじゃすびい',
        role: '导演',
      },
      {
        name: '茜屋',
        role: 'SD原画',
      },
    ],
    nsfw: false,
    type: null,
    platform: ['win'],
    status: 1,
    hot_score: 18.28440361318448,
    views: 37479,
    downloads: 208,
  },
  {
    id: 2,
    v_id: 'v33175',
    b_id: '363763',
    title_jp: 'ジュエリー・ハーツ・アカデミア -We will wing wonder world-',
    title_zh: '霞流宝石心 -壮志凌云振寰宇-',
    title_en: '',
    aliases: [
      'ジュエハ',
      'jeweha',
      '宝石心学园',
      '寶石心學院物語 -We will wing wonder world-',
      '쥬얼리 하츠 아카데미아',
      '쥬에하',
      '宝石心学院',
    ],
    intro_jp:
      '「輝け、僕らの意志──」\r\n\r\nフリギア王立ジュエリー・アカデミア──\r\n\r\nそこは『意志（ジェム）』と呼ばれる不思議な宝石を研究する学園。\r\n主人公ソーマ・ジェイスはアカデミアに眠る『賢者の石』を探るべく、\r\nエージェントとして『クラス・ダイヤ』への潜入を試みる。\r\nしかし……彼が配属されたのは謎の新設学級『クラス・ペガサス』だった。\r\n\r\n──素性を隠す外国のスパイ・ソーマ。\r\n──剣にしか興味のない女子・ベルカ。\r\n──誰ともつるまない孤高の不良・ヴェオ。\r\n──獣人にして稀代の才媛・メア。\r\n──成績も態度も最悪の王子・マークス。\r\n──唯一まともなクラスの良心・アリアンナ。\r\n\r\nペガサス組に揃ったのは目的も国籍もバラバラな６人の少年少女。\r\n彼らはしばしば反発し合いながらも、やがて世界を脅かす危機に直面することになる。\r\n\r\n『石喰い』──\r\n\r\nそれは、ノヴァ大陸全土を石化せんと迫る謎の災厄。\r\nその最前線に位置した彼らは、元凶の組織《メデューサ》との闘争に巻き込まれていき……？\r\n\r\n「いくよみんな──わたし達の全力を、思いっきりぶつけてやろう！」\r\n\r\n果たしてソーマはミッションを達成できるのか。\r\nそして、大陸を喰らう石化の脅威に打ち勝つことはできるのか。\r\n\r\n世界を羽ばたく意志と絆の冒険譚──ここに輝く。 ',
    intro_zh: '',
    intro_en:
      '"Shine, our Will."\n\nPhrygia Royal, Academy of Jewelry, is a place where mysterious gem stone called "The Will (意志 Ishi)" are researched.\n\nThe main character, Souma Jace, attempts to infiltrate "Diamond Class" as an agent to search for the "Philosopher\'s Gem Stone" that lies dormant in the academy. But he is assigned to a mysterious new class that called "Pegasus Class".\n\n- Souma, a foreign agent who hides his true identity.\n- Berka, a girl who is only interested in swordship.\n- Veo, a solitary and loner delinquent who doesn\'t hang out with anyone.\n- Mare, a kemonomimi beast who has a rare talent.\n- Markus, a foreign prince with the worst grades and attitude.\n- Arianna, the only decent conscience member in the class.\n\nThe Pegasus Class group is made up of six boys and girls with different purposes and nationalities.\nThey often rebel against each other, but soon find themselves facing a crisis that threatens the world.\n\n"The Stone Eaters", a mysterious disaster that threatens to petrify the entire Nova continent. Located on the front lines, they become embroiled in a struggle against the "Medusa," the organization responsible for the disaster.\n\n"Let\'s go, everyone - let\'s give it everything what we\'ve got!"\n\nWill Soma be able to accomplish his mission and able to overcome the threat of petrification that threatens to destroy the continent?\n\nAn adventure tale of The Wills and bonds that fly across the world - here it shines.\n\n[Translated from [url=http://cabbage-soft.com/]Official Website[/url]]',
    release_date: '2022-07-28T16:00:00.000Z',
    release_date_tba: false,
    extra_info: [],
    tags: [
      'Galgame',
      '冬茜トム',
      'しらたま',
      'きゃべつそふと',
      '萝莉',
      '2022',
      'PC',
      '兽耳',
      'GAL',
      '游戏',
      '我永远喜欢しらたま',
      '废萌',
      '画风好',
      'CabbageSoft',
      '剧情',
      '汉化',
      '生肉',
      '剧情作',
      'R18',
      '战斗',
      '奇幻',
      '白玉',
      '等汉化',
      '悬疑',
      '妹',
      'メア',
      '纯爱',
      '吸血鬼',
      '幼驯染',
      '燃',
    ],
    staffs: [
      {
        name: '冬茜トム',
        role: '剧本',
      },
      {
        name: 'しらたま、よねぞう（サブ）',
        role: '原画',
      },
      {
        name: 'KyoKa',
        role: '主题歌演出',
      },
      {
        name: 'KyoKa',
        role: '主题歌作词',
      },
      {
        name: '藤井稿太郎',
        role: '主题歌作曲',
      },
      {
        name: '藤井稿太郎',
        role: '音乐',
      },
      {
        name: 'プリズムビジョン',
        role: '动画制作',
      },
      {
        name: 'しげた',
        role: '导演',
      },
    ],
    nsfw: false,
    type: null,
    platform: ['win', 'ps4', 'swi'],
    status: 1,
    hot_score: 15.31126712995152,
    views: 6216,
    downloads: 131,
  },
  {
    id: 3,
    v_id: 'v16560',
    b_id: '121488',
    title_jp: '見上げてごらん、夜空の星を',
    title_zh: '仰望夜空的星辰',
    title_en: 'A Sky Full of Stars',
    aliases: ['Full of Stars', 'MiaZora', '看星星', '미아게테', '抬头看看吧，看那天上的繁星'],
    intro_jp:
      '「この列車は宙をゆく銀河鉄道天文台！\r\n　太陽系を征服しても、我ら三人の旅はまだまだ終わらない」\r\nどこへでも行けるって思ってた。\r\n宇宙の謎を全て解き明かすことだって、手を伸ばせば あの星を掴むことだってできる、そう思ってた――\r\n子供の頃、幼なじみたちと毎晩のように星を観ていた宙見暁斗。\r\n天体望遠鏡の先に浮かぶ無数の光に、胸を躍らせていた。\r\nそれはまるで、銀河を旅するような日々だった。\r\nだがしかし、成長した暁斗は “星を観ない天文部員” と呼ばれるようになっていた。\r\nやめてしまったのだ、夜空を見上げることを。\r\nそんな彼のもとに、“むつらぼしの会” への参加要請が届く。\r\n暁斗は誘いを断るべく会へ足を運ぶが、そこで思いがけない再会をする。\r\nそこには、どこか遠くへ引っ越していったはずの幼なじみ・箒星ひかり がいたのだ。\r\nいつも傍にいてくれた、もう一人の幼なじみ・天ノ川沙夜。\r\nむつらぼしの会 復活を望む他校の先輩・白鳥織姫。\r\nそして、暁斗を慕う後輩・日下部ころな。\r\n別れと再会、新しい出逢いを経て、再び夜空を見上げるようになった暁斗は取り戻していく。\r\nもう二度と戻らないと思っていた、大切な想いの数々を。\r\nそして知っていく。 未だ出逢ったことのなかった 特別な夜 を。\r\n「さあ、銀河の謎を解き明かすべく、次なる目的地へ向かおう！」\r\n仲間たちと宙を見上げ、星々を巡りゆく青春の日々が、また始まる。',
    intro_zh: '',
    intro_en:
      'When Akito was small, he would gaze at the stars every night with his childhood friends Hikari and Saya. He felt excited seeing the twinkles of countless stars through the telescope lens, so close that it felt like he could reach out and grab them with his hand. It inspired dreams of journeys into space, exploring the Milky Way and solving the mysteries of the galaxy. However, now he no longer looks up at the night sky and was called the ‘astronomy club member who doesn’t watch the stars’.\n\nHe received an invitation to attend the revival of the ‘Pleiades meeting’ with astronomy clubs from other schools in the area and decided to go to their next meeting to turn it down in person. There, he had an unexpected reunion with Hikari, whom he hadn’t seen since she moved some place far away. Together with Saya, senpai Orihime and kouhai Korona, his long-lost desire to look up at the stars has been rekindled and their star-filled youthful days full of new precious memories begin.\n\n[From [url=https://omochikaeri.wordpress.com/2015/12/18/december-2015-eroge-releases/]Hau~ Omochikaeri![/url]]',
    release_date: '2015-12-17T16:00:00.000Z',
    release_date_tba: false,
    extra_info: [],
    tags: [
      'Galgame',
      'pulltop',
      '看星星',
      '天文',
      '幼驯染',
      '异色瞳',
      '紺野アスタ',
      '青春',
      '汉化',
      'PC',
      '2015',
      '纯爱',
      'GAL',
      '废萌',
      'ADV',
      '八島タカヒロ',
      '幼なじみ',
      'R18',
      '游戏',
      'AVG',
      '又吉愛',
      'STEAM',
      '遠野そよぎ',
      '校园',
      '萌作',
      '治愈',
      '基井あゆむ',
      '小鸟居夕花',
      '萌系',
      '2015-12',
    ],
    staffs: [
      {
        name: '紺野アスタ(共通パート / 箒星ひかり / 天ノ川沙夜)、高嶋栄二(白鳥織姫 / 日下部ころな)',
        role: '剧本',
      },
      {
        name: '紺野アスタ',
        role: '企画',
      },
      {
        name: '八島タカヒロ、基井あゆむ',
        role: '原画',
      },
      {
        name: '田口まこと',
        role: 'SD原画',
      },
      {
        name: 'TWOFIVE',
        role: '音乐',
      },
      {
        name: '霜月はるか',
        role: '主题歌演出',
      },
      {
        name: 'Minao Ohse',
        role: '主题歌作词',
      },
      {
        name: 'おおくまけんいち',
        role: '主题歌作曲',
      },
    ],
    nsfw: false,
    type: null,
    platform: ['win', 'dvd'],
    status: 1,
    hot_score: 12.101883957963532,
    views: 2874,
    downloads: 33,
  },
]
