// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/aicatalogmodel"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/aicatalogprovider"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/pgvalue"
)

// AICatalogModel is the model entity for the AICatalogModel schema.
type AICatalogModel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID string `json:"provider_id,omitempty"`
	// ModelKey holds the value of the "model_key" field.
	ModelKey string `json:"model_key,omitempty"`
	// CanonicalID holds the value of the "canonical_id" field.
	CanonicalID *string `json:"canonical_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type *string `json:"type,omitempty"`
	// Family holds the value of the "family" field.
	Family *string `json:"family,omitempty"`
	// Npm holds the value of the "npm" field.
	Npm *string `json:"npm,omitempty"`
	// InputModalities holds the value of the "input_modalities" field.
	InputModalities pgvalue.Strings `json:"input_modalities,omitempty"`
	// OutputModalities holds the value of the "output_modalities" field.
	OutputModalities pgvalue.Strings `json:"output_modalities,omitempty"`
	// ContextLimit holds the value of the "context_limit" field.
	ContextLimit *int `json:"context_limit,omitempty"`
	// OutputLimit holds the value of the "output_limit" field.
	OutputLimit *int `json:"output_limit,omitempty"`
	// Temperature holds the value of the "temperature" field.
	Temperature bool `json:"temperature,omitempty"`
	// ToolCall holds the value of the "tool_call" field.
	ToolCall bool `json:"tool_call,omitempty"`
	// Reasoning holds the value of the "reasoning" field.
	Reasoning bool `json:"reasoning,omitempty"`
	// StructuredOutput holds the value of the "structured_output" field.
	StructuredOutput *bool `json:"structured_output,omitempty"`
	// InputPrice holds the value of the "input_price" field.
	InputPrice *float64 `json:"input_price,omitempty"`
	// OutputPrice holds the value of the "output_price" field.
	OutputPrice *float64 `json:"output_price,omitempty"`
	// CacheReadPrice holds the value of the "cache_read_price" field.
	CacheReadPrice *float64 `json:"cache_read_price,omitempty"`
	// CacheWritePrice holds the value of the "cache_write_price" field.
	CacheWritePrice *float64 `json:"cache_write_price,omitempty"`
	// PriceTiers holds the value of the "price_tiers" field.
	PriceTiers jsontext.Value `json:"price_tiers,omitempty"`
	// ReleaseDate holds the value of the "release_date" field.
	ReleaseDate *string `json:"release_date,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt time.Time `json:"synced_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AICatalogModelQuery when eager-loading is set.
	Edges        AICatalogModelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AICatalogModelEdges holds the relations/edges for other nodes in the graph.
type AICatalogModelEdges struct {
	// Provider holds the value of the provider edge.
	Provider *AICatalogProvider `json:"provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AICatalogModelEdges) ProviderOrErr() (*AICatalogProvider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aicatalogprovider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AICatalogModel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aicatalogmodel.FieldPriceTiers:
			values[i] = new([]byte)
		case aicatalogmodel.FieldInputModalities, aicatalogmodel.FieldOutputModalities:
			values[i] = new(pgvalue.Strings)
		case aicatalogmodel.FieldTemperature, aicatalogmodel.FieldToolCall, aicatalogmodel.FieldReasoning, aicatalogmodel.FieldStructuredOutput:
			values[i] = new(sql.NullBool)
		case aicatalogmodel.FieldInputPrice, aicatalogmodel.FieldOutputPrice, aicatalogmodel.FieldCacheReadPrice, aicatalogmodel.FieldCacheWritePrice:
			values[i] = new(sql.NullFloat64)
		case aicatalogmodel.FieldID, aicatalogmodel.FieldContextLimit, aicatalogmodel.FieldOutputLimit:
			values[i] = new(sql.NullInt64)
		case aicatalogmodel.FieldProviderID, aicatalogmodel.FieldModelKey, aicatalogmodel.FieldCanonicalID, aicatalogmodel.FieldName, aicatalogmodel.FieldType, aicatalogmodel.FieldFamily, aicatalogmodel.FieldNpm, aicatalogmodel.FieldReleaseDate:
			values[i] = new(sql.NullString)
		case aicatalogmodel.FieldSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AICatalogModel fields.
func (_m *AICatalogModel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aicatalogmodel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case aicatalogmodel.FieldProviderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.String
			}
		case aicatalogmodel.FieldModelKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_key", values[i])
			} else if value.Valid {
				_m.ModelKey = value.String
			}
		case aicatalogmodel.FieldCanonicalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field canonical_id", values[i])
			} else if value.Valid {
				_m.CanonicalID = new(string)
				*_m.CanonicalID = value.String
			}
		case aicatalogmodel.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case aicatalogmodel.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = new(string)
				*_m.Type = value.String
			}
		case aicatalogmodel.FieldFamily:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field family", values[i])
			} else if value.Valid {
				_m.Family = new(string)
				*_m.Family = value.String
			}
		case aicatalogmodel.FieldNpm:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field npm", values[i])
			} else if value.Valid {
				_m.Npm = new(string)
				*_m.Npm = value.String
			}
		case aicatalogmodel.FieldInputModalities:
			if value, ok := values[i].(*pgvalue.Strings); !ok {
				return fmt.Errorf("unexpected type %T for field input_modalities", values[i])
			} else if value != nil {
				_m.InputModalities = *value
			}
		case aicatalogmodel.FieldOutputModalities:
			if value, ok := values[i].(*pgvalue.Strings); !ok {
				return fmt.Errorf("unexpected type %T for field output_modalities", values[i])
			} else if value != nil {
				_m.OutputModalities = *value
			}
		case aicatalogmodel.FieldContextLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field context_limit", values[i])
			} else if value.Valid {
				_m.ContextLimit = new(int)
				*_m.ContextLimit = int(value.Int64)
			}
		case aicatalogmodel.FieldOutputLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_limit", values[i])
			} else if value.Valid {
				_m.OutputLimit = new(int)
				*_m.OutputLimit = int(value.Int64)
			}
		case aicatalogmodel.FieldTemperature:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field temperature", values[i])
			} else if value.Valid {
				_m.Temperature = value.Bool
			}
		case aicatalogmodel.FieldToolCall:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field tool_call", values[i])
			} else if value.Valid {
				_m.ToolCall = value.Bool
			}
		case aicatalogmodel.FieldReasoning:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning", values[i])
			} else if value.Valid {
				_m.Reasoning = value.Bool
			}
		case aicatalogmodel.FieldStructuredOutput:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field structured_output", values[i])
			} else if value.Valid {
				_m.StructuredOutput = new(bool)
				*_m.StructuredOutput = value.Bool
			}
		case aicatalogmodel.FieldInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_price", values[i])
			} else if value.Valid {
				_m.InputPrice = new(float64)
				*_m.InputPrice = value.Float64
			}
		case aicatalogmodel.FieldOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_price", values[i])
			} else if value.Valid {
				_m.OutputPrice = new(float64)
				*_m.OutputPrice = value.Float64
			}
		case aicatalogmodel.FieldCacheReadPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_price", values[i])
			} else if value.Valid {
				_m.CacheReadPrice = new(float64)
				*_m.CacheReadPrice = value.Float64
			}
		case aicatalogmodel.FieldCacheWritePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_price", values[i])
			} else if value.Valid {
				_m.CacheWritePrice = new(float64)
				*_m.CacheWritePrice = value.Float64
			}
		case aicatalogmodel.FieldPriceTiers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field price_tiers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PriceTiers); err != nil {
					return fmt.Errorf("unmarshal field price_tiers: %w", err)
				}
			}
		case aicatalogmodel.FieldReleaseDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field release_date", values[i])
			} else if value.Valid {
				_m.ReleaseDate = new(string)
				*_m.ReleaseDate = value.String
			}
		case aicatalogmodel.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AICatalogModel.
// This includes values selected through modifiers, order, etc.
func (_m *AICatalogModel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProvider queries the "provider" edge of the AICatalogModel entity.
func (_m *AICatalogModel) QueryProvider() *AICatalogProviderQuery {
	return NewAICatalogModelClient(_m.config).QueryProvider(_m)
}

// Update returns a builder for updating this AICatalogModel.
// Note that you need to call AICatalogModel.Unwrap() before calling this method if this AICatalogModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AICatalogModel) Update() *AICatalogModelUpdateOne {
	return NewAICatalogModelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AICatalogModel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AICatalogModel) Unwrap() *AICatalogModel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AICatalogModel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AICatalogModel) String() string {
	var builder strings.Builder
	builder.WriteString("AICatalogModel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_id=")
	builder.WriteString(_m.ProviderID)
	builder.WriteString(", ")
	builder.WriteString("model_key=")
	builder.WriteString(_m.ModelKey)
	builder.WriteString(", ")
	if v := _m.CanonicalID; v != nil {
		builder.WriteString("canonical_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Type; v != nil {
		builder.WriteString("type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Family; v != nil {
		builder.WriteString("family=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Npm; v != nil {
		builder.WriteString("npm=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("input_modalities=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputModalities))
	builder.WriteString(", ")
	builder.WriteString("output_modalities=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputModalities))
	builder.WriteString(", ")
	if v := _m.ContextLimit; v != nil {
		builder.WriteString("context_limit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputLimit; v != nil {
		builder.WriteString("output_limit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("temperature=")
	builder.WriteString(fmt.Sprintf("%v", _m.Temperature))
	builder.WriteString(", ")
	builder.WriteString("tool_call=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToolCall))
	builder.WriteString(", ")
	builder.WriteString("reasoning=")
	builder.WriteString(fmt.Sprintf("%v", _m.Reasoning))
	builder.WriteString(", ")
	if v := _m.StructuredOutput; v != nil {
		builder.WriteString("structured_output=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.InputPrice; v != nil {
		builder.WriteString("input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputPrice; v != nil {
		builder.WriteString("output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheReadPrice; v != nil {
		builder.WriteString("cache_read_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CacheWritePrice; v != nil {
		builder.WriteString("cache_write_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("price_tiers=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceTiers))
	builder.WriteString(", ")
	if v := _m.ReleaseDate; v != nil {
		builder.WriteString("release_date=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(_m.SyncedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AICatalogModels is a parsable slice of AICatalogModel.
type AICatalogModels []*AICatalogModel
