// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/aiprovider"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/aiprovideroffer"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/pgvalue"
)

// AIProviderOffer is the model entity for the AIProviderOffer schema.
type AIProviderOffer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID int `json:"provider_id,omitempty"`
	// UpstreamID holds the value of the "upstream_id" field.
	UpstreamID string `json:"upstream_id,omitempty"`
	// Name holds the value of the "name" field.
	Name *string `json:"name,omitempty"`
	// Protocols holds the value of the "protocols" field.
	Protocols pgvalue.Strings `json:"protocols,omitempty"`
	// CanonicalID holds the value of the "canonical_id" field.
	CanonicalID *string `json:"canonical_id,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt time.Time `json:"synced_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AIProviderOfferQuery when eager-loading is set.
	Edges        AIProviderOfferEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AIProviderOfferEdges holds the relations/edges for other nodes in the graph.
type AIProviderOfferEdges struct {
	// Provider holds the value of the provider edge.
	Provider *AIProvider `json:"provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIProviderOfferEdges) ProviderOrErr() (*AIProvider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aiprovider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AIProviderOffer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aiprovideroffer.FieldProtocols:
			values[i] = new(pgvalue.Strings)
		case aiprovideroffer.FieldID, aiprovideroffer.FieldProviderID:
			values[i] = new(sql.NullInt64)
		case aiprovideroffer.FieldUpstreamID, aiprovideroffer.FieldName, aiprovideroffer.FieldCanonicalID:
			values[i] = new(sql.NullString)
		case aiprovideroffer.FieldSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AIProviderOffer fields.
func (_m *AIProviderOffer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aiprovideroffer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case aiprovideroffer.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = int(value.Int64)
			}
		case aiprovideroffer.FieldUpstreamID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_id", values[i])
			} else if value.Valid {
				_m.UpstreamID = value.String
			}
		case aiprovideroffer.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case aiprovideroffer.FieldProtocols:
			if value, ok := values[i].(*pgvalue.Strings); !ok {
				return fmt.Errorf("unexpected type %T for field protocols", values[i])
			} else if value != nil {
				_m.Protocols = *value
			}
		case aiprovideroffer.FieldCanonicalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field canonical_id", values[i])
			} else if value.Valid {
				_m.CanonicalID = new(string)
				*_m.CanonicalID = value.String
			}
		case aiprovideroffer.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AIProviderOffer.
// This includes values selected through modifiers, order, etc.
func (_m *AIProviderOffer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProvider queries the "provider" edge of the AIProviderOffer entity.
func (_m *AIProviderOffer) QueryProvider() *AIProviderQuery {
	return NewAIProviderOfferClient(_m.config).QueryProvider(_m)
}

// Update returns a builder for updating this AIProviderOffer.
// Note that you need to call AIProviderOffer.Unwrap() before calling this method if this AIProviderOffer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AIProviderOffer) Update() *AIProviderOfferUpdateOne {
	return NewAIProviderOfferClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AIProviderOffer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AIProviderOffer) Unwrap() *AIProviderOffer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AIProviderOffer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AIProviderOffer) String() string {
	var builder strings.Builder
	builder.WriteString("AIProviderOffer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("upstream_id=")
	builder.WriteString(_m.UpstreamID)
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("protocols=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protocols))
	builder.WriteString(", ")
	if v := _m.CanonicalID; v != nil {
		builder.WriteString("canonical_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(_m.SyncedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AIProviderOffers is a parsable slice of AIProviderOffer.
type AIProviderOffers []*AIProviderOffer
