// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/aimodel"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/aiprovider"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/airequest"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/airequestpayload"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/airoute"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/airouteadjustment"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/predicate"
)

// AIRequestQuery is the builder for querying AIRequest entities.
type AIRequestQuery struct {
	config
	ctx             *QueryContext
	order           []airequest.OrderOption
	inters          []Interceptor
	predicates      []predicate.AIRequest
	withModel       *AIModelQuery
	withRoute       *AIRouteQuery
	withProvider    *AIProviderQuery
	withPayload     *AIRequestPayloadQuery
	withAdjustments *AIRouteAdjustmentQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AIRequestQuery builder.
func (_q *AIRequestQuery) Where(ps ...predicate.AIRequest) *AIRequestQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AIRequestQuery) Limit(limit int) *AIRequestQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AIRequestQuery) Offset(offset int) *AIRequestQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AIRequestQuery) Unique(unique bool) *AIRequestQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AIRequestQuery) Order(o ...airequest.OrderOption) *AIRequestQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryModel chains the current query on the "model" edge.
func (_q *AIRequestQuery) QueryModel() *AIModelQuery {
	query := (&AIModelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(airequest.Table, airequest.FieldID, selector),
			sqlgraph.To(aimodel.Table, aimodel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, airequest.ModelTable, airequest.ModelColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoute chains the current query on the "route" edge.
func (_q *AIRequestQuery) QueryRoute() *AIRouteQuery {
	query := (&AIRouteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(airequest.Table, airequest.FieldID, selector),
			sqlgraph.To(airoute.Table, airoute.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, airequest.RouteTable, airequest.RouteColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProvider chains the current query on the "provider" edge.
func (_q *AIRequestQuery) QueryProvider() *AIProviderQuery {
	query := (&AIProviderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(airequest.Table, airequest.FieldID, selector),
			sqlgraph.To(aiprovider.Table, aiprovider.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, airequest.ProviderTable, airequest.ProviderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPayload chains the current query on the "payload" edge.
func (_q *AIRequestQuery) QueryPayload() *AIRequestPayloadQuery {
	query := (&AIRequestPayloadClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(airequest.Table, airequest.FieldID, selector),
			sqlgraph.To(airequestpayload.Table, airequestpayload.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, airequest.PayloadTable, airequest.PayloadColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAdjustments chains the current query on the "adjustments" edge.
func (_q *AIRequestQuery) QueryAdjustments() *AIRouteAdjustmentQuery {
	query := (&AIRouteAdjustmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(airequest.Table, airequest.FieldID, selector),
			sqlgraph.To(airouteadjustment.Table, airouteadjustment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, airequest.AdjustmentsTable, airequest.AdjustmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AIRequest entity from the query.
// Returns a *NotFoundError when no AIRequest was found.
func (_q *AIRequestQuery) First(ctx context.Context) (*AIRequest, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{airequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AIRequestQuery) FirstX(ctx context.Context) *AIRequest {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AIRequest ID from the query.
// Returns a *NotFoundError when no AIRequest ID was found.
func (_q *AIRequestQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{airequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AIRequestQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AIRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AIRequest entity is found.
// Returns a *NotFoundError when no AIRequest entities are found.
func (_q *AIRequestQuery) Only(ctx context.Context) (*AIRequest, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{airequest.Label}
	default:
		return nil, &NotSingularError{airequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AIRequestQuery) OnlyX(ctx context.Context) *AIRequest {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AIRequest ID in the query.
// Returns a *NotSingularError when more than one AIRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AIRequestQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{airequest.Label}
	default:
		err = &NotSingularError{airequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AIRequestQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AIRequests.
func (_q *AIRequestQuery) All(ctx context.Context) ([]*AIRequest, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AIRequest, *AIRequestQuery]()
	return withInterceptors[[]*AIRequest](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AIRequestQuery) AllX(ctx context.Context) []*AIRequest {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AIRequest IDs.
func (_q *AIRequestQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(airequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AIRequestQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AIRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AIRequestQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AIRequestQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AIRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AIRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AIRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AIRequestQuery) Clone() *AIRequestQuery {
	if _q == nil {
		return nil
	}
	return &AIRequestQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]airequest.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.AIRequest{}, _q.predicates...),
		withModel:       _q.withModel.Clone(),
		withRoute:       _q.withRoute.Clone(),
		withProvider:    _q.withProvider.Clone(),
		withPayload:     _q.withPayload.Clone(),
		withAdjustments: _q.withAdjustments.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithModel tells the query-builder to eager-load the nodes that are connected to
// the "model" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AIRequestQuery) WithModel(opts ...func(*AIModelQuery)) *AIRequestQuery {
	query := (&AIModelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withModel = query
	return _q
}

// WithRoute tells the query-builder to eager-load the nodes that are connected to
// the "route" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AIRequestQuery) WithRoute(opts ...func(*AIRouteQuery)) *AIRequestQuery {
	query := (&AIRouteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRoute = query
	return _q
}

// WithProvider tells the query-builder to eager-load the nodes that are connected to
// the "provider" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AIRequestQuery) WithProvider(opts ...func(*AIProviderQuery)) *AIRequestQuery {
	query := (&AIProviderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProvider = query
	return _q
}

// WithPayload tells the query-builder to eager-load the nodes that are connected to
// the "payload" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AIRequestQuery) WithPayload(opts ...func(*AIRequestPayloadQuery)) *AIRequestQuery {
	query := (&AIRequestPayloadClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPayload = query
	return _q
}

// WithAdjustments tells the query-builder to eager-load the nodes that are connected to
// the "adjustments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AIRequestQuery) WithAdjustments(opts ...func(*AIRouteAdjustmentQuery)) *AIRequestQuery {
	query := (&AIRouteAdjustmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAdjustments = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CallID string `json:"call_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AIRequest.Query().
//		GroupBy(airequest.FieldCallID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AIRequestQuery) GroupBy(field string, fields ...string) *AIRequestGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AIRequestGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = airequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CallID string `json:"call_id,omitempty"`
//	}
//
//	client.AIRequest.Query().
//		Select(airequest.FieldCallID).
//		Scan(ctx, &v)
func (_q *AIRequestQuery) Select(fields ...string) *AIRequestSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AIRequestSelect{AIRequestQuery: _q}
	sbuild.label = airequest.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AIRequestSelect configured with the given aggregations.
func (_q *AIRequestQuery) Aggregate(fns ...AggregateFunc) *AIRequestSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AIRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !airequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AIRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AIRequest, error) {
	var (
		nodes       = []*AIRequest{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withModel != nil,
			_q.withRoute != nil,
			_q.withProvider != nil,
			_q.withPayload != nil,
			_q.withAdjustments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AIRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AIRequest{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withModel; query != nil {
		if err := _q.loadModel(ctx, query, nodes, nil,
			func(n *AIRequest, e *AIModel) { n.Edges.Model = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRoute; query != nil {
		if err := _q.loadRoute(ctx, query, nodes, nil,
			func(n *AIRequest, e *AIRoute) { n.Edges.Route = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProvider; query != nil {
		if err := _q.loadProvider(ctx, query, nodes, nil,
			func(n *AIRequest, e *AIProvider) { n.Edges.Provider = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPayload; query != nil {
		if err := _q.loadPayload(ctx, query, nodes, nil,
			func(n *AIRequest, e *AIRequestPayload) { n.Edges.Payload = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAdjustments; query != nil {
		if err := _q.loadAdjustments(ctx, query, nodes,
			func(n *AIRequest) { n.Edges.Adjustments = []*AIRouteAdjustment{} },
			func(n *AIRequest, e *AIRouteAdjustment) { n.Edges.Adjustments = append(n.Edges.Adjustments, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AIRequestQuery) loadModel(ctx context.Context, query *AIModelQuery, nodes []*AIRequest, init func(*AIRequest), assign func(*AIRequest, *AIModel)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AIRequest)
	for i := range nodes {
		if nodes[i].ModelID == nil {
			continue
		}
		fk := *nodes[i].ModelID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(aimodel.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "model_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AIRequestQuery) loadRoute(ctx context.Context, query *AIRouteQuery, nodes []*AIRequest, init func(*AIRequest), assign func(*AIRequest, *AIRoute)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AIRequest)
	for i := range nodes {
		if nodes[i].RouteID == nil {
			continue
		}
		fk := *nodes[i].RouteID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(airoute.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "route_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AIRequestQuery) loadProvider(ctx context.Context, query *AIProviderQuery, nodes []*AIRequest, init func(*AIRequest), assign func(*AIRequest, *AIProvider)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AIRequest)
	for i := range nodes {
		if nodes[i].ProviderID == nil {
			continue
		}
		fk := *nodes[i].ProviderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(aiprovider.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "provider_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AIRequestQuery) loadPayload(ctx context.Context, query *AIRequestPayloadQuery, nodes []*AIRequest, init func(*AIRequest), assign func(*AIRequest, *AIRequestPayload)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*AIRequest)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(airequestpayload.FieldRequestID)
	}
	query.Where(predicate.AIRequestPayload(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(airequest.PayloadColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RequestID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "request_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AIRequestQuery) loadAdjustments(ctx context.Context, query *AIRouteAdjustmentQuery, nodes []*AIRequest, init func(*AIRequest), assign func(*AIRequest, *AIRouteAdjustment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*AIRequest)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(airouteadjustment.FieldRequestID)
	}
	query.Where(predicate.AIRouteAdjustment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(airequest.AdjustmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RequestID
		if fk == nil {
			return fmt.Errorf(`foreign-key "request_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "request_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AIRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AIRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(airequest.Table, airequest.Columns, sqlgraph.NewFieldSpec(airequest.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, airequest.FieldID)
		for i := range fields {
			if fields[i] != airequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withModel != nil {
			_spec.Node.AddColumnOnce(airequest.FieldModelID)
		}
		if _q.withRoute != nil {
			_spec.Node.AddColumnOnce(airequest.FieldRouteID)
		}
		if _q.withProvider != nil {
			_spec.Node.AddColumnOnce(airequest.FieldProviderID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AIRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(airequest.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = airequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *AIRequestQuery) ForUpdate(opts ...sql.LockOption) *AIRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *AIRequestQuery) ForShare(opts ...sql.LockOption) *AIRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *AIRequestQuery) Modify(modifiers ...func(s *sql.Selector)) *AIRequestSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// AIRequestGroupBy is the group-by builder for AIRequest entities.
type AIRequestGroupBy struct {
	selector
	build *AIRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AIRequestGroupBy) Aggregate(fns ...AggregateFunc) *AIRequestGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AIRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AIRequestQuery, *AIRequestGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AIRequestGroupBy) sqlScan(ctx context.Context, root *AIRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AIRequestSelect is the builder for selecting fields of AIRequest entities.
type AIRequestSelect struct {
	*AIRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AIRequestSelect) Aggregate(fns ...AggregateFunc) *AIRequestSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AIRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AIRequestQuery, *AIRequestSelect](ctx, _s.AIRequestQuery, _s, _s.inters, v)
}

func (_s *AIRequestSelect) sqlScan(ctx context.Context, root *AIRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *AIRequestSelect) Modify(modifiers ...func(s *sql.Selector)) *AIRequestSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
