// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/aimodel"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/aiprovider"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/airequest"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/airequestpayload"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/airoute"
)

// AIRequest is the model entity for the AIRequest schema.
type AIRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CallID holds the value of the "call_id" field.
	CallID string `json:"call_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Scene holds the value of the "scene" field.
	Scene *string `json:"scene,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID *int `json:"model_id,omitempty"`
	// RouteID holds the value of the "route_id" field.
	RouteID *int `json:"route_id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID *int `json:"provider_id,omitempty"`
	// UpstreamID holds the value of the "upstream_id" field.
	UpstreamID string `json:"upstream_id,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol string `json:"protocol,omitempty"`
	// Ok holds the value of the "ok" field.
	Ok bool `json:"ok,omitempty"`
	// ErrorKind holds the value of the "error_kind" field.
	ErrorKind *string `json:"error_kind,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// ErrorDetail holds the value of the "error_detail" field.
	ErrorDetail *string `json:"error_detail,omitempty"`
	// Adaptation holds the value of the "adaptation" field.
	Adaptation *string `json:"adaptation,omitempty"`
	// FinishReason holds the value of the "finish_reason" field.
	FinishReason *string `json:"finish_reason,omitempty"`
	// FirstTokenMs holds the value of the "first_token_ms" field.
	FirstTokenMs *int `json:"first_token_ms,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int `json:"duration_ms,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int `json:"output_tokens,omitempty"`
	// CacheReadTokens holds the value of the "cache_read_tokens" field.
	CacheReadTokens int `json:"cache_read_tokens,omitempty"`
	// CacheWriteTokens holds the value of the "cache_write_tokens" field.
	CacheWriteTokens int `json:"cache_write_tokens,omitempty"`
	// ReasoningTokens holds the value of the "reasoning_tokens" field.
	ReasoningTokens int `json:"reasoning_tokens,omitempty"`
	// CostUsd holds the value of the "cost_usd" field.
	CostUsd float64 `json:"cost_usd,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AIRequestQuery when eager-loading is set.
	Edges        AIRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AIRequestEdges holds the relations/edges for other nodes in the graph.
type AIRequestEdges struct {
	// Model holds the value of the model edge.
	Model *AIModel `json:"model,omitempty"`
	// Route holds the value of the route edge.
	Route *AIRoute `json:"route,omitempty"`
	// Provider holds the value of the provider edge.
	Provider *AIProvider `json:"provider,omitempty"`
	// Payload holds the value of the payload edge.
	Payload *AIRequestPayload `json:"payload,omitempty"`
	// Adjustments holds the value of the adjustments edge.
	Adjustments []*AIRouteAdjustment `json:"adjustments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// ModelOrErr returns the Model value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIRequestEdges) ModelOrErr() (*AIModel, error) {
	if e.Model != nil {
		return e.Model, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aimodel.Label}
	}
	return nil, &NotLoadedError{edge: "model"}
}

// RouteOrErr returns the Route value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIRequestEdges) RouteOrErr() (*AIRoute, error) {
	if e.Route != nil {
		return e.Route, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: airoute.Label}
	}
	return nil, &NotLoadedError{edge: "route"}
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIRequestEdges) ProviderOrErr() (*AIProvider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: aiprovider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// PayloadOrErr returns the Payload value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIRequestEdges) PayloadOrErr() (*AIRequestPayload, error) {
	if e.Payload != nil {
		return e.Payload, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: airequestpayload.Label}
	}
	return nil, &NotLoadedError{edge: "payload"}
}

// AdjustmentsOrErr returns the Adjustments value or an error if the edge
// was not loaded in eager-loading.
func (e AIRequestEdges) AdjustmentsOrErr() ([]*AIRouteAdjustment, error) {
	if e.loadedTypes[4] {
		return e.Adjustments, nil
	}
	return nil, &NotLoadedError{edge: "adjustments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AIRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case airequest.FieldOk:
			values[i] = new(sql.NullBool)
		case airequest.FieldCostUsd:
			values[i] = new(sql.NullFloat64)
		case airequest.FieldID, airequest.FieldModelID, airequest.FieldRouteID, airequest.FieldProviderID, airequest.FieldFirstTokenMs, airequest.FieldDurationMs, airequest.FieldInputTokens, airequest.FieldOutputTokens, airequest.FieldCacheReadTokens, airequest.FieldCacheWriteTokens, airequest.FieldReasoningTokens:
			values[i] = new(sql.NullInt64)
		case airequest.FieldCallID, airequest.FieldSource, airequest.FieldScene, airequest.FieldUpstreamID, airequest.FieldProtocol, airequest.FieldErrorKind, airequest.FieldErrorMessage, airequest.FieldErrorDetail, airequest.FieldAdaptation, airequest.FieldFinishReason:
			values[i] = new(sql.NullString)
		case airequest.FieldCreated:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AIRequest fields.
func (_m *AIRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case airequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case airequest.FieldCallID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field call_id", values[i])
			} else if value.Valid {
				_m.CallID = value.String
			}
		case airequest.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case airequest.FieldScene:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scene", values[i])
			} else if value.Valid {
				_m.Scene = new(string)
				*_m.Scene = value.String
			}
		case airequest.FieldModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = new(int)
				*_m.ModelID = int(value.Int64)
			}
		case airequest.FieldRouteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field route_id", values[i])
			} else if value.Valid {
				_m.RouteID = new(int)
				*_m.RouteID = int(value.Int64)
			}
		case airequest.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = new(int)
				*_m.ProviderID = int(value.Int64)
			}
		case airequest.FieldUpstreamID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_id", values[i])
			} else if value.Valid {
				_m.UpstreamID = value.String
			}
		case airequest.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case airequest.FieldOk:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field ok", values[i])
			} else if value.Valid {
				_m.Ok = value.Bool
			}
		case airequest.FieldErrorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_kind", values[i])
			} else if value.Valid {
				_m.ErrorKind = new(string)
				*_m.ErrorKind = value.String
			}
		case airequest.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case airequest.FieldErrorDetail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_detail", values[i])
			} else if value.Valid {
				_m.ErrorDetail = new(string)
				*_m.ErrorDetail = value.String
			}
		case airequest.FieldAdaptation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field adaptation", values[i])
			} else if value.Valid {
				_m.Adaptation = new(string)
				*_m.Adaptation = value.String
			}
		case airequest.FieldFinishReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field finish_reason", values[i])
			} else if value.Valid {
				_m.FinishReason = new(string)
				*_m.FinishReason = value.String
			}
		case airequest.FieldFirstTokenMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field first_token_ms", values[i])
			} else if value.Valid {
				_m.FirstTokenMs = new(int)
				*_m.FirstTokenMs = int(value.Int64)
			}
		case airequest.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = int(value.Int64)
			}
		case airequest.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = int(value.Int64)
			}
		case airequest.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = int(value.Int64)
			}
		case airequest.FieldCacheReadTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_tokens", values[i])
			} else if value.Valid {
				_m.CacheReadTokens = int(value.Int64)
			}
		case airequest.FieldCacheWriteTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_tokens", values[i])
			} else if value.Valid {
				_m.CacheWriteTokens = int(value.Int64)
			}
		case airequest.FieldReasoningTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_tokens", values[i])
			} else if value.Valid {
				_m.ReasoningTokens = int(value.Int64)
			}
		case airequest.FieldCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_usd", values[i])
			} else if value.Valid {
				_m.CostUsd = value.Float64
			}
		case airequest.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AIRequest.
// This includes values selected through modifiers, order, etc.
func (_m *AIRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModel queries the "model" edge of the AIRequest entity.
func (_m *AIRequest) QueryModel() *AIModelQuery {
	return NewAIRequestClient(_m.config).QueryModel(_m)
}

// QueryRoute queries the "route" edge of the AIRequest entity.
func (_m *AIRequest) QueryRoute() *AIRouteQuery {
	return NewAIRequestClient(_m.config).QueryRoute(_m)
}

// QueryProvider queries the "provider" edge of the AIRequest entity.
func (_m *AIRequest) QueryProvider() *AIProviderQuery {
	return NewAIRequestClient(_m.config).QueryProvider(_m)
}

// QueryPayload queries the "payload" edge of the AIRequest entity.
func (_m *AIRequest) QueryPayload() *AIRequestPayloadQuery {
	return NewAIRequestClient(_m.config).QueryPayload(_m)
}

// QueryAdjustments queries the "adjustments" edge of the AIRequest entity.
func (_m *AIRequest) QueryAdjustments() *AIRouteAdjustmentQuery {
	return NewAIRequestClient(_m.config).QueryAdjustments(_m)
}

// Update returns a builder for updating this AIRequest.
// Note that you need to call AIRequest.Unwrap() before calling this method if this AIRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AIRequest) Update() *AIRequestUpdateOne {
	return NewAIRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AIRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AIRequest) Unwrap() *AIRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AIRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AIRequest) String() string {
	var builder strings.Builder
	builder.WriteString("AIRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("call_id=")
	builder.WriteString(_m.CallID)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.Scene; v != nil {
		builder.WriteString("scene=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ModelID; v != nil {
		builder.WriteString("model_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RouteID; v != nil {
		builder.WriteString("route_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProviderID; v != nil {
		builder.WriteString("provider_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("upstream_id=")
	builder.WriteString(_m.UpstreamID)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("ok=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ok))
	builder.WriteString(", ")
	if v := _m.ErrorKind; v != nil {
		builder.WriteString("error_kind=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorDetail; v != nil {
		builder.WriteString("error_detail=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Adaptation; v != nil {
		builder.WriteString("adaptation=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FinishReason; v != nil {
		builder.WriteString("finish_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FirstTokenMs; v != nil {
		builder.WriteString("first_token_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_read_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_write_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheWriteTokens))
	builder.WriteString(", ")
	builder.WriteString("reasoning_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReasoningTokens))
	builder.WriteString(", ")
	builder.WriteString("cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostUsd))
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AIRequests is a parsable slice of AIRequest.
type AIRequests []*AIRequest
