// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/airequest"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/airoute"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/airouteadjustment"
)

// AIRouteAdjustment is the model entity for the AIRouteAdjustment schema.
type AIRouteAdjustment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RouteID holds the value of the "route_id" field.
	RouteID int `json:"route_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Previous holds the value of the "previous" field.
	Previous *string `json:"previous,omitempty"`
	// ErrorKind holds the value of the "error_kind" field.
	ErrorKind string `json:"error_kind,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *int64 `json:"request_id,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AIRouteAdjustmentQuery when eager-loading is set.
	Edges        AIRouteAdjustmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AIRouteAdjustmentEdges holds the relations/edges for other nodes in the graph.
type AIRouteAdjustmentEdges struct {
	// Route holds the value of the route edge.
	Route *AIRoute `json:"route,omitempty"`
	// Request holds the value of the request edge.
	Request *AIRequest `json:"request,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RouteOrErr returns the Route value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIRouteAdjustmentEdges) RouteOrErr() (*AIRoute, error) {
	if e.Route != nil {
		return e.Route, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: airoute.Label}
	}
	return nil, &NotLoadedError{edge: "route"}
}

// RequestOrErr returns the Request value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AIRouteAdjustmentEdges) RequestOrErr() (*AIRequest, error) {
	if e.Request != nil {
		return e.Request, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: airequest.Label}
	}
	return nil, &NotLoadedError{edge: "request"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AIRouteAdjustment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case airouteadjustment.FieldID, airouteadjustment.FieldRouteID, airouteadjustment.FieldRequestID:
			values[i] = new(sql.NullInt64)
		case airouteadjustment.FieldKind, airouteadjustment.FieldValue, airouteadjustment.FieldPrevious, airouteadjustment.FieldErrorKind:
			values[i] = new(sql.NullString)
		case airouteadjustment.FieldCreated:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AIRouteAdjustment fields.
func (_m *AIRouteAdjustment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case airouteadjustment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case airouteadjustment.FieldRouteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field route_id", values[i])
			} else if value.Valid {
				_m.RouteID = int(value.Int64)
			}
		case airouteadjustment.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case airouteadjustment.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case airouteadjustment.FieldPrevious:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field previous", values[i])
			} else if value.Valid {
				_m.Previous = new(string)
				*_m.Previous = value.String
			}
		case airouteadjustment.FieldErrorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_kind", values[i])
			} else if value.Valid {
				_m.ErrorKind = value.String
			}
		case airouteadjustment.FieldRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(int64)
				*_m.RequestID = value.Int64
			}
		case airouteadjustment.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the AIRouteAdjustment.
// This includes values selected through modifiers, order, etc.
func (_m *AIRouteAdjustment) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoute queries the "route" edge of the AIRouteAdjustment entity.
func (_m *AIRouteAdjustment) QueryRoute() *AIRouteQuery {
	return NewAIRouteAdjustmentClient(_m.config).QueryRoute(_m)
}

// QueryRequest queries the "request" edge of the AIRouteAdjustment entity.
func (_m *AIRouteAdjustment) QueryRequest() *AIRequestQuery {
	return NewAIRouteAdjustmentClient(_m.config).QueryRequest(_m)
}

// Update returns a builder for updating this AIRouteAdjustment.
// Note that you need to call AIRouteAdjustment.Unwrap() before calling this method if this AIRouteAdjustment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AIRouteAdjustment) Update() *AIRouteAdjustmentUpdateOne {
	return NewAIRouteAdjustmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AIRouteAdjustment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AIRouteAdjustment) Unwrap() *AIRouteAdjustment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AIRouteAdjustment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AIRouteAdjustment) String() string {
	var builder strings.Builder
	builder.WriteString("AIRouteAdjustment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("route_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RouteID))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteString(", ")
	if v := _m.Previous; v != nil {
		builder.WriteString("previous=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("error_kind=")
	builder.WriteString(_m.ErrorKind)
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AIRouteAdjustments is a parsable slice of AIRouteAdjustment.
type AIRouteAdjustments []*AIRouteAdjustment
