// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/catalogsourcelink"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/predicate"
)

// CatalogSourceLinkUpdate is the builder for updating CatalogSourceLink entities.
type CatalogSourceLinkUpdate struct {
	config
	hooks     []Hook
	mutation  *CatalogSourceLinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CatalogSourceLinkUpdate builder.
func (_u *CatalogSourceLinkUpdate) Where(ps ...predicate.CatalogSourceLink) *CatalogSourceLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSource sets the "source" field.
func (_u *CatalogSourceLinkUpdate) SetSource(v string) *CatalogSourceLinkUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdate) SetNillableSource(v *string) *CatalogSourceLinkUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetEntity sets the "entity" field.
func (_u *CatalogSourceLinkUpdate) SetEntity(v string) *CatalogSourceLinkUpdate {
	_u.mutation.SetEntity(v)
	return _u
}

// SetNillableEntity sets the "entity" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdate) SetNillableEntity(v *string) *CatalogSourceLinkUpdate {
	if v != nil {
		_u.SetEntity(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *CatalogSourceLinkUpdate) SetExternalID(v string) *CatalogSourceLinkUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdate) SetNillableExternalID(v *string) *CatalogSourceLinkUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetLocalID sets the "local_id" field.
func (_u *CatalogSourceLinkUpdate) SetLocalID(v int) *CatalogSourceLinkUpdate {
	_u.mutation.ResetLocalID()
	_u.mutation.SetLocalID(v)
	return _u
}

// SetNillableLocalID sets the "local_id" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdate) SetNillableLocalID(v *int) *CatalogSourceLinkUpdate {
	if v != nil {
		_u.SetLocalID(*v)
	}
	return _u
}

// AddLocalID adds value to the "local_id" field.
func (_u *CatalogSourceLinkUpdate) AddLocalID(v int) *CatalogSourceLinkUpdate {
	_u.mutation.AddLocalID(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *CatalogSourceLinkUpdate) SetRevision(v string) *CatalogSourceLinkUpdate {
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdate) SetNillableRevision(v *string) *CatalogSourceLinkUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// ClearRevision clears the value of the "revision" field.
func (_u *CatalogSourceLinkUpdate) ClearRevision() *CatalogSourceLinkUpdate {
	_u.mutation.ClearRevision()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *CatalogSourceLinkUpdate) SetSyncedAt(v time.Time) *CatalogSourceLinkUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdate) SetNillableSyncedAt(v *time.Time) *CatalogSourceLinkUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *CatalogSourceLinkUpdate) ClearSyncedAt() *CatalogSourceLinkUpdate {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetMissingAt sets the "missing_at" field.
func (_u *CatalogSourceLinkUpdate) SetMissingAt(v time.Time) *CatalogSourceLinkUpdate {
	_u.mutation.SetMissingAt(v)
	return _u
}

// SetNillableMissingAt sets the "missing_at" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdate) SetNillableMissingAt(v *time.Time) *CatalogSourceLinkUpdate {
	if v != nil {
		_u.SetMissingAt(*v)
	}
	return _u
}

// ClearMissingAt clears the value of the "missing_at" field.
func (_u *CatalogSourceLinkUpdate) ClearMissingAt() *CatalogSourceLinkUpdate {
	_u.mutation.ClearMissingAt()
	return _u
}

// SetFailures sets the "failures" field.
func (_u *CatalogSourceLinkUpdate) SetFailures(v int) *CatalogSourceLinkUpdate {
	_u.mutation.ResetFailures()
	_u.mutation.SetFailures(v)
	return _u
}

// SetNillableFailures sets the "failures" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdate) SetNillableFailures(v *int) *CatalogSourceLinkUpdate {
	if v != nil {
		_u.SetFailures(*v)
	}
	return _u
}

// AddFailures adds value to the "failures" field.
func (_u *CatalogSourceLinkUpdate) AddFailures(v int) *CatalogSourceLinkUpdate {
	_u.mutation.AddFailures(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CatalogSourceLinkUpdate) SetLastError(v string) *CatalogSourceLinkUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdate) SetNillableLastError(v *string) *CatalogSourceLinkUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CatalogSourceLinkUpdate) ClearLastError() *CatalogSourceLinkUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *CatalogSourceLinkUpdate) SetUpdated(v time.Time) *CatalogSourceLinkUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// Mutation returns the CatalogSourceLinkMutation object of the builder.
func (_u *CatalogSourceLinkUpdate) Mutation() *CatalogSourceLinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CatalogSourceLinkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CatalogSourceLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CatalogSourceLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CatalogSourceLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CatalogSourceLinkUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := catalogsourcelink.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CatalogSourceLinkUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := catalogsourcelink.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "CatalogSourceLink.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Entity(); ok {
		if err := catalogsourcelink.EntityValidator(v); err != nil {
			return &ValidationError{Name: "entity", err: fmt.Errorf(`ent: validator failed for field "CatalogSourceLink.entity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := catalogsourcelink.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "CatalogSourceLink.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := catalogsourcelink.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "CatalogSourceLink.revision": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastError(); ok {
		if err := catalogsourcelink.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "CatalogSourceLink.last_error": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CatalogSourceLinkUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CatalogSourceLinkUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CatalogSourceLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(catalogsourcelink.Table, catalogsourcelink.Columns, sqlgraph.NewFieldSpec(catalogsourcelink.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(catalogsourcelink.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Entity(); ok {
		_spec.SetField(catalogsourcelink.FieldEntity, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(catalogsourcelink.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalID(); ok {
		_spec.SetField(catalogsourcelink.FieldLocalID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLocalID(); ok {
		_spec.AddField(catalogsourcelink.FieldLocalID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(catalogsourcelink.FieldRevision, field.TypeString, value)
	}
	if _u.mutation.RevisionCleared() {
		_spec.ClearField(catalogsourcelink.FieldRevision, field.TypeString)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(catalogsourcelink.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(catalogsourcelink.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MissingAt(); ok {
		_spec.SetField(catalogsourcelink.FieldMissingAt, field.TypeTime, value)
	}
	if _u.mutation.MissingAtCleared() {
		_spec.ClearField(catalogsourcelink.FieldMissingAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Failures(); ok {
		_spec.SetField(catalogsourcelink.FieldFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailures(); ok {
		_spec.AddField(catalogsourcelink.FieldFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(catalogsourcelink.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(catalogsourcelink.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(catalogsourcelink.FieldUpdated, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{catalogsourcelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CatalogSourceLinkUpdateOne is the builder for updating a single CatalogSourceLink entity.
type CatalogSourceLinkUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CatalogSourceLinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetSource sets the "source" field.
func (_u *CatalogSourceLinkUpdateOne) SetSource(v string) *CatalogSourceLinkUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdateOne) SetNillableSource(v *string) *CatalogSourceLinkUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetEntity sets the "entity" field.
func (_u *CatalogSourceLinkUpdateOne) SetEntity(v string) *CatalogSourceLinkUpdateOne {
	_u.mutation.SetEntity(v)
	return _u
}

// SetNillableEntity sets the "entity" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdateOne) SetNillableEntity(v *string) *CatalogSourceLinkUpdateOne {
	if v != nil {
		_u.SetEntity(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *CatalogSourceLinkUpdateOne) SetExternalID(v string) *CatalogSourceLinkUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdateOne) SetNillableExternalID(v *string) *CatalogSourceLinkUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetLocalID sets the "local_id" field.
func (_u *CatalogSourceLinkUpdateOne) SetLocalID(v int) *CatalogSourceLinkUpdateOne {
	_u.mutation.ResetLocalID()
	_u.mutation.SetLocalID(v)
	return _u
}

// SetNillableLocalID sets the "local_id" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdateOne) SetNillableLocalID(v *int) *CatalogSourceLinkUpdateOne {
	if v != nil {
		_u.SetLocalID(*v)
	}
	return _u
}

// AddLocalID adds value to the "local_id" field.
func (_u *CatalogSourceLinkUpdateOne) AddLocalID(v int) *CatalogSourceLinkUpdateOne {
	_u.mutation.AddLocalID(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *CatalogSourceLinkUpdateOne) SetRevision(v string) *CatalogSourceLinkUpdateOne {
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdateOne) SetNillableRevision(v *string) *CatalogSourceLinkUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// ClearRevision clears the value of the "revision" field.
func (_u *CatalogSourceLinkUpdateOne) ClearRevision() *CatalogSourceLinkUpdateOne {
	_u.mutation.ClearRevision()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *CatalogSourceLinkUpdateOne) SetSyncedAt(v time.Time) *CatalogSourceLinkUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdateOne) SetNillableSyncedAt(v *time.Time) *CatalogSourceLinkUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *CatalogSourceLinkUpdateOne) ClearSyncedAt() *CatalogSourceLinkUpdateOne {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetMissingAt sets the "missing_at" field.
func (_u *CatalogSourceLinkUpdateOne) SetMissingAt(v time.Time) *CatalogSourceLinkUpdateOne {
	_u.mutation.SetMissingAt(v)
	return _u
}

// SetNillableMissingAt sets the "missing_at" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdateOne) SetNillableMissingAt(v *time.Time) *CatalogSourceLinkUpdateOne {
	if v != nil {
		_u.SetMissingAt(*v)
	}
	return _u
}

// ClearMissingAt clears the value of the "missing_at" field.
func (_u *CatalogSourceLinkUpdateOne) ClearMissingAt() *CatalogSourceLinkUpdateOne {
	_u.mutation.ClearMissingAt()
	return _u
}

// SetFailures sets the "failures" field.
func (_u *CatalogSourceLinkUpdateOne) SetFailures(v int) *CatalogSourceLinkUpdateOne {
	_u.mutation.ResetFailures()
	_u.mutation.SetFailures(v)
	return _u
}

// SetNillableFailures sets the "failures" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdateOne) SetNillableFailures(v *int) *CatalogSourceLinkUpdateOne {
	if v != nil {
		_u.SetFailures(*v)
	}
	return _u
}

// AddFailures adds value to the "failures" field.
func (_u *CatalogSourceLinkUpdateOne) AddFailures(v int) *CatalogSourceLinkUpdateOne {
	_u.mutation.AddFailures(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CatalogSourceLinkUpdateOne) SetLastError(v string) *CatalogSourceLinkUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CatalogSourceLinkUpdateOne) SetNillableLastError(v *string) *CatalogSourceLinkUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CatalogSourceLinkUpdateOne) ClearLastError() *CatalogSourceLinkUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *CatalogSourceLinkUpdateOne) SetUpdated(v time.Time) *CatalogSourceLinkUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// Mutation returns the CatalogSourceLinkMutation object of the builder.
func (_u *CatalogSourceLinkUpdateOne) Mutation() *CatalogSourceLinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the CatalogSourceLinkUpdate builder.
func (_u *CatalogSourceLinkUpdateOne) Where(ps ...predicate.CatalogSourceLink) *CatalogSourceLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CatalogSourceLinkUpdateOne) Select(field string, fields ...string) *CatalogSourceLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CatalogSourceLink entity.
func (_u *CatalogSourceLinkUpdateOne) Save(ctx context.Context) (*CatalogSourceLink, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CatalogSourceLinkUpdateOne) SaveX(ctx context.Context) *CatalogSourceLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CatalogSourceLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CatalogSourceLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CatalogSourceLinkUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := catalogsourcelink.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CatalogSourceLinkUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := catalogsourcelink.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "CatalogSourceLink.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Entity(); ok {
		if err := catalogsourcelink.EntityValidator(v); err != nil {
			return &ValidationError{Name: "entity", err: fmt.Errorf(`ent: validator failed for field "CatalogSourceLink.entity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := catalogsourcelink.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "CatalogSourceLink.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := catalogsourcelink.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "CatalogSourceLink.revision": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastError(); ok {
		if err := catalogsourcelink.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "CatalogSourceLink.last_error": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CatalogSourceLinkUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CatalogSourceLinkUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CatalogSourceLinkUpdateOne) sqlSave(ctx context.Context) (_node *CatalogSourceLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(catalogsourcelink.Table, catalogsourcelink.Columns, sqlgraph.NewFieldSpec(catalogsourcelink.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CatalogSourceLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, catalogsourcelink.FieldID)
		for _, f := range fields {
			if !catalogsourcelink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != catalogsourcelink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(catalogsourcelink.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Entity(); ok {
		_spec.SetField(catalogsourcelink.FieldEntity, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(catalogsourcelink.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalID(); ok {
		_spec.SetField(catalogsourcelink.FieldLocalID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLocalID(); ok {
		_spec.AddField(catalogsourcelink.FieldLocalID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(catalogsourcelink.FieldRevision, field.TypeString, value)
	}
	if _u.mutation.RevisionCleared() {
		_spec.ClearField(catalogsourcelink.FieldRevision, field.TypeString)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(catalogsourcelink.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(catalogsourcelink.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MissingAt(); ok {
		_spec.SetField(catalogsourcelink.FieldMissingAt, field.TypeTime, value)
	}
	if _u.mutation.MissingAtCleared() {
		_spec.ClearField(catalogsourcelink.FieldMissingAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Failures(); ok {
		_spec.SetField(catalogsourcelink.FieldFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailures(); ok {
		_spec.AddField(catalogsourcelink.FieldFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(catalogsourcelink.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(catalogsourcelink.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(catalogsourcelink.FieldUpdated, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CatalogSourceLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{catalogsourcelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
