// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/game"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamecharacter"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamecharacterrelation"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/predicate"
)

// GameCharacterRelationUpdate is the builder for updating GameCharacterRelation entities.
type GameCharacterRelationUpdate struct {
	config
	hooks     []Hook
	mutation  *GameCharacterRelationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the GameCharacterRelationUpdate builder.
func (_u *GameCharacterRelationUpdate) Where(ps ...predicate.GameCharacterRelation) *GameCharacterRelationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetImage sets the "image" field.
func (_u *GameCharacterRelationUpdate) SetImage(v string) *GameCharacterRelationUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *GameCharacterRelationUpdate) SetNillableImage(v *string) *GameCharacterRelationUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *GameCharacterRelationUpdate) ClearImage() *GameCharacterRelationUpdate {
	_u.mutation.ClearImage()
	return _u
}

// SetActor sets the "actor" field.
func (_u *GameCharacterRelationUpdate) SetActor(v string) *GameCharacterRelationUpdate {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *GameCharacterRelationUpdate) SetNillableActor(v *string) *GameCharacterRelationUpdate {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// ClearActor clears the value of the "actor" field.
func (_u *GameCharacterRelationUpdate) ClearActor() *GameCharacterRelationUpdate {
	_u.mutation.ClearActor()
	return _u
}

// SetRole sets the "role" field.
func (_u *GameCharacterRelationUpdate) SetRole(v gamecharacterrelation.Role) *GameCharacterRelationUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *GameCharacterRelationUpdate) SetNillableRole(v *gamecharacterrelation.Role) *GameCharacterRelationUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// ClearRole clears the value of the "role" field.
func (_u *GameCharacterRelationUpdate) ClearRole() *GameCharacterRelationUpdate {
	_u.mutation.ClearRole()
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *GameCharacterRelationUpdate) SetGameID(v int) *GameCharacterRelationUpdate {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *GameCharacterRelationUpdate) SetNillableGameID(v *int) *GameCharacterRelationUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *GameCharacterRelationUpdate) SetCharacterID(v int) *GameCharacterRelationUpdate {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *GameCharacterRelationUpdate) SetNillableCharacterID(v *int) *GameCharacterRelationUpdate {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *GameCharacterRelationUpdate) SetUpdated(v time.Time) *GameCharacterRelationUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetCharacter sets the "character" edge to the GameCharacter entity.
func (_u *GameCharacterRelationUpdate) SetCharacter(v *GameCharacter) *GameCharacterRelationUpdate {
	return _u.SetCharacterID(v.ID)
}

// SetGame sets the "game" edge to the Game entity.
func (_u *GameCharacterRelationUpdate) SetGame(v *Game) *GameCharacterRelationUpdate {
	return _u.SetGameID(v.ID)
}

// Mutation returns the GameCharacterRelationMutation object of the builder.
func (_u *GameCharacterRelationUpdate) Mutation() *GameCharacterRelationMutation {
	return _u.mutation
}

// ClearCharacter clears the "character" edge to the GameCharacter entity.
func (_u *GameCharacterRelationUpdate) ClearCharacter() *GameCharacterRelationUpdate {
	_u.mutation.ClearCharacter()
	return _u
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *GameCharacterRelationUpdate) ClearGame() *GameCharacterRelationUpdate {
	_u.mutation.ClearGame()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameCharacterRelationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameCharacterRelationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameCharacterRelationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameCharacterRelationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameCharacterRelationUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := gamecharacterrelation.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameCharacterRelationUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := gamecharacterrelation.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "GameCharacterRelation.role": %w`, err)}
		}
	}
	if _u.mutation.CharacterCleared() && len(_u.mutation.CharacterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GameCharacterRelation.character"`)
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GameCharacterRelation.game"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GameCharacterRelationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GameCharacterRelationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GameCharacterRelationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gamecharacterrelation.Table, gamecharacterrelation.Columns, sqlgraph.NewFieldSpec(gamecharacterrelation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(gamecharacterrelation.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(gamecharacterrelation.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(gamecharacterrelation.FieldActor, field.TypeString, value)
	}
	if _u.mutation.ActorCleared() {
		_spec.ClearField(gamecharacterrelation.FieldActor, field.TypeString)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(gamecharacterrelation.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.RoleCleared() {
		_spec.ClearField(gamecharacterrelation.FieldRole, field.TypeEnum)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(gamecharacterrelation.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.CharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gamecharacterrelation.CharacterTable,
			Columns: []string{gamecharacterrelation.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamecharacter.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gamecharacterrelation.CharacterTable,
			Columns: []string{gamecharacterrelation.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamecharacter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gamecharacterrelation.GameTable,
			Columns: []string{gamecharacterrelation.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gamecharacterrelation.GameTable,
			Columns: []string{gamecharacterrelation.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gamecharacterrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameCharacterRelationUpdateOne is the builder for updating a single GameCharacterRelation entity.
type GameCharacterRelationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *GameCharacterRelationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetImage sets the "image" field.
func (_u *GameCharacterRelationUpdateOne) SetImage(v string) *GameCharacterRelationUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *GameCharacterRelationUpdateOne) SetNillableImage(v *string) *GameCharacterRelationUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *GameCharacterRelationUpdateOne) ClearImage() *GameCharacterRelationUpdateOne {
	_u.mutation.ClearImage()
	return _u
}

// SetActor sets the "actor" field.
func (_u *GameCharacterRelationUpdateOne) SetActor(v string) *GameCharacterRelationUpdateOne {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *GameCharacterRelationUpdateOne) SetNillableActor(v *string) *GameCharacterRelationUpdateOne {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// ClearActor clears the value of the "actor" field.
func (_u *GameCharacterRelationUpdateOne) ClearActor() *GameCharacterRelationUpdateOne {
	_u.mutation.ClearActor()
	return _u
}

// SetRole sets the "role" field.
func (_u *GameCharacterRelationUpdateOne) SetRole(v gamecharacterrelation.Role) *GameCharacterRelationUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *GameCharacterRelationUpdateOne) SetNillableRole(v *gamecharacterrelation.Role) *GameCharacterRelationUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// ClearRole clears the value of the "role" field.
func (_u *GameCharacterRelationUpdateOne) ClearRole() *GameCharacterRelationUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *GameCharacterRelationUpdateOne) SetGameID(v int) *GameCharacterRelationUpdateOne {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *GameCharacterRelationUpdateOne) SetNillableGameID(v *int) *GameCharacterRelationUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *GameCharacterRelationUpdateOne) SetCharacterID(v int) *GameCharacterRelationUpdateOne {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *GameCharacterRelationUpdateOne) SetNillableCharacterID(v *int) *GameCharacterRelationUpdateOne {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *GameCharacterRelationUpdateOne) SetUpdated(v time.Time) *GameCharacterRelationUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetCharacter sets the "character" edge to the GameCharacter entity.
func (_u *GameCharacterRelationUpdateOne) SetCharacter(v *GameCharacter) *GameCharacterRelationUpdateOne {
	return _u.SetCharacterID(v.ID)
}

// SetGame sets the "game" edge to the Game entity.
func (_u *GameCharacterRelationUpdateOne) SetGame(v *Game) *GameCharacterRelationUpdateOne {
	return _u.SetGameID(v.ID)
}

// Mutation returns the GameCharacterRelationMutation object of the builder.
func (_u *GameCharacterRelationUpdateOne) Mutation() *GameCharacterRelationMutation {
	return _u.mutation
}

// ClearCharacter clears the "character" edge to the GameCharacter entity.
func (_u *GameCharacterRelationUpdateOne) ClearCharacter() *GameCharacterRelationUpdateOne {
	_u.mutation.ClearCharacter()
	return _u
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *GameCharacterRelationUpdateOne) ClearGame() *GameCharacterRelationUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// Where appends a list predicates to the GameCharacterRelationUpdate builder.
func (_u *GameCharacterRelationUpdateOne) Where(ps ...predicate.GameCharacterRelation) *GameCharacterRelationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameCharacterRelationUpdateOne) Select(field string, fields ...string) *GameCharacterRelationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GameCharacterRelation entity.
func (_u *GameCharacterRelationUpdateOne) Save(ctx context.Context) (*GameCharacterRelation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameCharacterRelationUpdateOne) SaveX(ctx context.Context) *GameCharacterRelation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameCharacterRelationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameCharacterRelationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameCharacterRelationUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := gamecharacterrelation.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameCharacterRelationUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := gamecharacterrelation.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "GameCharacterRelation.role": %w`, err)}
		}
	}
	if _u.mutation.CharacterCleared() && len(_u.mutation.CharacterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GameCharacterRelation.character"`)
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GameCharacterRelation.game"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GameCharacterRelationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GameCharacterRelationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GameCharacterRelationUpdateOne) sqlSave(ctx context.Context) (_node *GameCharacterRelation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gamecharacterrelation.Table, gamecharacterrelation.Columns, sqlgraph.NewFieldSpec(gamecharacterrelation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GameCharacterRelation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gamecharacterrelation.FieldID)
		for _, f := range fields {
			if !gamecharacterrelation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gamecharacterrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(gamecharacterrelation.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(gamecharacterrelation.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(gamecharacterrelation.FieldActor, field.TypeString, value)
	}
	if _u.mutation.ActorCleared() {
		_spec.ClearField(gamecharacterrelation.FieldActor, field.TypeString)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(gamecharacterrelation.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.RoleCleared() {
		_spec.ClearField(gamecharacterrelation.FieldRole, field.TypeEnum)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(gamecharacterrelation.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.CharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gamecharacterrelation.CharacterTable,
			Columns: []string{gamecharacterrelation.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamecharacter.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gamecharacterrelation.CharacterTable,
			Columns: []string{gamecharacterrelation.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamecharacter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gamecharacterrelation.GameTable,
			Columns: []string{gamecharacterrelation.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gamecharacterrelation.GameTable,
			Columns: []string{gamecharacterrelation.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &GameCharacterRelation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gamecharacterrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
