// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/game"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamedeveloper"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamedeveloperrelation"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/predicate"
)

// GameDeveloperRelationQuery is the builder for querying GameDeveloperRelation entities.
type GameDeveloperRelationQuery struct {
	config
	ctx           *QueryContext
	order         []gamedeveloperrelation.OrderOption
	inters        []Interceptor
	predicates    []predicate.GameDeveloperRelation
	withDeveloper *GameDeveloperQuery
	withGame      *GameQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GameDeveloperRelationQuery builder.
func (_q *GameDeveloperRelationQuery) Where(ps ...predicate.GameDeveloperRelation) *GameDeveloperRelationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GameDeveloperRelationQuery) Limit(limit int) *GameDeveloperRelationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GameDeveloperRelationQuery) Offset(offset int) *GameDeveloperRelationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GameDeveloperRelationQuery) Unique(unique bool) *GameDeveloperRelationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GameDeveloperRelationQuery) Order(o ...gamedeveloperrelation.OrderOption) *GameDeveloperRelationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDeveloper chains the current query on the "developer" edge.
func (_q *GameDeveloperRelationQuery) QueryDeveloper() *GameDeveloperQuery {
	query := (&GameDeveloperClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gamedeveloperrelation.Table, gamedeveloperrelation.FieldID, selector),
			sqlgraph.To(gamedeveloper.Table, gamedeveloper.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, gamedeveloperrelation.DeveloperTable, gamedeveloperrelation.DeveloperColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGame chains the current query on the "game" edge.
func (_q *GameDeveloperRelationQuery) QueryGame() *GameQuery {
	query := (&GameClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gamedeveloperrelation.Table, gamedeveloperrelation.FieldID, selector),
			sqlgraph.To(game.Table, game.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, gamedeveloperrelation.GameTable, gamedeveloperrelation.GameColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GameDeveloperRelation entity from the query.
// Returns a *NotFoundError when no GameDeveloperRelation was found.
func (_q *GameDeveloperRelationQuery) First(ctx context.Context) (*GameDeveloperRelation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{gamedeveloperrelation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GameDeveloperRelationQuery) FirstX(ctx context.Context) *GameDeveloperRelation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GameDeveloperRelation ID from the query.
// Returns a *NotFoundError when no GameDeveloperRelation ID was found.
func (_q *GameDeveloperRelationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{gamedeveloperrelation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GameDeveloperRelationQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GameDeveloperRelation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GameDeveloperRelation entity is found.
// Returns a *NotFoundError when no GameDeveloperRelation entities are found.
func (_q *GameDeveloperRelationQuery) Only(ctx context.Context) (*GameDeveloperRelation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{gamedeveloperrelation.Label}
	default:
		return nil, &NotSingularError{gamedeveloperrelation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GameDeveloperRelationQuery) OnlyX(ctx context.Context) *GameDeveloperRelation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GameDeveloperRelation ID in the query.
// Returns a *NotSingularError when more than one GameDeveloperRelation ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GameDeveloperRelationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{gamedeveloperrelation.Label}
	default:
		err = &NotSingularError{gamedeveloperrelation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GameDeveloperRelationQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GameDeveloperRelations.
func (_q *GameDeveloperRelationQuery) All(ctx context.Context) ([]*GameDeveloperRelation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GameDeveloperRelation, *GameDeveloperRelationQuery]()
	return withInterceptors[[]*GameDeveloperRelation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GameDeveloperRelationQuery) AllX(ctx context.Context) []*GameDeveloperRelation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GameDeveloperRelation IDs.
func (_q *GameDeveloperRelationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(gamedeveloperrelation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GameDeveloperRelationQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GameDeveloperRelationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GameDeveloperRelationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GameDeveloperRelationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GameDeveloperRelationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GameDeveloperRelationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GameDeveloperRelationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GameDeveloperRelationQuery) Clone() *GameDeveloperRelationQuery {
	if _q == nil {
		return nil
	}
	return &GameDeveloperRelationQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]gamedeveloperrelation.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.GameDeveloperRelation{}, _q.predicates...),
		withDeveloper: _q.withDeveloper.Clone(),
		withGame:      _q.withGame.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithDeveloper tells the query-builder to eager-load the nodes that are connected to
// the "developer" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GameDeveloperRelationQuery) WithDeveloper(opts ...func(*GameDeveloperQuery)) *GameDeveloperRelationQuery {
	query := (&GameDeveloperClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDeveloper = query
	return _q
}

// WithGame tells the query-builder to eager-load the nodes that are connected to
// the "game" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GameDeveloperRelationQuery) WithGame(opts ...func(*GameQuery)) *GameDeveloperRelationQuery {
	query := (&GameClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGame = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Role string `json:"role,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GameDeveloperRelation.Query().
//		GroupBy(gamedeveloperrelation.FieldRole).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GameDeveloperRelationQuery) GroupBy(field string, fields ...string) *GameDeveloperRelationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GameDeveloperRelationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = gamedeveloperrelation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Role string `json:"role,omitempty"`
//	}
//
//	client.GameDeveloperRelation.Query().
//		Select(gamedeveloperrelation.FieldRole).
//		Scan(ctx, &v)
func (_q *GameDeveloperRelationQuery) Select(fields ...string) *GameDeveloperRelationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GameDeveloperRelationSelect{GameDeveloperRelationQuery: _q}
	sbuild.label = gamedeveloperrelation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GameDeveloperRelationSelect configured with the given aggregations.
func (_q *GameDeveloperRelationQuery) Aggregate(fns ...AggregateFunc) *GameDeveloperRelationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GameDeveloperRelationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !gamedeveloperrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GameDeveloperRelationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GameDeveloperRelation, error) {
	var (
		nodes       = []*GameDeveloperRelation{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withDeveloper != nil,
			_q.withGame != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GameDeveloperRelation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GameDeveloperRelation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDeveloper; query != nil {
		if err := _q.loadDeveloper(ctx, query, nodes, nil,
			func(n *GameDeveloperRelation, e *GameDeveloper) { n.Edges.Developer = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGame; query != nil {
		if err := _q.loadGame(ctx, query, nodes, nil,
			func(n *GameDeveloperRelation, e *Game) { n.Edges.Game = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GameDeveloperRelationQuery) loadDeveloper(ctx context.Context, query *GameDeveloperQuery, nodes []*GameDeveloperRelation, init func(*GameDeveloperRelation), assign func(*GameDeveloperRelation, *GameDeveloper)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GameDeveloperRelation)
	for i := range nodes {
		fk := nodes[i].DeveloperID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(gamedeveloper.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "developer_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GameDeveloperRelationQuery) loadGame(ctx context.Context, query *GameQuery, nodes []*GameDeveloperRelation, init func(*GameDeveloperRelation), assign func(*GameDeveloperRelation, *Game)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GameDeveloperRelation)
	for i := range nodes {
		fk := nodes[i].GameID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(game.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "game_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *GameDeveloperRelationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GameDeveloperRelationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(gamedeveloperrelation.Table, gamedeveloperrelation.Columns, sqlgraph.NewFieldSpec(gamedeveloperrelation.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gamedeveloperrelation.FieldID)
		for i := range fields {
			if fields[i] != gamedeveloperrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withDeveloper != nil {
			_spec.Node.AddColumnOnce(gamedeveloperrelation.FieldDeveloperID)
		}
		if _q.withGame != nil {
			_spec.Node.AddColumnOnce(gamedeveloperrelation.FieldGameID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GameDeveloperRelationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(gamedeveloperrelation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = gamedeveloperrelation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *GameDeveloperRelationQuery) ForUpdate(opts ...sql.LockOption) *GameDeveloperRelationQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *GameDeveloperRelationQuery) ForShare(opts ...sql.LockOption) *GameDeveloperRelationQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *GameDeveloperRelationQuery) Modify(modifiers ...func(s *sql.Selector)) *GameDeveloperRelationSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// GameDeveloperRelationGroupBy is the group-by builder for GameDeveloperRelation entities.
type GameDeveloperRelationGroupBy struct {
	selector
	build *GameDeveloperRelationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GameDeveloperRelationGroupBy) Aggregate(fns ...AggregateFunc) *GameDeveloperRelationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GameDeveloperRelationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GameDeveloperRelationQuery, *GameDeveloperRelationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GameDeveloperRelationGroupBy) sqlScan(ctx context.Context, root *GameDeveloperRelationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GameDeveloperRelationSelect is the builder for selecting fields of GameDeveloperRelation entities.
type GameDeveloperRelationSelect struct {
	*GameDeveloperRelationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GameDeveloperRelationSelect) Aggregate(fns ...AggregateFunc) *GameDeveloperRelationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GameDeveloperRelationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GameDeveloperRelationQuery, *GameDeveloperRelationSelect](ctx, _s.GameDeveloperRelationQuery, _s, _s.inters, v)
}

func (_s *GameDeveloperRelationSelect) sqlScan(ctx context.Context, root *GameDeveloperRelationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *GameDeveloperRelationSelect) Modify(modifiers ...func(s *sql.Selector)) *GameDeveloperRelationSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
