// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/activity"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/ad"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/comment"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/editrecord"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/favorite"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/favoriteitem"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/fieldpermissionmapping"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/game"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamecharacter"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamecharacterrelation"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamecover"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamedeveloper"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamedeveloperrelation"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamedownloadresource"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamedownloadresourcefile"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamedownloadresourcefilehistory"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamedownloadresourcereport"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gameimage"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamelink"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gamerelation"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gameuploadchunk"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gameuploadsession"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/malwarescancase"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/message"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/moderationevent"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/oidcidentity"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/rolefieldpermission"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/schema"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/sponsororder"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/tag"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/user"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/userbannedrecord"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/userfieldpermission"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/usergamepvnmapping"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/userloginsession"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/userpasskeycredential"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/userpvnbinding"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/useruploadquota"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/useruploadquotarecord"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/walkthrough"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	activityFields := schema.Activity{}.Fields()
	_ = activityFields
	// activityDescFileStatus is the schema descriptor for file_status field.
	activityDescFileStatus := activityFields[10].Descriptor()
	// activity.DefaultFileStatus holds the default value on creation for the file_status field.
	activity.DefaultFileStatus = activityDescFileStatus.Default.(int)
	// activityDescFileCheckStatus is the schema descriptor for file_check_status field.
	activityDescFileCheckStatus := activityFields[11].Descriptor()
	// activity.DefaultFileCheckStatus holds the default value on creation for the file_check_status field.
	activity.DefaultFileCheckStatus = activityDescFileCheckStatus.Default.(int)
	// activityDescCreated is the schema descriptor for created field.
	activityDescCreated := activityFields[14].Descriptor()
	// activity.DefaultCreated holds the default value on creation for the created field.
	activity.DefaultCreated = activityDescCreated.Default.(func() time.Time)
	// activityDescUpdated is the schema descriptor for updated field.
	activityDescUpdated := activityFields[15].Descriptor()
	// activity.DefaultUpdated holds the default value on creation for the updated field.
	activity.DefaultUpdated = activityDescUpdated.Default.(func() time.Time)
	// activity.UpdateDefaultUpdated holds the default value on update for the updated field.
	activity.UpdateDefaultUpdated = activityDescUpdated.UpdateDefault.(func() time.Time)
	adFields := schema.Ad{}.Fields()
	_ = adFields
	// adDescName is the schema descriptor for name field.
	adDescName := adFields[1].Descriptor()
	// ad.NameValidator is a validator for the "name" field. It is called by the builders before save.
	ad.NameValidator = adDescName.Validators[0].(func(string) error)
	// adDescImageZh is the schema descriptor for image_zh field.
	adDescImageZh := adFields[3].Descriptor()
	// ad.ImageZhValidator is a validator for the "image_zh" field. It is called by the builders before save.
	ad.ImageZhValidator = adDescImageZh.Validators[0].(func(string) error)
	// adDescImageJa is the schema descriptor for image_ja field.
	adDescImageJa := adFields[4].Descriptor()
	// ad.ImageJaValidator is a validator for the "image_ja" field. It is called by the builders before save.
	ad.ImageJaValidator = adDescImageJa.Validators[0].(func(string) error)
	// adDescImageEn is the schema descriptor for image_en field.
	adDescImageEn := adFields[5].Descriptor()
	// ad.ImageEnValidator is a validator for the "image_en" field. It is called by the builders before save.
	ad.ImageEnValidator = adDescImageEn.Validators[0].(func(string) error)
	// adDescAspect is the schema descriptor for aspect field.
	adDescAspect := adFields[6].Descriptor()
	// ad.AspectValidator is a validator for the "aspect" field. It is called by the builders before save.
	ad.AspectValidator = adDescAspect.Validators[0].(func(string) error)
	// adDescLink is the schema descriptor for link field.
	adDescLink := adFields[7].Descriptor()
	// ad.LinkValidator is a validator for the "link" field. It is called by the builders before save.
	ad.LinkValidator = adDescLink.Validators[0].(func(string) error)
	// adDescEnabled is the schema descriptor for enabled field.
	adDescEnabled := adFields[9].Descriptor()
	// ad.DefaultEnabled holds the default value on creation for the enabled field.
	ad.DefaultEnabled = adDescEnabled.Default.(bool)
	// adDescSort is the schema descriptor for sort field.
	adDescSort := adFields[10].Descriptor()
	// ad.DefaultSort holds the default value on creation for the sort field.
	ad.DefaultSort = adDescSort.Default.(int)
	// adDescCreated is the schema descriptor for created field.
	adDescCreated := adFields[13].Descriptor()
	// ad.DefaultCreated holds the default value on creation for the created field.
	ad.DefaultCreated = adDescCreated.Default.(func() time.Time)
	// adDescUpdated is the schema descriptor for updated field.
	adDescUpdated := adFields[14].Descriptor()
	// ad.DefaultUpdated holds the default value on creation for the updated field.
	ad.DefaultUpdated = adDescUpdated.Default.(func() time.Time)
	// ad.UpdateDefaultUpdated holds the default value on update for the updated field.
	ad.UpdateDefaultUpdated = adDescUpdated.UpdateDefault.(func() time.Time)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescHTML is the schema descriptor for html field.
	commentDescHTML := commentFields[2].Descriptor()
	// comment.HTMLValidator is a validator for the "html" field. It is called by the builders before save.
	comment.HTMLValidator = commentDescHTML.Validators[0].(func(string) error)
	// commentDescReplyCount is the schema descriptor for reply_count field.
	commentDescReplyCount := commentFields[6].Descriptor()
	// comment.DefaultReplyCount holds the default value on creation for the reply_count field.
	comment.DefaultReplyCount = commentDescReplyCount.Default.(int)
	// commentDescStatus is the schema descriptor for status field.
	commentDescStatus := commentFields[8].Descriptor()
	// comment.DefaultStatus holds the default value on creation for the status field.
	comment.DefaultStatus = commentDescStatus.Default.(int)
	// commentDescEdited is the schema descriptor for edited field.
	commentDescEdited := commentFields[9].Descriptor()
	// comment.DefaultEdited holds the default value on creation for the edited field.
	comment.DefaultEdited = commentDescEdited.Default.(bool)
	// commentDescCreated is the schema descriptor for created field.
	commentDescCreated := commentFields[10].Descriptor()
	// comment.DefaultCreated holds the default value on creation for the created field.
	comment.DefaultCreated = commentDescCreated.Default.(func() time.Time)
	// commentDescUpdated is the schema descriptor for updated field.
	commentDescUpdated := commentFields[11].Descriptor()
	// comment.DefaultUpdated holds the default value on creation for the updated field.
	comment.DefaultUpdated = commentDescUpdated.Default.(func() time.Time)
	// comment.UpdateDefaultUpdated holds the default value on update for the updated field.
	comment.UpdateDefaultUpdated = commentDescUpdated.UpdateDefault.(func() time.Time)
	editrecordFields := schema.EditRecord{}.Fields()
	_ = editrecordFields
	// editrecordDescFieldMask is the schema descriptor for field_mask field.
	editrecordDescFieldMask := editrecordFields[6].Descriptor()
	// editrecord.DefaultFieldMask holds the default value on creation for the field_mask field.
	editrecord.DefaultFieldMask = editrecordDescFieldMask.Default.(int64)
	// editrecordDescNote is the schema descriptor for note field.
	editrecordDescNote := editrecordFields[10].Descriptor()
	// editrecord.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	editrecord.NoteValidator = editrecordDescNote.Validators[0].(func(string) error)
	// editrecordDescUndo is the schema descriptor for undo field.
	editrecordDescUndo := editrecordFields[11].Descriptor()
	// editrecord.DefaultUndo holds the default value on creation for the undo field.
	editrecord.DefaultUndo = editrecordDescUndo.Default.(bool)
	// editrecordDescCreated is the schema descriptor for created field.
	editrecordDescCreated := editrecordFields[13].Descriptor()
	// editrecord.DefaultCreated holds the default value on creation for the created field.
	editrecord.DefaultCreated = editrecordDescCreated.Default.(func() time.Time)
	// editrecordDescUpdated is the schema descriptor for updated field.
	editrecordDescUpdated := editrecordFields[14].Descriptor()
	// editrecord.DefaultUpdated holds the default value on creation for the updated field.
	editrecord.DefaultUpdated = editrecordDescUpdated.Default.(func() time.Time)
	// editrecord.UpdateDefaultUpdated holds the default value on update for the updated field.
	editrecord.UpdateDefaultUpdated = editrecordDescUpdated.UpdateDefault.(func() time.Time)
	favoriteFields := schema.Favorite{}.Fields()
	_ = favoriteFields
	// favoriteDescName is the schema descriptor for name field.
	favoriteDescName := favoriteFields[2].Descriptor()
	// favorite.NameValidator is a validator for the "name" field. It is called by the builders before save.
	favorite.NameValidator = favoriteDescName.Validators[0].(func(string) error)
	// favoriteDescDescription is the schema descriptor for description field.
	favoriteDescDescription := favoriteFields[3].Descriptor()
	// favorite.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	favorite.DescriptionValidator = favoriteDescDescription.Validators[0].(func(string) error)
	// favoriteDescIsPrivate is the schema descriptor for is_private field.
	favoriteDescIsPrivate := favoriteFields[4].Descriptor()
	// favorite.DefaultIsPrivate holds the default value on creation for the is_private field.
	favorite.DefaultIsPrivate = favoriteDescIsPrivate.Default.(bool)
	// favoriteDescDefault is the schema descriptor for default field.
	favoriteDescDefault := favoriteFields[5].Descriptor()
	// favorite.DefaultDefault holds the default value on creation for the default field.
	favorite.DefaultDefault = favoriteDescDefault.Default.(bool)
	// favoriteDescCreated is the schema descriptor for created field.
	favoriteDescCreated := favoriteFields[6].Descriptor()
	// favorite.DefaultCreated holds the default value on creation for the created field.
	favorite.DefaultCreated = favoriteDescCreated.Default.(func() time.Time)
	// favoriteDescUpdated is the schema descriptor for updated field.
	favoriteDescUpdated := favoriteFields[7].Descriptor()
	// favorite.DefaultUpdated holds the default value on creation for the updated field.
	favorite.DefaultUpdated = favoriteDescUpdated.Default.(func() time.Time)
	// favorite.UpdateDefaultUpdated holds the default value on update for the updated field.
	favorite.UpdateDefaultUpdated = favoriteDescUpdated.UpdateDefault.(func() time.Time)
	favoriteitemFields := schema.FavoriteItem{}.Fields()
	_ = favoriteitemFields
	// favoriteitemDescNote is the schema descriptor for note field.
	favoriteitemDescNote := favoriteitemFields[3].Descriptor()
	// favoriteitem.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	favoriteitem.NoteValidator = favoriteitemDescNote.Validators[0].(func(string) error)
	// favoriteitemDescCreated is the schema descriptor for created field.
	favoriteitemDescCreated := favoriteitemFields[4].Descriptor()
	// favoriteitem.DefaultCreated holds the default value on creation for the created field.
	favoriteitem.DefaultCreated = favoriteitemDescCreated.Default.(func() time.Time)
	// favoriteitemDescUpdated is the schema descriptor for updated field.
	favoriteitemDescUpdated := favoriteitemFields[5].Descriptor()
	// favoriteitem.DefaultUpdated holds the default value on creation for the updated field.
	favoriteitem.DefaultUpdated = favoriteitemDescUpdated.Default.(func() time.Time)
	// favoriteitem.UpdateDefaultUpdated holds the default value on update for the updated field.
	favoriteitem.UpdateDefaultUpdated = favoriteitemDescUpdated.UpdateDefault.(func() time.Time)
	fieldpermissionmappingFields := schema.FieldPermissionMapping{}.Fields()
	_ = fieldpermissionmappingFields
	// fieldpermissionmappingDescIsRelation is the schema descriptor for is_relation field.
	fieldpermissionmappingDescIsRelation := fieldpermissionmappingFields[4].Descriptor()
	// fieldpermissionmapping.DefaultIsRelation holds the default value on creation for the is_relation field.
	fieldpermissionmapping.DefaultIsRelation = fieldpermissionmappingDescIsRelation.Default.(bool)
	// fieldpermissionmappingDescCreated is the schema descriptor for created field.
	fieldpermissionmappingDescCreated := fieldpermissionmappingFields[5].Descriptor()
	// fieldpermissionmapping.DefaultCreated holds the default value on creation for the created field.
	fieldpermissionmapping.DefaultCreated = fieldpermissionmappingDescCreated.Default.(func() time.Time)
	// fieldpermissionmappingDescUpdated is the schema descriptor for updated field.
	fieldpermissionmappingDescUpdated := fieldpermissionmappingFields[6].Descriptor()
	// fieldpermissionmapping.DefaultUpdated holds the default value on creation for the updated field.
	fieldpermissionmapping.DefaultUpdated = fieldpermissionmappingDescUpdated.Default.(func() time.Time)
	// fieldpermissionmapping.UpdateDefaultUpdated holds the default value on update for the updated field.
	fieldpermissionmapping.UpdateDefaultUpdated = fieldpermissionmappingDescUpdated.UpdateDefault.(func() time.Time)
	gameFields := schema.Game{}.Fields()
	_ = gameFields
	// gameDescTitleJp is the schema descriptor for title_jp field.
	gameDescTitleJp := gameFields[4].Descriptor()
	// game.DefaultTitleJp holds the default value on creation for the title_jp field.
	game.DefaultTitleJp = gameDescTitleJp.Default.(string)
	// game.TitleJpValidator is a validator for the "title_jp" field. It is called by the builders before save.
	game.TitleJpValidator = gameDescTitleJp.Validators[0].(func(string) error)
	// gameDescTitleZh is the schema descriptor for title_zh field.
	gameDescTitleZh := gameFields[5].Descriptor()
	// game.DefaultTitleZh holds the default value on creation for the title_zh field.
	game.DefaultTitleZh = gameDescTitleZh.Default.(string)
	// game.TitleZhValidator is a validator for the "title_zh" field. It is called by the builders before save.
	game.TitleZhValidator = gameDescTitleZh.Validators[0].(func(string) error)
	// gameDescTitleEn is the schema descriptor for title_en field.
	gameDescTitleEn := gameFields[6].Descriptor()
	// game.DefaultTitleEn holds the default value on creation for the title_en field.
	game.DefaultTitleEn = gameDescTitleEn.Default.(string)
	// game.TitleEnValidator is a validator for the "title_en" field. It is called by the builders before save.
	game.TitleEnValidator = gameDescTitleEn.Validators[0].(func(string) error)
	// gameDescIntroJp is the schema descriptor for intro_jp field.
	gameDescIntroJp := gameFields[8].Descriptor()
	// game.DefaultIntroJp holds the default value on creation for the intro_jp field.
	game.DefaultIntroJp = gameDescIntroJp.Default.(string)
	// game.IntroJpValidator is a validator for the "intro_jp" field. It is called by the builders before save.
	game.IntroJpValidator = gameDescIntroJp.Validators[0].(func(string) error)
	// gameDescIntroZh is the schema descriptor for intro_zh field.
	gameDescIntroZh := gameFields[9].Descriptor()
	// game.DefaultIntroZh holds the default value on creation for the intro_zh field.
	game.DefaultIntroZh = gameDescIntroZh.Default.(string)
	// game.IntroZhValidator is a validator for the "intro_zh" field. It is called by the builders before save.
	game.IntroZhValidator = gameDescIntroZh.Validators[0].(func(string) error)
	// gameDescIntroEn is the schema descriptor for intro_en field.
	gameDescIntroEn := gameFields[10].Descriptor()
	// game.DefaultIntroEn holds the default value on creation for the intro_en field.
	game.DefaultIntroEn = gameDescIntroEn.Default.(string)
	// game.IntroEnValidator is a validator for the "intro_en" field. It is called by the builders before save.
	game.IntroEnValidator = gameDescIntroEn.Validators[0].(func(string) error)
	// gameDescReleaseDateTba is the schema descriptor for release_date_tba field.
	gameDescReleaseDateTba := gameFields[12].Descriptor()
	// game.DefaultReleaseDateTba holds the default value on creation for the release_date_tba field.
	game.DefaultReleaseDateTba = gameDescReleaseDateTba.Default.(bool)
	// gameDescNsfw is the schema descriptor for nsfw field.
	gameDescNsfw := gameFields[15].Descriptor()
	// game.DefaultNsfw holds the default value on creation for the nsfw field.
	game.DefaultNsfw = gameDescNsfw.Default.(bool)
	// gameDescDownloads is the schema descriptor for downloads field.
	gameDescDownloads := gameFields[18].Descriptor()
	// game.DefaultDownloads holds the default value on creation for the downloads field.
	game.DefaultDownloads = gameDescDownloads.Default.(int)
	// gameDescViews is the schema descriptor for views field.
	gameDescViews := gameFields[19].Descriptor()
	// game.DefaultViews holds the default value on creation for the views field.
	game.DefaultViews = gameDescViews.Default.(int)
	// gameDescHotScore is the schema descriptor for hot_score field.
	gameDescHotScore := gameFields[20].Descriptor()
	// game.DefaultHotScore holds the default value on creation for the hot_score field.
	game.DefaultHotScore = gameDescHotScore.Default.(float64)
	// gameDescStatus is the schema descriptor for status field.
	gameDescStatus := gameFields[22].Descriptor()
	// game.DefaultStatus holds the default value on creation for the status field.
	game.DefaultStatus = gameDescStatus.Default.(int)
	// gameDescCreated is the schema descriptor for created field.
	gameDescCreated := gameFields[23].Descriptor()
	// game.DefaultCreated holds the default value on creation for the created field.
	game.DefaultCreated = gameDescCreated.Default.(func() time.Time)
	// gameDescUpdated is the schema descriptor for updated field.
	gameDescUpdated := gameFields[24].Descriptor()
	// game.DefaultUpdated holds the default value on creation for the updated field.
	game.DefaultUpdated = gameDescUpdated.Default.(func() time.Time)
	// game.UpdateDefaultUpdated holds the default value on update for the updated field.
	game.UpdateDefaultUpdated = gameDescUpdated.UpdateDefault.(func() time.Time)
	gamecharacterFields := schema.GameCharacter{}.Fields()
	_ = gamecharacterFields
	// gamecharacterDescNameJp is the schema descriptor for name_jp field.
	gamecharacterDescNameJp := gamecharacterFields[5].Descriptor()
	// gamecharacter.DefaultNameJp holds the default value on creation for the name_jp field.
	gamecharacter.DefaultNameJp = gamecharacterDescNameJp.Default.(string)
	// gamecharacterDescIntroJp is the schema descriptor for intro_jp field.
	gamecharacterDescIntroJp := gamecharacterFields[9].Descriptor()
	// gamecharacter.DefaultIntroJp holds the default value on creation for the intro_jp field.
	gamecharacter.DefaultIntroJp = gamecharacterDescIntroJp.Default.(string)
	// gamecharacter.IntroJpValidator is a validator for the "intro_jp" field. It is called by the builders before save.
	gamecharacter.IntroJpValidator = gamecharacterDescIntroJp.Validators[0].(func(string) error)
	// gamecharacterDescIntroZh is the schema descriptor for intro_zh field.
	gamecharacterDescIntroZh := gamecharacterFields[10].Descriptor()
	// gamecharacter.DefaultIntroZh holds the default value on creation for the intro_zh field.
	gamecharacter.DefaultIntroZh = gamecharacterDescIntroZh.Default.(string)
	// gamecharacter.IntroZhValidator is a validator for the "intro_zh" field. It is called by the builders before save.
	gamecharacter.IntroZhValidator = gamecharacterDescIntroZh.Validators[0].(func(string) error)
	// gamecharacterDescIntroEn is the schema descriptor for intro_en field.
	gamecharacterDescIntroEn := gamecharacterFields[11].Descriptor()
	// gamecharacter.DefaultIntroEn holds the default value on creation for the intro_en field.
	gamecharacter.DefaultIntroEn = gamecharacterDescIntroEn.Default.(string)
	// gamecharacter.IntroEnValidator is a validator for the "intro_en" field. It is called by the builders before save.
	gamecharacter.IntroEnValidator = gamecharacterDescIntroEn.Validators[0].(func(string) error)
	// gamecharacterDescCreated is the schema descriptor for created field.
	gamecharacterDescCreated := gamecharacterFields[22].Descriptor()
	// gamecharacter.DefaultCreated holds the default value on creation for the created field.
	gamecharacter.DefaultCreated = gamecharacterDescCreated.Default.(func() time.Time)
	// gamecharacterDescUpdated is the schema descriptor for updated field.
	gamecharacterDescUpdated := gamecharacterFields[23].Descriptor()
	// gamecharacter.DefaultUpdated holds the default value on creation for the updated field.
	gamecharacter.DefaultUpdated = gamecharacterDescUpdated.Default.(func() time.Time)
	// gamecharacter.UpdateDefaultUpdated holds the default value on update for the updated field.
	gamecharacter.UpdateDefaultUpdated = gamecharacterDescUpdated.UpdateDefault.(func() time.Time)
	gamecharacterrelationFields := schema.GameCharacterRelation{}.Fields()
	_ = gamecharacterrelationFields
	// gamecharacterrelationDescCreated is the schema descriptor for created field.
	gamecharacterrelationDescCreated := gamecharacterrelationFields[6].Descriptor()
	// gamecharacterrelation.DefaultCreated holds the default value on creation for the created field.
	gamecharacterrelation.DefaultCreated = gamecharacterrelationDescCreated.Default.(func() time.Time)
	// gamecharacterrelationDescUpdated is the schema descriptor for updated field.
	gamecharacterrelationDescUpdated := gamecharacterrelationFields[7].Descriptor()
	// gamecharacterrelation.DefaultUpdated holds the default value on creation for the updated field.
	gamecharacterrelation.DefaultUpdated = gamecharacterrelationDescUpdated.Default.(func() time.Time)
	// gamecharacterrelation.UpdateDefaultUpdated holds the default value on update for the updated field.
	gamecharacterrelation.UpdateDefaultUpdated = gamecharacterrelationDescUpdated.UpdateDefault.(func() time.Time)
	gamecoverFields := schema.GameCover{}.Fields()
	_ = gamecoverFields
	// gamecoverDescCreated is the schema descriptor for created field.
	gamecoverDescCreated := gamecoverFields[10].Descriptor()
	// gamecover.DefaultCreated holds the default value on creation for the created field.
	gamecover.DefaultCreated = gamecoverDescCreated.Default.(func() time.Time)
	// gamecoverDescUpdated is the schema descriptor for updated field.
	gamecoverDescUpdated := gamecoverFields[11].Descriptor()
	// gamecover.DefaultUpdated holds the default value on creation for the updated field.
	gamecover.DefaultUpdated = gamecoverDescUpdated.Default.(func() time.Time)
	// gamecover.UpdateDefaultUpdated holds the default value on update for the updated field.
	gamecover.UpdateDefaultUpdated = gamecoverDescUpdated.UpdateDefault.(func() time.Time)
	gamedeveloperFields := schema.GameDeveloper{}.Fields()
	_ = gamedeveloperFields
	// gamedeveloperDescName is the schema descriptor for name field.
	gamedeveloperDescName := gamedeveloperFields[4].Descriptor()
	// gamedeveloper.DefaultName holds the default value on creation for the name field.
	gamedeveloper.DefaultName = gamedeveloperDescName.Default.(string)
	// gamedeveloper.NameValidator is a validator for the "name" field. It is called by the builders before save.
	gamedeveloper.NameValidator = gamedeveloperDescName.Validators[0].(func(string) error)
	// gamedeveloperDescIntroJp is the schema descriptor for intro_jp field.
	gamedeveloperDescIntroJp := gamedeveloperFields[7].Descriptor()
	// gamedeveloper.DefaultIntroJp holds the default value on creation for the intro_jp field.
	gamedeveloper.DefaultIntroJp = gamedeveloperDescIntroJp.Default.(string)
	// gamedeveloper.IntroJpValidator is a validator for the "intro_jp" field. It is called by the builders before save.
	gamedeveloper.IntroJpValidator = gamedeveloperDescIntroJp.Validators[0].(func(string) error)
	// gamedeveloperDescIntroZh is the schema descriptor for intro_zh field.
	gamedeveloperDescIntroZh := gamedeveloperFields[8].Descriptor()
	// gamedeveloper.DefaultIntroZh holds the default value on creation for the intro_zh field.
	gamedeveloper.DefaultIntroZh = gamedeveloperDescIntroZh.Default.(string)
	// gamedeveloper.IntroZhValidator is a validator for the "intro_zh" field. It is called by the builders before save.
	gamedeveloper.IntroZhValidator = gamedeveloperDescIntroZh.Validators[0].(func(string) error)
	// gamedeveloperDescIntroEn is the schema descriptor for intro_en field.
	gamedeveloperDescIntroEn := gamedeveloperFields[9].Descriptor()
	// gamedeveloper.DefaultIntroEn holds the default value on creation for the intro_en field.
	gamedeveloper.DefaultIntroEn = gamedeveloperDescIntroEn.Default.(string)
	// gamedeveloper.IntroEnValidator is a validator for the "intro_en" field. It is called by the builders before save.
	gamedeveloper.IntroEnValidator = gamedeveloperDescIntroEn.Validators[0].(func(string) error)
	// gamedeveloperDescCreated is the schema descriptor for created field.
	gamedeveloperDescCreated := gamedeveloperFields[13].Descriptor()
	// gamedeveloper.DefaultCreated holds the default value on creation for the created field.
	gamedeveloper.DefaultCreated = gamedeveloperDescCreated.Default.(func() time.Time)
	// gamedeveloperDescUpdated is the schema descriptor for updated field.
	gamedeveloperDescUpdated := gamedeveloperFields[14].Descriptor()
	// gamedeveloper.DefaultUpdated holds the default value on creation for the updated field.
	gamedeveloper.DefaultUpdated = gamedeveloperDescUpdated.Default.(func() time.Time)
	// gamedeveloper.UpdateDefaultUpdated holds the default value on update for the updated field.
	gamedeveloper.UpdateDefaultUpdated = gamedeveloperDescUpdated.UpdateDefault.(func() time.Time)
	gamedeveloperrelationFields := schema.GameDeveloperRelation{}.Fields()
	_ = gamedeveloperrelationFields
	// gamedeveloperrelationDescCreated is the schema descriptor for created field.
	gamedeveloperrelationDescCreated := gamedeveloperrelationFields[4].Descriptor()
	// gamedeveloperrelation.DefaultCreated holds the default value on creation for the created field.
	gamedeveloperrelation.DefaultCreated = gamedeveloperrelationDescCreated.Default.(func() time.Time)
	// gamedeveloperrelationDescUpdated is the schema descriptor for updated field.
	gamedeveloperrelationDescUpdated := gamedeveloperrelationFields[5].Descriptor()
	// gamedeveloperrelation.DefaultUpdated holds the default value on creation for the updated field.
	gamedeveloperrelation.DefaultUpdated = gamedeveloperrelationDescUpdated.Default.(func() time.Time)
	// gamedeveloperrelation.UpdateDefaultUpdated holds the default value on update for the updated field.
	gamedeveloperrelation.UpdateDefaultUpdated = gamedeveloperrelationDescUpdated.UpdateDefault.(func() time.Time)
	gamedownloadresourceFields := schema.GameDownloadResource{}.Fields()
	_ = gamedownloadresourceFields
	// gamedownloadresourceDescStatus is the schema descriptor for status field.
	gamedownloadresourceDescStatus := gamedownloadresourceFields[0].Descriptor()
	// gamedownloadresource.DefaultStatus holds the default value on creation for the status field.
	gamedownloadresource.DefaultStatus = gamedownloadresourceDescStatus.Default.(int)
	// gamedownloadresourceDescNote is the schema descriptor for note field.
	gamedownloadresourceDescNote := gamedownloadresourceFields[6].Descriptor()
	// gamedownloadresource.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	gamedownloadresource.NoteValidator = gamedownloadresourceDescNote.Validators[0].(func(string) error)
	// gamedownloadresourceDescDownloads is the schema descriptor for downloads field.
	gamedownloadresourceDescDownloads := gamedownloadresourceFields[7].Descriptor()
	// gamedownloadresource.DefaultDownloads holds the default value on creation for the downloads field.
	gamedownloadresource.DefaultDownloads = gamedownloadresourceDescDownloads.Default.(int)
	// gamedownloadresourceDescCreated is the schema descriptor for created field.
	gamedownloadresourceDescCreated := gamedownloadresourceFields[10].Descriptor()
	// gamedownloadresource.DefaultCreated holds the default value on creation for the created field.
	gamedownloadresource.DefaultCreated = gamedownloadresourceDescCreated.Default.(func() time.Time)
	// gamedownloadresourceDescUpdated is the schema descriptor for updated field.
	gamedownloadresourceDescUpdated := gamedownloadresourceFields[11].Descriptor()
	// gamedownloadresource.DefaultUpdated holds the default value on creation for the updated field.
	gamedownloadresource.DefaultUpdated = gamedownloadresourceDescUpdated.Default.(func() time.Time)
	// gamedownloadresource.UpdateDefaultUpdated holds the default value on update for the updated field.
	gamedownloadresource.UpdateDefaultUpdated = gamedownloadresourceDescUpdated.UpdateDefault.(func() time.Time)
	gamedownloadresourcefileFields := schema.GameDownloadResourceFile{}.Fields()
	_ = gamedownloadresourcefileFields
	// gamedownloadresourcefileDescFileStatus is the schema descriptor for file_status field.
	gamedownloadresourcefileDescFileStatus := gamedownloadresourcefileFields[11].Descriptor()
	// gamedownloadresourcefile.DefaultFileStatus holds the default value on creation for the file_status field.
	gamedownloadresourcefile.DefaultFileStatus = gamedownloadresourcefileDescFileStatus.Default.(int)
	// gamedownloadresourcefileDescFileCheckStatus is the schema descriptor for file_check_status field.
	gamedownloadresourcefileDescFileCheckStatus := gamedownloadresourcefileFields[12].Descriptor()
	// gamedownloadresourcefile.DefaultFileCheckStatus holds the default value on creation for the file_check_status field.
	gamedownloadresourcefile.DefaultFileCheckStatus = gamedownloadresourcefileDescFileCheckStatus.Default.(int)
	// gamedownloadresourcefileDescIsVirusFalsePositive is the schema descriptor for is_virus_false_positive field.
	gamedownloadresourcefileDescIsVirusFalsePositive := gamedownloadresourcefileFields[13].Descriptor()
	// gamedownloadresourcefile.DefaultIsVirusFalsePositive holds the default value on creation for the is_virus_false_positive field.
	gamedownloadresourcefile.DefaultIsVirusFalsePositive = gamedownloadresourcefileDescIsVirusFalsePositive.Default.(bool)
	// gamedownloadresourcefileDescCreated is the schema descriptor for created field.
	gamedownloadresourcefileDescCreated := gamedownloadresourcefileFields[16].Descriptor()
	// gamedownloadresourcefile.DefaultCreated holds the default value on creation for the created field.
	gamedownloadresourcefile.DefaultCreated = gamedownloadresourcefileDescCreated.Default.(func() time.Time)
	// gamedownloadresourcefileDescUpdated is the schema descriptor for updated field.
	gamedownloadresourcefileDescUpdated := gamedownloadresourcefileFields[17].Descriptor()
	// gamedownloadresourcefile.DefaultUpdated holds the default value on creation for the updated field.
	gamedownloadresourcefile.DefaultUpdated = gamedownloadresourcefileDescUpdated.Default.(func() time.Time)
	// gamedownloadresourcefile.UpdateDefaultUpdated holds the default value on update for the updated field.
	gamedownloadresourcefile.UpdateDefaultUpdated = gamedownloadresourcefileDescUpdated.UpdateDefault.(func() time.Time)
	gamedownloadresourcefilehistoryFields := schema.GameDownloadResourceFileHistory{}.Fields()
	_ = gamedownloadresourcefilehistoryFields
	// gamedownloadresourcefilehistoryDescReason is the schema descriptor for reason field.
	gamedownloadresourcefilehistoryDescReason := gamedownloadresourcefilehistoryFields[6].Descriptor()
	// gamedownloadresourcefilehistory.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	gamedownloadresourcefilehistory.ReasonValidator = gamedownloadresourcefilehistoryDescReason.Validators[0].(func(string) error)
	// gamedownloadresourcefilehistoryDescCreated is the schema descriptor for created field.
	gamedownloadresourcefilehistoryDescCreated := gamedownloadresourcefilehistoryFields[9].Descriptor()
	// gamedownloadresourcefilehistory.DefaultCreated holds the default value on creation for the created field.
	gamedownloadresourcefilehistory.DefaultCreated = gamedownloadresourcefilehistoryDescCreated.Default.(func() time.Time)
	gamedownloadresourcereportFields := schema.GameDownloadResourceReport{}.Fields()
	_ = gamedownloadresourcereportFields
	// gamedownloadresourcereportDescDetail is the schema descriptor for detail field.
	gamedownloadresourcereportDescDetail := gamedownloadresourcereportFields[5].Descriptor()
	// gamedownloadresourcereport.DetailValidator is a validator for the "detail" field. It is called by the builders before save.
	gamedownloadresourcereport.DetailValidator = gamedownloadresourcereportDescDetail.Validators[0].(func(string) error)
	// gamedownloadresourcereportDescProcessNote is the schema descriptor for process_note field.
	gamedownloadresourcereportDescProcessNote := gamedownloadresourcereportFields[10].Descriptor()
	// gamedownloadresourcereport.ProcessNoteValidator is a validator for the "process_note" field. It is called by the builders before save.
	gamedownloadresourcereport.ProcessNoteValidator = gamedownloadresourcereportDescProcessNote.Validators[0].(func(string) error)
	// gamedownloadresourcereportDescReporterPenaltyApplied is the schema descriptor for reporter_penalty_applied field.
	gamedownloadresourcereportDescReporterPenaltyApplied := gamedownloadresourcereportFields[11].Descriptor()
	// gamedownloadresourcereport.DefaultReporterPenaltyApplied holds the default value on creation for the reporter_penalty_applied field.
	gamedownloadresourcereport.DefaultReporterPenaltyApplied = gamedownloadresourcereportDescReporterPenaltyApplied.Default.(bool)
	// gamedownloadresourcereportDescReportedPenaltyApplied is the schema descriptor for reported_penalty_applied field.
	gamedownloadresourcereportDescReportedPenaltyApplied := gamedownloadresourcereportFields[12].Descriptor()
	// gamedownloadresourcereport.DefaultReportedPenaltyApplied holds the default value on creation for the reported_penalty_applied field.
	gamedownloadresourcereport.DefaultReportedPenaltyApplied = gamedownloadresourcereportDescReportedPenaltyApplied.Default.(bool)
	// gamedownloadresourcereportDescCreated is the schema descriptor for created field.
	gamedownloadresourcereportDescCreated := gamedownloadresourcereportFields[13].Descriptor()
	// gamedownloadresourcereport.DefaultCreated holds the default value on creation for the created field.
	gamedownloadresourcereport.DefaultCreated = gamedownloadresourcereportDescCreated.Default.(func() time.Time)
	// gamedownloadresourcereportDescUpdated is the schema descriptor for updated field.
	gamedownloadresourcereportDescUpdated := gamedownloadresourcereportFields[14].Descriptor()
	// gamedownloadresourcereport.DefaultUpdated holds the default value on creation for the updated field.
	gamedownloadresourcereport.DefaultUpdated = gamedownloadresourcereportDescUpdated.Default.(func() time.Time)
	// gamedownloadresourcereport.UpdateDefaultUpdated holds the default value on update for the updated field.
	gamedownloadresourcereport.UpdateDefaultUpdated = gamedownloadresourcereportDescUpdated.UpdateDefault.(func() time.Time)
	gameimageFields := schema.GameImage{}.Fields()
	_ = gameimageFields
	// gameimageDescCreated is the schema descriptor for created field.
	gameimageDescCreated := gameimageFields[8].Descriptor()
	// gameimage.DefaultCreated holds the default value on creation for the created field.
	gameimage.DefaultCreated = gameimageDescCreated.Default.(func() time.Time)
	// gameimageDescUpdated is the schema descriptor for updated field.
	gameimageDescUpdated := gameimageFields[9].Descriptor()
	// gameimage.DefaultUpdated holds the default value on creation for the updated field.
	gameimage.DefaultUpdated = gameimageDescUpdated.Default.(func() time.Time)
	// gameimage.UpdateDefaultUpdated holds the default value on update for the updated field.
	gameimage.UpdateDefaultUpdated = gameimageDescUpdated.UpdateDefault.(func() time.Time)
	gamelinkFields := schema.GameLink{}.Fields()
	_ = gamelinkFields
	// gamelinkDescCreated is the schema descriptor for created field.
	gamelinkDescCreated := gamelinkFields[4].Descriptor()
	// gamelink.DefaultCreated holds the default value on creation for the created field.
	gamelink.DefaultCreated = gamelinkDescCreated.Default.(func() time.Time)
	// gamelinkDescUpdated is the schema descriptor for updated field.
	gamelinkDescUpdated := gamelinkFields[5].Descriptor()
	// gamelink.DefaultUpdated holds the default value on creation for the updated field.
	gamelink.DefaultUpdated = gamelinkDescUpdated.Default.(func() time.Time)
	// gamelink.UpdateDefaultUpdated holds the default value on update for the updated field.
	gamelink.UpdateDefaultUpdated = gamelinkDescUpdated.UpdateDefault.(func() time.Time)
	gamerelationFields := schema.GameRelation{}.Fields()
	_ = gamerelationFields
	// gamerelationDescCreated is the schema descriptor for created field.
	gamerelationDescCreated := gamerelationFields[4].Descriptor()
	// gamerelation.DefaultCreated holds the default value on creation for the created field.
	gamerelation.DefaultCreated = gamerelationDescCreated.Default.(func() time.Time)
	// gamerelationDescUpdated is the schema descriptor for updated field.
	gamerelationDescUpdated := gamerelationFields[5].Descriptor()
	// gamerelation.DefaultUpdated holds the default value on creation for the updated field.
	gamerelation.DefaultUpdated = gamerelationDescUpdated.Default.(func() time.Time)
	// gamerelation.UpdateDefaultUpdated holds the default value on update for the updated field.
	gamerelation.UpdateDefaultUpdated = gamerelationDescUpdated.UpdateDefault.(func() time.Time)
	gameuploadchunkFields := schema.GameUploadChunk{}.Fields()
	_ = gameuploadchunkFields
	// gameuploadchunkDescCreated is the schema descriptor for created field.
	gameuploadchunkDescCreated := gameuploadchunkFields[5].Descriptor()
	// gameuploadchunk.DefaultCreated holds the default value on creation for the created field.
	gameuploadchunk.DefaultCreated = gameuploadchunkDescCreated.Default.(func() time.Time)
	// gameuploadchunkDescUpdated is the schema descriptor for updated field.
	gameuploadchunkDescUpdated := gameuploadchunkFields[6].Descriptor()
	// gameuploadchunk.DefaultUpdated holds the default value on creation for the updated field.
	gameuploadchunk.DefaultUpdated = gameuploadchunkDescUpdated.Default.(func() time.Time)
	// gameuploadchunk.UpdateDefaultUpdated holds the default value on update for the updated field.
	gameuploadchunk.UpdateDefaultUpdated = gameuploadchunkDescUpdated.UpdateDefault.(func() time.Time)
	gameuploadsessionFields := schema.GameUploadSession{}.Fields()
	_ = gameuploadsessionFields
	// gameuploadsessionDescCreated is the schema descriptor for created field.
	gameuploadsessionDescCreated := gameuploadsessionFields[13].Descriptor()
	// gameuploadsession.DefaultCreated holds the default value on creation for the created field.
	gameuploadsession.DefaultCreated = gameuploadsessionDescCreated.Default.(func() time.Time)
	// gameuploadsessionDescUpdated is the schema descriptor for updated field.
	gameuploadsessionDescUpdated := gameuploadsessionFields[14].Descriptor()
	// gameuploadsession.DefaultUpdated holds the default value on creation for the updated field.
	gameuploadsession.DefaultUpdated = gameuploadsessionDescUpdated.Default.(func() time.Time)
	// gameuploadsession.UpdateDefaultUpdated holds the default value on update for the updated field.
	gameuploadsession.UpdateDefaultUpdated = gameuploadsessionDescUpdated.UpdateDefault.(func() time.Time)
	malwarescancaseFields := schema.MalwareScanCase{}.Fields()
	_ = malwarescancaseFields
	// malwarescancaseDescReviewNote is the schema descriptor for review_note field.
	malwarescancaseDescReviewNote := malwarescancaseFields[8].Descriptor()
	// malwarescancase.ReviewNoteValidator is a validator for the "review_note" field. It is called by the builders before save.
	malwarescancase.ReviewNoteValidator = malwarescancaseDescReviewNote.Validators[0].(func(string) error)
	// malwarescancaseDescDetector is the schema descriptor for detector field.
	malwarescancaseDescDetector := malwarescancaseFields[11].Descriptor()
	// malwarescancase.DetectorValidator is a validator for the "detector" field. It is called by the builders before save.
	malwarescancase.DetectorValidator = malwarescancaseDescDetector.Validators[0].(func(string) error)
	// malwarescancaseDescScanLogPath is the schema descriptor for scan_log_path field.
	malwarescancaseDescScanLogPath := malwarescancaseFields[14].Descriptor()
	// malwarescancase.ScanLogPathValidator is a validator for the "scan_log_path" field. It is called by the builders before save.
	malwarescancase.ScanLogPathValidator = malwarescancaseDescScanLogPath.Validators[0].(func(string) error)
	// malwarescancaseDescNotifyUploaderOnAllow is the schema descriptor for notify_uploader_on_allow field.
	malwarescancaseDescNotifyUploaderOnAllow := malwarescancaseFields[16].Descriptor()
	// malwarescancase.DefaultNotifyUploaderOnAllow holds the default value on creation for the notify_uploader_on_allow field.
	malwarescancase.DefaultNotifyUploaderOnAllow = malwarescancaseDescNotifyUploaderOnAllow.Default.(bool)
	// malwarescancaseDescCreated is the schema descriptor for created field.
	malwarescancaseDescCreated := malwarescancaseFields[22].Descriptor()
	// malwarescancase.DefaultCreated holds the default value on creation for the created field.
	malwarescancase.DefaultCreated = malwarescancaseDescCreated.Default.(func() time.Time)
	// malwarescancaseDescUpdated is the schema descriptor for updated field.
	malwarescancaseDescUpdated := malwarescancaseFields[23].Descriptor()
	// malwarescancase.DefaultUpdated holds the default value on creation for the updated field.
	malwarescancase.DefaultUpdated = malwarescancaseDescUpdated.Default.(func() time.Time)
	// malwarescancase.UpdateDefaultUpdated holds the default value on update for the updated field.
	malwarescancase.UpdateDefaultUpdated = malwarescancaseDescUpdated.UpdateDefault.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescTitle is the schema descriptor for title field.
	messageDescTitle := messageFields[3].Descriptor()
	// message.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	message.TitleValidator = messageDescTitle.Validators[0].(func(string) error)
	// messageDescContent is the schema descriptor for content field.
	messageDescContent := messageFields[4].Descriptor()
	// message.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	message.ContentValidator = messageDescContent.Validators[0].(func(string) error)
	// messageDescLinkText is the schema descriptor for link_text field.
	messageDescLinkText := messageFields[5].Descriptor()
	// message.LinkTextValidator is a validator for the "link_text" field. It is called by the builders before save.
	message.LinkTextValidator = messageDescLinkText.Validators[0].(func(string) error)
	// messageDescLinkURL is the schema descriptor for link_url field.
	messageDescLinkURL := messageFields[6].Descriptor()
	// message.LinkURLValidator is a validator for the "link_url" field. It is called by the builders before save.
	message.LinkURLValidator = messageDescLinkURL.Validators[0].(func(string) error)
	// messageDescExternalLink is the schema descriptor for external_link field.
	messageDescExternalLink := messageFields[7].Descriptor()
	// message.DefaultExternalLink holds the default value on creation for the external_link field.
	message.DefaultExternalLink = messageDescExternalLink.Default.(bool)
	// messageDescRead is the schema descriptor for read field.
	messageDescRead := messageFields[13].Descriptor()
	// message.DefaultRead holds the default value on creation for the read field.
	message.DefaultRead = messageDescRead.Default.(bool)
	// messageDescCreated is the schema descriptor for created field.
	messageDescCreated := messageFields[15].Descriptor()
	// message.DefaultCreated holds the default value on creation for the created field.
	message.DefaultCreated = messageDescCreated.Default.(func() time.Time)
	// messageDescUpdated is the schema descriptor for updated field.
	messageDescUpdated := messageFields[16].Descriptor()
	// message.DefaultUpdated holds the default value on creation for the updated field.
	message.DefaultUpdated = messageDescUpdated.Default.(func() time.Time)
	// message.UpdateDefaultUpdated holds the default value on update for the updated field.
	message.UpdateDefaultUpdated = messageDescUpdated.UpdateDefault.(func() time.Time)
	moderationeventFields := schema.ModerationEvent{}.Fields()
	_ = moderationeventFields
	// moderationeventDescAuditBy is the schema descriptor for audit_by field.
	moderationeventDescAuditBy := moderationeventFields[1].Descriptor()
	// moderationevent.DefaultAuditBy holds the default value on creation for the audit_by field.
	moderationevent.DefaultAuditBy = moderationeventDescAuditBy.Default.(int)
	// moderationeventDescModel is the schema descriptor for model field.
	moderationeventDescModel := moderationeventFields[2].Descriptor()
	// moderationevent.DefaultModel holds the default value on creation for the model field.
	moderationevent.DefaultModel = moderationeventDescModel.Default.(string)
	// moderationeventDescReason is the schema descriptor for reason field.
	moderationeventDescReason := moderationeventFields[8].Descriptor()
	// moderationevent.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	moderationevent.ReasonValidator = moderationeventDescReason.Validators[0].(func(string) error)
	// moderationeventDescEvidence is the schema descriptor for evidence field.
	moderationeventDescEvidence := moderationeventFields[9].Descriptor()
	// moderationevent.EvidenceValidator is a validator for the "evidence" field. It is called by the builders before save.
	moderationevent.EvidenceValidator = moderationeventDescEvidence.Validators[0].(func(string) error)
	// moderationeventDescCreatedAt is the schema descriptor for created_at field.
	moderationeventDescCreatedAt := moderationeventFields[12].Descriptor()
	// moderationevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	moderationevent.DefaultCreatedAt = moderationeventDescCreatedAt.Default.(func() time.Time)
	// moderationeventDescUpdatedAt is the schema descriptor for updated_at field.
	moderationeventDescUpdatedAt := moderationeventFields[13].Descriptor()
	// moderationevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	moderationevent.DefaultUpdatedAt = moderationeventDescUpdatedAt.Default.(func() time.Time)
	// moderationevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	moderationevent.UpdateDefaultUpdatedAt = moderationeventDescUpdatedAt.UpdateDefault.(func() time.Time)
	oidcidentityFields := schema.OidcIdentity{}.Fields()
	_ = oidcidentityFields
	// oidcidentityDescProvider is the schema descriptor for provider field.
	oidcidentityDescProvider := oidcidentityFields[2].Descriptor()
	// oidcidentity.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	oidcidentity.ProviderValidator = oidcidentityDescProvider.Validators[0].(func(string) error)
	// oidcidentityDescSubject is the schema descriptor for subject field.
	oidcidentityDescSubject := oidcidentityFields[3].Descriptor()
	// oidcidentity.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	oidcidentity.SubjectValidator = oidcidentityDescSubject.Validators[0].(func(string) error)
	// oidcidentityDescEmailAtLink is the schema descriptor for email_at_link field.
	oidcidentityDescEmailAtLink := oidcidentityFields[4].Descriptor()
	// oidcidentity.EmailAtLinkValidator is a validator for the "email_at_link" field. It is called by the builders before save.
	oidcidentity.EmailAtLinkValidator = oidcidentityDescEmailAtLink.Validators[0].(func(string) error)
	// oidcidentityDescCreated is the schema descriptor for created field.
	oidcidentityDescCreated := oidcidentityFields[6].Descriptor()
	// oidcidentity.DefaultCreated holds the default value on creation for the created field.
	oidcidentity.DefaultCreated = oidcidentityDescCreated.Default.(func() time.Time)
	// oidcidentityDescUpdated is the schema descriptor for updated field.
	oidcidentityDescUpdated := oidcidentityFields[7].Descriptor()
	// oidcidentity.DefaultUpdated holds the default value on creation for the updated field.
	oidcidentity.DefaultUpdated = oidcidentityDescUpdated.Default.(func() time.Time)
	// oidcidentity.UpdateDefaultUpdated holds the default value on update for the updated field.
	oidcidentity.UpdateDefaultUpdated = oidcidentityDescUpdated.UpdateDefault.(func() time.Time)
	rolefieldpermissionFields := schema.RoleFieldPermission{}.Fields()
	_ = rolefieldpermissionFields
	// rolefieldpermissionDescAllowMask is the schema descriptor for allow_mask field.
	rolefieldpermissionDescAllowMask := rolefieldpermissionFields[3].Descriptor()
	// rolefieldpermission.DefaultAllowMask holds the default value on creation for the allow_mask field.
	rolefieldpermission.DefaultAllowMask = rolefieldpermissionDescAllowMask.Default.(int64)
	// rolefieldpermissionDescCreated is the schema descriptor for created field.
	rolefieldpermissionDescCreated := rolefieldpermissionFields[4].Descriptor()
	// rolefieldpermission.DefaultCreated holds the default value on creation for the created field.
	rolefieldpermission.DefaultCreated = rolefieldpermissionDescCreated.Default.(func() time.Time)
	// rolefieldpermissionDescUpdated is the schema descriptor for updated field.
	rolefieldpermissionDescUpdated := rolefieldpermissionFields[5].Descriptor()
	// rolefieldpermission.DefaultUpdated holds the default value on creation for the updated field.
	rolefieldpermission.DefaultUpdated = rolefieldpermissionDescUpdated.Default.(func() time.Time)
	// rolefieldpermission.UpdateDefaultUpdated holds the default value on update for the updated field.
	rolefieldpermission.UpdateDefaultUpdated = rolefieldpermissionDescUpdated.UpdateDefault.(func() time.Time)
	sponsororderFields := schema.SponsorOrder{}.Fields()
	_ = sponsororderFields
	// sponsororderDescProviderOrderID is the schema descriptor for provider_order_id field.
	sponsororderDescProviderOrderID := sponsororderFields[1].Descriptor()
	// sponsororder.ProviderOrderIDValidator is a validator for the "provider_order_id" field. It is called by the builders before save.
	sponsororder.ProviderOrderIDValidator = sponsororderDescProviderOrderID.Validators[0].(func(string) error)
	// sponsororderDescProvider is the schema descriptor for provider field.
	sponsororderDescProvider := sponsororderFields[2].Descriptor()
	// sponsororder.DefaultProvider holds the default value on creation for the provider field.
	sponsororder.DefaultProvider = sponsororderDescProvider.Default.(string)
	// sponsororder.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	sponsororder.ProviderValidator = sponsororderDescProvider.Validators[0].(func(string) error)
	// sponsororderDescCurrency is the schema descriptor for currency field.
	sponsororderDescCurrency := sponsororderFields[4].Descriptor()
	// sponsororder.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	sponsororder.CurrencyValidator = sponsororderDescCurrency.Validators[0].(func(string) error)
	// sponsororderDescPaymentMethod is the schema descriptor for payment_method field.
	sponsororderDescPaymentMethod := sponsororderFields[5].Descriptor()
	// sponsororder.PaymentMethodValidator is a validator for the "payment_method" field. It is called by the builders before save.
	sponsororder.PaymentMethodValidator = sponsororderDescPaymentMethod.Validators[0].(func(string) error)
	// sponsororderDescSponsorName is the schema descriptor for sponsor_name field.
	sponsororderDescSponsorName := sponsororderFields[7].Descriptor()
	// sponsororder.SponsorNameValidator is a validator for the "sponsor_name" field. It is called by the builders before save.
	sponsororder.SponsorNameValidator = sponsororderDescSponsorName.Validators[0].(func(string) error)
	// sponsororderDescIsPrivate is the schema descriptor for is_private field.
	sponsororderDescIsPrivate := sponsororderFields[9].Descriptor()
	// sponsororder.DefaultIsPrivate holds the default value on creation for the is_private field.
	sponsororder.DefaultIsPrivate = sponsororderDescIsPrivate.Default.(bool)
	// sponsororderDescCallbackVerified is the schema descriptor for callback_verified field.
	sponsororderDescCallbackVerified := sponsororderFields[13].Descriptor()
	// sponsororder.DefaultCallbackVerified holds the default value on creation for the callback_verified field.
	sponsororder.DefaultCallbackVerified = sponsororderDescCallbackVerified.Default.(bool)
	// sponsororderDescCreated is the schema descriptor for created field.
	sponsororderDescCreated := sponsororderFields[14].Descriptor()
	// sponsororder.DefaultCreated holds the default value on creation for the created field.
	sponsororder.DefaultCreated = sponsororderDescCreated.Default.(func() time.Time)
	// sponsororderDescUpdated is the schema descriptor for updated field.
	sponsororderDescUpdated := sponsororderFields[15].Descriptor()
	// sponsororder.DefaultUpdated holds the default value on creation for the updated field.
	sponsororder.DefaultUpdated = sponsororderDescUpdated.Default.(func() time.Time)
	// sponsororder.UpdateDefaultUpdated holds the default value on update for the updated field.
	sponsororder.UpdateDefaultUpdated = sponsororderDescUpdated.UpdateDefault.(func() time.Time)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescCount is the schema descriptor for count field.
	tagDescCount := tagFields[3].Descriptor()
	// tag.DefaultCount holds the default value on creation for the count field.
	tag.DefaultCount = tagDescCount.Default.(int)
	// tagDescCreated is the schema descriptor for created field.
	tagDescCreated := tagFields[4].Descriptor()
	// tag.DefaultCreated holds the default value on creation for the created field.
	tag.DefaultCreated = tagDescCreated.Default.(func() time.Time)
	// tagDescUpdated is the schema descriptor for updated field.
	tagDescUpdated := tagFields[5].Descriptor()
	// tag.DefaultUpdated holds the default value on creation for the updated field.
	tag.DefaultUpdated = tagDescUpdated.Default.(func() time.Time)
	// tag.UpdateDefaultUpdated holds the default value on update for the updated field.
	tag.UpdateDefaultUpdated = tagDescUpdated.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescContentLimit is the schema descriptor for content_limit field.
	userDescContentLimit := userFields[8].Descriptor()
	// user.DefaultContentLimit holds the default value on creation for the content_limit field.
	user.DefaultContentLimit = userDescContentLimit.Default.(int)
	// userDescOnlyGamesWithResources is the schema descriptor for only_games_with_resources field.
	userDescOnlyGamesWithResources := userFields[9].Descriptor()
	// user.DefaultOnlyGamesWithResources holds the default value on creation for the only_games_with_resources field.
	user.DefaultOnlyGamesWithResources = userDescOnlyGamesWithResources.Default.(bool)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[10].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(int)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[11].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int)
	// userDescUploadInjectedFileTimes is the schema descriptor for upload_injected_file_times field.
	userDescUploadInjectedFileTimes := userFields[12].Descriptor()
	// user.DefaultUploadInjectedFileTimes holds the default value on creation for the upload_injected_file_times field.
	user.DefaultUploadInjectedFileTimes = userDescUploadInjectedFileTimes.Default.(int)
	// userDescTwoFactorEnabled is the schema descriptor for two_factor_enabled field.
	userDescTwoFactorEnabled := userFields[15].Descriptor()
	// user.DefaultTwoFactorEnabled holds the default value on creation for the two_factor_enabled field.
	user.DefaultTwoFactorEnabled = userDescTwoFactorEnabled.Default.(bool)
	// userDescCreated is the schema descriptor for created field.
	userDescCreated := userFields[17].Descriptor()
	// user.DefaultCreated holds the default value on creation for the created field.
	user.DefaultCreated = userDescCreated.Default.(func() time.Time)
	// userDescUpdated is the schema descriptor for updated field.
	userDescUpdated := userFields[18].Descriptor()
	// user.DefaultUpdated holds the default value on creation for the updated field.
	user.DefaultUpdated = userDescUpdated.Default.(func() time.Time)
	// user.UpdateDefaultUpdated holds the default value on update for the updated field.
	user.UpdateDefaultUpdated = userDescUpdated.UpdateDefault.(func() time.Time)
	userbannedrecordFields := schema.UserBannedRecord{}.Fields()
	_ = userbannedrecordFields
	// userbannedrecordDescBannedAt is the schema descriptor for banned_at field.
	userbannedrecordDescBannedAt := userbannedrecordFields[2].Descriptor()
	// userbannedrecord.DefaultBannedAt holds the default value on creation for the banned_at field.
	userbannedrecord.DefaultBannedAt = userbannedrecordDescBannedAt.Default.(func() time.Time)
	// userbannedrecordDescBannedReason is the schema descriptor for banned_reason field.
	userbannedrecordDescBannedReason := userbannedrecordFields[3].Descriptor()
	// userbannedrecord.BannedReasonValidator is a validator for the "banned_reason" field. It is called by the builders before save.
	userbannedrecord.BannedReasonValidator = userbannedrecordDescBannedReason.Validators[0].(func(string) error)
	// userbannedrecordDescIsPermanent is the schema descriptor for is_permanent field.
	userbannedrecordDescIsPermanent := userbannedrecordFields[6].Descriptor()
	// userbannedrecord.DefaultIsPermanent holds the default value on creation for the is_permanent field.
	userbannedrecord.DefaultIsPermanent = userbannedrecordDescIsPermanent.Default.(bool)
	userfieldpermissionFields := schema.UserFieldPermission{}.Fields()
	_ = userfieldpermissionFields
	// userfieldpermissionDescAllowMask is the schema descriptor for allow_mask field.
	userfieldpermissionDescAllowMask := userfieldpermissionFields[3].Descriptor()
	// userfieldpermission.DefaultAllowMask holds the default value on creation for the allow_mask field.
	userfieldpermission.DefaultAllowMask = userfieldpermissionDescAllowMask.Default.(int64)
	// userfieldpermissionDescCreated is the schema descriptor for created field.
	userfieldpermissionDescCreated := userfieldpermissionFields[4].Descriptor()
	// userfieldpermission.DefaultCreated holds the default value on creation for the created field.
	userfieldpermission.DefaultCreated = userfieldpermissionDescCreated.Default.(func() time.Time)
	// userfieldpermissionDescUpdated is the schema descriptor for updated field.
	userfieldpermissionDescUpdated := userfieldpermissionFields[5].Descriptor()
	// userfieldpermission.DefaultUpdated holds the default value on creation for the updated field.
	userfieldpermission.DefaultUpdated = userfieldpermissionDescUpdated.Default.(func() time.Time)
	// userfieldpermission.UpdateDefaultUpdated holds the default value on update for the updated field.
	userfieldpermission.UpdateDefaultUpdated = userfieldpermissionDescUpdated.UpdateDefault.(func() time.Time)
	usergamepvnmappingFields := schema.UserGamePvnMapping{}.Fields()
	_ = usergamepvnmappingFields
	// usergamepvnmappingDescTotalPlayTime is the schema descriptor for total_play_time field.
	usergamepvnmappingDescTotalPlayTime := usergamepvnmappingFields[4].Descriptor()
	// usergamepvnmapping.DefaultTotalPlayTime holds the default value on creation for the total_play_time field.
	usergamepvnmapping.DefaultTotalPlayTime = usergamepvnmappingDescTotalPlayTime.Default.(int)
	// usergamepvnmappingDescPlayType is the schema descriptor for play_type field.
	usergamepvnmappingDescPlayType := usergamepvnmappingFields[6].Descriptor()
	// usergamepvnmapping.DefaultPlayType holds the default value on creation for the play_type field.
	usergamepvnmapping.DefaultPlayType = usergamepvnmappingDescPlayType.Default.(int)
	// usergamepvnmappingDescMyRate is the schema descriptor for my_rate field.
	usergamepvnmappingDescMyRate := usergamepvnmappingFields[7].Descriptor()
	// usergamepvnmapping.DefaultMyRate holds the default value on creation for the my_rate field.
	usergamepvnmapping.DefaultMyRate = usergamepvnmappingDescMyRate.Default.(int)
	// usergamepvnmappingDescSyncedAt is the schema descriptor for synced_at field.
	usergamepvnmappingDescSyncedAt := usergamepvnmappingFields[8].Descriptor()
	// usergamepvnmapping.DefaultSyncedAt holds the default value on creation for the synced_at field.
	usergamepvnmapping.DefaultSyncedAt = usergamepvnmappingDescSyncedAt.Default.(func() time.Time)
	// usergamepvnmappingDescCreated is the schema descriptor for created field.
	usergamepvnmappingDescCreated := usergamepvnmappingFields[9].Descriptor()
	// usergamepvnmapping.DefaultCreated holds the default value on creation for the created field.
	usergamepvnmapping.DefaultCreated = usergamepvnmappingDescCreated.Default.(func() time.Time)
	// usergamepvnmappingDescUpdated is the schema descriptor for updated field.
	usergamepvnmappingDescUpdated := usergamepvnmappingFields[10].Descriptor()
	// usergamepvnmapping.DefaultUpdated holds the default value on creation for the updated field.
	usergamepvnmapping.DefaultUpdated = usergamepvnmappingDescUpdated.Default.(func() time.Time)
	// usergamepvnmapping.UpdateDefaultUpdated holds the default value on update for the updated field.
	usergamepvnmapping.UpdateDefaultUpdated = usergamepvnmappingDescUpdated.UpdateDefault.(func() time.Time)
	userloginsessionFields := schema.UserLoginSession{}.Fields()
	_ = userloginsessionFields
	// userloginsessionDescRefreshTokenHash is the schema descriptor for refresh_token_hash field.
	userloginsessionDescRefreshTokenHash := userloginsessionFields[2].Descriptor()
	// userloginsession.RefreshTokenHashValidator is a validator for the "refresh_token_hash" field. It is called by the builders before save.
	userloginsession.RefreshTokenHashValidator = userloginsessionDescRefreshTokenHash.Validators[0].(func(string) error)
	// userloginsessionDescRefreshTokenPrefix is the schema descriptor for refresh_token_prefix field.
	userloginsessionDescRefreshTokenPrefix := userloginsessionFields[3].Descriptor()
	// userloginsession.RefreshTokenPrefixValidator is a validator for the "refresh_token_prefix" field. It is called by the builders before save.
	userloginsession.RefreshTokenPrefixValidator = userloginsessionDescRefreshTokenPrefix.Validators[0].(func(string) error)
	// userloginsessionDescStatus is the schema descriptor for status field.
	userloginsessionDescStatus := userloginsessionFields[4].Descriptor()
	// userloginsession.DefaultStatus holds the default value on creation for the status field.
	userloginsession.DefaultStatus = userloginsessionDescStatus.Default.(int)
	// userloginsessionDescFamilyID is the schema descriptor for family_id field.
	userloginsessionDescFamilyID := userloginsessionFields[5].Descriptor()
	// userloginsession.DefaultFamilyID holds the default value on creation for the family_id field.
	userloginsession.DefaultFamilyID = userloginsessionDescFamilyID.Default.(func() string)
	// userloginsessionDescBlockedReason is the schema descriptor for blocked_reason field.
	userloginsessionDescBlockedReason := userloginsessionFields[12].Descriptor()
	// userloginsession.BlockedReasonValidator is a validator for the "blocked_reason" field. It is called by the builders before save.
	userloginsession.BlockedReasonValidator = userloginsessionDescBlockedReason.Validators[0].(func(string) error)
	// userloginsessionDescCreated is the schema descriptor for created field.
	userloginsessionDescCreated := userloginsessionFields[16].Descriptor()
	// userloginsession.DefaultCreated holds the default value on creation for the created field.
	userloginsession.DefaultCreated = userloginsessionDescCreated.Default.(func() time.Time)
	// userloginsessionDescUpdated is the schema descriptor for updated field.
	userloginsessionDescUpdated := userloginsessionFields[17].Descriptor()
	// userloginsession.DefaultUpdated holds the default value on creation for the updated field.
	userloginsession.DefaultUpdated = userloginsessionDescUpdated.Default.(func() time.Time)
	// userloginsession.UpdateDefaultUpdated holds the default value on update for the updated field.
	userloginsession.UpdateDefaultUpdated = userloginsessionDescUpdated.UpdateDefault.(func() time.Time)
	userpasskeycredentialFields := schema.UserPasskeyCredential{}.Fields()
	_ = userpasskeycredentialFields
	// userpasskeycredentialDescCredentialID is the schema descriptor for credential_id field.
	userpasskeycredentialDescCredentialID := userpasskeycredentialFields[2].Descriptor()
	// userpasskeycredential.CredentialIDValidator is a validator for the "credential_id" field. It is called by the builders before save.
	userpasskeycredential.CredentialIDValidator = userpasskeycredentialDescCredentialID.Validators[0].(func(string) error)
	// userpasskeycredentialDescCounter is the schema descriptor for counter field.
	userpasskeycredentialDescCounter := userpasskeycredentialFields[4].Descriptor()
	// userpasskeycredential.DefaultCounter holds the default value on creation for the counter field.
	userpasskeycredential.DefaultCounter = userpasskeycredentialDescCounter.Default.(int)
	// userpasskeycredentialDescAaguid is the schema descriptor for aaguid field.
	userpasskeycredentialDescAaguid := userpasskeycredentialFields[6].Descriptor()
	// userpasskeycredential.AaguidValidator is a validator for the "aaguid" field. It is called by the builders before save.
	userpasskeycredential.AaguidValidator = userpasskeycredentialDescAaguid.Validators[0].(func(string) error)
	// userpasskeycredentialDescDeviceType is the schema descriptor for device_type field.
	userpasskeycredentialDescDeviceType := userpasskeycredentialFields[7].Descriptor()
	// userpasskeycredential.DeviceTypeValidator is a validator for the "device_type" field. It is called by the builders before save.
	userpasskeycredential.DeviceTypeValidator = userpasskeycredentialDescDeviceType.Validators[0].(func(string) error)
	// userpasskeycredentialDescCredentialBackedUp is the schema descriptor for credential_backed_up field.
	userpasskeycredentialDescCredentialBackedUp := userpasskeycredentialFields[8].Descriptor()
	// userpasskeycredential.DefaultCredentialBackedUp holds the default value on creation for the credential_backed_up field.
	userpasskeycredential.DefaultCredentialBackedUp = userpasskeycredentialDescCredentialBackedUp.Default.(bool)
	// userpasskeycredentialDescName is the schema descriptor for name field.
	userpasskeycredentialDescName := userpasskeycredentialFields[9].Descriptor()
	// userpasskeycredential.NameValidator is a validator for the "name" field. It is called by the builders before save.
	userpasskeycredential.NameValidator = userpasskeycredentialDescName.Validators[0].(func(string) error)
	// userpasskeycredentialDescCreated is the schema descriptor for created field.
	userpasskeycredentialDescCreated := userpasskeycredentialFields[12].Descriptor()
	// userpasskeycredential.DefaultCreated holds the default value on creation for the created field.
	userpasskeycredential.DefaultCreated = userpasskeycredentialDescCreated.Default.(func() time.Time)
	// userpasskeycredentialDescUpdated is the schema descriptor for updated field.
	userpasskeycredentialDescUpdated := userpasskeycredentialFields[13].Descriptor()
	// userpasskeycredential.DefaultUpdated holds the default value on creation for the updated field.
	userpasskeycredential.DefaultUpdated = userpasskeycredentialDescUpdated.Default.(func() time.Time)
	// userpasskeycredential.UpdateDefaultUpdated holds the default value on update for the updated field.
	userpasskeycredential.UpdateDefaultUpdated = userpasskeycredentialDescUpdated.UpdateDefault.(func() time.Time)
	userpvnbindingFields := schema.UserPvnBinding{}.Fields()
	_ = userpvnbindingFields
	// userpvnbindingDescPvnUserName is the schema descriptor for pvn_user_name field.
	userpvnbindingDescPvnUserName := userpvnbindingFields[3].Descriptor()
	// userpvnbinding.PvnUserNameValidator is a validator for the "pvn_user_name" field. It is called by the builders before save.
	userpvnbinding.PvnUserNameValidator = userpvnbindingDescPvnUserName.Validators[0].(func(string) error)
	// userpvnbindingDescPvnUserAvatar is the schema descriptor for pvn_user_avatar field.
	userpvnbindingDescPvnUserAvatar := userpvnbindingFields[4].Descriptor()
	// userpvnbinding.PvnUserAvatarValidator is a validator for the "pvn_user_avatar" field. It is called by the builders before save.
	userpvnbinding.PvnUserAvatarValidator = userpvnbindingDescPvnUserAvatar.Validators[0].(func(string) error)
	// userpvnbindingDescCreated is the schema descriptor for created field.
	userpvnbindingDescCreated := userpvnbindingFields[7].Descriptor()
	// userpvnbinding.DefaultCreated holds the default value on creation for the created field.
	userpvnbinding.DefaultCreated = userpvnbindingDescCreated.Default.(func() time.Time)
	// userpvnbindingDescUpdated is the schema descriptor for updated field.
	userpvnbindingDescUpdated := userpvnbindingFields[8].Descriptor()
	// userpvnbinding.DefaultUpdated holds the default value on creation for the updated field.
	userpvnbinding.DefaultUpdated = userpvnbindingDescUpdated.Default.(func() time.Time)
	// userpvnbinding.UpdateDefaultUpdated holds the default value on update for the updated field.
	userpvnbinding.UpdateDefaultUpdated = userpvnbindingDescUpdated.UpdateDefault.(func() time.Time)
	useruploadquotaFields := schema.UserUploadQuota{}.Fields()
	_ = useruploadquotaFields
	// useruploadquotaDescIsFirstGrant is the schema descriptor for is_first_grant field.
	useruploadquotaDescIsFirstGrant := useruploadquotaFields[4].Descriptor()
	// useruploadquota.DefaultIsFirstGrant holds the default value on creation for the is_first_grant field.
	useruploadquota.DefaultIsFirstGrant = useruploadquotaDescIsFirstGrant.Default.(bool)
	// useruploadquotaDescCreated is the schema descriptor for created field.
	useruploadquotaDescCreated := useruploadquotaFields[5].Descriptor()
	// useruploadquota.DefaultCreated holds the default value on creation for the created field.
	useruploadquota.DefaultCreated = useruploadquotaDescCreated.Default.(func() time.Time)
	// useruploadquotaDescUpdated is the schema descriptor for updated field.
	useruploadquotaDescUpdated := useruploadquotaFields[6].Descriptor()
	// useruploadquota.DefaultUpdated holds the default value on creation for the updated field.
	useruploadquota.DefaultUpdated = useruploadquotaDescUpdated.Default.(func() time.Time)
	// useruploadquota.UpdateDefaultUpdated holds the default value on update for the updated field.
	useruploadquota.UpdateDefaultUpdated = useruploadquotaDescUpdated.UpdateDefault.(func() time.Time)
	useruploadquotarecordFields := schema.UserUploadQuotaRecord{}.Fields()
	_ = useruploadquotarecordFields
	// useruploadquotarecordDescActionReason is the schema descriptor for action_reason field.
	useruploadquotarecordDescActionReason := useruploadquotarecordFields[4].Descriptor()
	// useruploadquotarecord.ActionReasonValidator is a validator for the "action_reason" field. It is called by the builders before save.
	useruploadquotarecord.ActionReasonValidator = useruploadquotarecordDescActionReason.Validators[0].(func(string) error)
	// useruploadquotarecordDescCreated is the schema descriptor for created field.
	useruploadquotarecordDescCreated := useruploadquotarecordFields[8].Descriptor()
	// useruploadquotarecord.DefaultCreated holds the default value on creation for the created field.
	useruploadquotarecord.DefaultCreated = useruploadquotarecordDescCreated.Default.(func() time.Time)
	// useruploadquotarecordDescUpdated is the schema descriptor for updated field.
	useruploadquotarecordDescUpdated := useruploadquotarecordFields[9].Descriptor()
	// useruploadquotarecord.DefaultUpdated holds the default value on creation for the updated field.
	useruploadquotarecord.DefaultUpdated = useruploadquotarecordDescUpdated.Default.(func() time.Time)
	// useruploadquotarecord.UpdateDefaultUpdated holds the default value on update for the updated field.
	useruploadquotarecord.UpdateDefaultUpdated = useruploadquotarecordDescUpdated.UpdateDefault.(func() time.Time)
	walkthroughFields := schema.Walkthrough{}.Fields()
	_ = walkthroughFields
	// walkthroughDescTitle is the schema descriptor for title field.
	walkthroughDescTitle := walkthroughFields[2].Descriptor()
	// walkthrough.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	walkthrough.TitleValidator = walkthroughDescTitle.Validators[0].(func(string) error)
	// walkthroughDescHTML is the schema descriptor for html field.
	walkthroughDescHTML := walkthroughFields[4].Descriptor()
	// walkthrough.HTMLValidator is a validator for the "html" field. It is called by the builders before save.
	walkthrough.HTMLValidator = walkthroughDescHTML.Validators[0].(func(string) error)
	// walkthroughDescLang is the schema descriptor for lang field.
	walkthroughDescLang := walkthroughFields[5].Descriptor()
	// walkthrough.LangValidator is a validator for the "lang" field. It is called by the builders before save.
	walkthrough.LangValidator = walkthroughDescLang.Validators[0].(func(string) error)
	// walkthroughDescCreated is the schema descriptor for created field.
	walkthroughDescCreated := walkthroughFields[6].Descriptor()
	// walkthrough.DefaultCreated holds the default value on creation for the created field.
	walkthrough.DefaultCreated = walkthroughDescCreated.Default.(func() time.Time)
	// walkthroughDescUpdated is the schema descriptor for updated field.
	walkthroughDescUpdated := walkthroughFields[7].Descriptor()
	// walkthrough.DefaultUpdated holds the default value on creation for the updated field.
	walkthrough.DefaultUpdated = walkthroughDescUpdated.Default.(func() time.Time)
	// walkthrough.UpdateDefaultUpdated holds the default value on update for the updated field.
	walkthrough.UpdateDefaultUpdated = walkthroughDescUpdated.UpdateDefault.(func() time.Time)
	// walkthroughDescEdited is the schema descriptor for edited field.
	walkthroughDescEdited := walkthroughFields[8].Descriptor()
	// walkthrough.DefaultEdited holds the default value on creation for the edited field.
	walkthrough.DefaultEdited = walkthroughDescEdited.Default.(bool)
}
