// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/predicate"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/sponsororder"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/user"
)

// SponsorOrderQuery is the builder for querying SponsorOrder entities.
type SponsorOrderQuery struct {
	config
	ctx        *QueryContext
	order      []sponsororder.OrderOption
	inters     []Interceptor
	predicates []predicate.SponsorOrder
	withUser   *UserQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SponsorOrderQuery builder.
func (_q *SponsorOrderQuery) Where(ps ...predicate.SponsorOrder) *SponsorOrderQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SponsorOrderQuery) Limit(limit int) *SponsorOrderQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SponsorOrderQuery) Offset(offset int) *SponsorOrderQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SponsorOrderQuery) Unique(unique bool) *SponsorOrderQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SponsorOrderQuery) Order(o ...sponsororder.OrderOption) *SponsorOrderQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *SponsorOrderQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sponsororder.Table, sponsororder.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sponsororder.UserTable, sponsororder.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SponsorOrder entity from the query.
// Returns a *NotFoundError when no SponsorOrder was found.
func (_q *SponsorOrderQuery) First(ctx context.Context) (*SponsorOrder, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sponsororder.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SponsorOrderQuery) FirstX(ctx context.Context) *SponsorOrder {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SponsorOrder ID from the query.
// Returns a *NotFoundError when no SponsorOrder ID was found.
func (_q *SponsorOrderQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sponsororder.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SponsorOrderQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SponsorOrder entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SponsorOrder entity is found.
// Returns a *NotFoundError when no SponsorOrder entities are found.
func (_q *SponsorOrderQuery) Only(ctx context.Context) (*SponsorOrder, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sponsororder.Label}
	default:
		return nil, &NotSingularError{sponsororder.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SponsorOrderQuery) OnlyX(ctx context.Context) *SponsorOrder {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SponsorOrder ID in the query.
// Returns a *NotSingularError when more than one SponsorOrder ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SponsorOrderQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sponsororder.Label}
	default:
		err = &NotSingularError{sponsororder.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SponsorOrderQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SponsorOrders.
func (_q *SponsorOrderQuery) All(ctx context.Context) ([]*SponsorOrder, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SponsorOrder, *SponsorOrderQuery]()
	return withInterceptors[[]*SponsorOrder](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SponsorOrderQuery) AllX(ctx context.Context) []*SponsorOrder {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SponsorOrder IDs.
func (_q *SponsorOrderQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(sponsororder.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SponsorOrderQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SponsorOrderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SponsorOrderQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SponsorOrderQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SponsorOrderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SponsorOrderQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SponsorOrderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SponsorOrderQuery) Clone() *SponsorOrderQuery {
	if _q == nil {
		return nil
	}
	return &SponsorOrderQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]sponsororder.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.SponsorOrder{}, _q.predicates...),
		withUser:   _q.withUser.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SponsorOrderQuery) WithUser(opts ...func(*UserQuery)) *SponsorOrderQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProviderOrderID string `json:"provider_order_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SponsorOrder.Query().
//		GroupBy(sponsororder.FieldProviderOrderID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SponsorOrderQuery) GroupBy(field string, fields ...string) *SponsorOrderGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SponsorOrderGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = sponsororder.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProviderOrderID string `json:"provider_order_id,omitempty"`
//	}
//
//	client.SponsorOrder.Query().
//		Select(sponsororder.FieldProviderOrderID).
//		Scan(ctx, &v)
func (_q *SponsorOrderQuery) Select(fields ...string) *SponsorOrderSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SponsorOrderSelect{SponsorOrderQuery: _q}
	sbuild.label = sponsororder.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SponsorOrderSelect configured with the given aggregations.
func (_q *SponsorOrderQuery) Aggregate(fns ...AggregateFunc) *SponsorOrderSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SponsorOrderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !sponsororder.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SponsorOrderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SponsorOrder, error) {
	var (
		nodes       = []*SponsorOrder{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SponsorOrder).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SponsorOrder{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *SponsorOrder, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SponsorOrderQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*SponsorOrder, init func(*SponsorOrder), assign func(*SponsorOrder, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SponsorOrder)
	for i := range nodes {
		if nodes[i].UserID == nil {
			continue
		}
		fk := *nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SponsorOrderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SponsorOrderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sponsororder.Table, sponsororder.Columns, sqlgraph.NewFieldSpec(sponsororder.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sponsororder.FieldID)
		for i := range fields {
			if fields[i] != sponsororder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(sponsororder.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SponsorOrderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(sponsororder.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = sponsororder.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SponsorOrderQuery) ForUpdate(opts ...sql.LockOption) *SponsorOrderQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SponsorOrderQuery) ForShare(opts ...sql.LockOption) *SponsorOrderQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *SponsorOrderQuery) Modify(modifiers ...func(s *sql.Selector)) *SponsorOrderSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// SponsorOrderGroupBy is the group-by builder for SponsorOrder entities.
type SponsorOrderGroupBy struct {
	selector
	build *SponsorOrderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SponsorOrderGroupBy) Aggregate(fns ...AggregateFunc) *SponsorOrderGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SponsorOrderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SponsorOrderQuery, *SponsorOrderGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SponsorOrderGroupBy) sqlScan(ctx context.Context, root *SponsorOrderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SponsorOrderSelect is the builder for selecting fields of SponsorOrder entities.
type SponsorOrderSelect struct {
	*SponsorOrderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SponsorOrderSelect) Aggregate(fns ...AggregateFunc) *SponsorOrderSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SponsorOrderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SponsorOrderQuery, *SponsorOrderSelect](ctx, _s.SponsorOrderQuery, _s, _s.inters, v)
}

func (_s *SponsorOrderSelect) sqlScan(ctx context.Context, root *SponsorOrderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *SponsorOrderSelect) Modify(modifiers ...func(s *sql.Selector)) *SponsorOrderSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
