// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/user"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/userfieldpermission"
)

// UserFieldPermissionCreate is the builder for creating a UserFieldPermission entity.
type UserFieldPermissionCreate struct {
	config
	mutation *UserFieldPermissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserFieldPermissionCreate) SetUserID(v int) *UserFieldPermissionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetEntity sets the "entity" field.
func (_c *UserFieldPermissionCreate) SetEntity(v userfieldpermission.Entity) *UserFieldPermissionCreate {
	_c.mutation.SetEntity(v)
	return _c
}

// SetAllowMask sets the "allow_mask" field.
func (_c *UserFieldPermissionCreate) SetAllowMask(v int64) *UserFieldPermissionCreate {
	_c.mutation.SetAllowMask(v)
	return _c
}

// SetNillableAllowMask sets the "allow_mask" field if the given value is not nil.
func (_c *UserFieldPermissionCreate) SetNillableAllowMask(v *int64) *UserFieldPermissionCreate {
	if v != nil {
		_c.SetAllowMask(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *UserFieldPermissionCreate) SetCreated(v time.Time) *UserFieldPermissionCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *UserFieldPermissionCreate) SetNillableCreated(v *time.Time) *UserFieldPermissionCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *UserFieldPermissionCreate) SetUpdated(v time.Time) *UserFieldPermissionCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *UserFieldPermissionCreate) SetNillableUpdated(v *time.Time) *UserFieldPermissionCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserFieldPermissionCreate) SetID(v int) *UserFieldPermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserFieldPermissionCreate) SetUser(v *User) *UserFieldPermissionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserFieldPermissionMutation object of the builder.
func (_c *UserFieldPermissionCreate) Mutation() *UserFieldPermissionMutation {
	return _c.mutation
}

// Save creates the UserFieldPermission in the database.
func (_c *UserFieldPermissionCreate) Save(ctx context.Context) (*UserFieldPermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserFieldPermissionCreate) SaveX(ctx context.Context) *UserFieldPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserFieldPermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserFieldPermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserFieldPermissionCreate) defaults() {
	if _, ok := _c.mutation.AllowMask(); !ok {
		v := userfieldpermission.DefaultAllowMask
		_c.mutation.SetAllowMask(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := userfieldpermission.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := userfieldpermission.DefaultUpdated()
		_c.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserFieldPermissionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserFieldPermission.user_id"`)}
	}
	if _, ok := _c.mutation.Entity(); !ok {
		return &ValidationError{Name: "entity", err: errors.New(`ent: missing required field "UserFieldPermission.entity"`)}
	}
	if v, ok := _c.mutation.Entity(); ok {
		if err := userfieldpermission.EntityValidator(v); err != nil {
			return &ValidationError{Name: "entity", err: fmt.Errorf(`ent: validator failed for field "UserFieldPermission.entity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AllowMask(); !ok {
		return &ValidationError{Name: "allow_mask", err: errors.New(`ent: missing required field "UserFieldPermission.allow_mask"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "UserFieldPermission.updated"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserFieldPermission.user"`)}
	}
	return nil
}

func (_c *UserFieldPermissionCreate) sqlSave(ctx context.Context) (*UserFieldPermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserFieldPermissionCreate) createSpec() (*UserFieldPermission, *sqlgraph.CreateSpec) {
	var (
		_node = &UserFieldPermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userfieldpermission.Table, sqlgraph.NewFieldSpec(userfieldpermission.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Entity(); ok {
		_spec.SetField(userfieldpermission.FieldEntity, field.TypeEnum, value)
		_node.Entity = value
	}
	if value, ok := _c.mutation.AllowMask(); ok {
		_spec.SetField(userfieldpermission.FieldAllowMask, field.TypeInt64, value)
		_node.AllowMask = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(userfieldpermission.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(userfieldpermission.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfieldpermission.UserTable,
			Columns: []string{userfieldpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserFieldPermission.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserFieldPermissionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserFieldPermissionCreate) OnConflict(opts ...sql.ConflictOption) *UserFieldPermissionUpsertOne {
	_c.conflict = opts
	return &UserFieldPermissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserFieldPermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserFieldPermissionCreate) OnConflictColumns(columns ...string) *UserFieldPermissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserFieldPermissionUpsertOne{
		create: _c,
	}
}

type (
	// UserFieldPermissionUpsertOne is the builder for "upsert"-ing
	//  one UserFieldPermission node.
	UserFieldPermissionUpsertOne struct {
		create *UserFieldPermissionCreate
	}

	// UserFieldPermissionUpsert is the "OnConflict" setter.
	UserFieldPermissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserFieldPermissionUpsert) SetUserID(v int) *UserFieldPermissionUpsert {
	u.Set(userfieldpermission.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserFieldPermissionUpsert) UpdateUserID() *UserFieldPermissionUpsert {
	u.SetExcluded(userfieldpermission.FieldUserID)
	return u
}

// SetEntity sets the "entity" field.
func (u *UserFieldPermissionUpsert) SetEntity(v userfieldpermission.Entity) *UserFieldPermissionUpsert {
	u.Set(userfieldpermission.FieldEntity, v)
	return u
}

// UpdateEntity sets the "entity" field to the value that was provided on create.
func (u *UserFieldPermissionUpsert) UpdateEntity() *UserFieldPermissionUpsert {
	u.SetExcluded(userfieldpermission.FieldEntity)
	return u
}

// SetAllowMask sets the "allow_mask" field.
func (u *UserFieldPermissionUpsert) SetAllowMask(v int64) *UserFieldPermissionUpsert {
	u.Set(userfieldpermission.FieldAllowMask, v)
	return u
}

// UpdateAllowMask sets the "allow_mask" field to the value that was provided on create.
func (u *UserFieldPermissionUpsert) UpdateAllowMask() *UserFieldPermissionUpsert {
	u.SetExcluded(userfieldpermission.FieldAllowMask)
	return u
}

// AddAllowMask adds v to the "allow_mask" field.
func (u *UserFieldPermissionUpsert) AddAllowMask(v int64) *UserFieldPermissionUpsert {
	u.Add(userfieldpermission.FieldAllowMask, v)
	return u
}

// SetUpdated sets the "updated" field.
func (u *UserFieldPermissionUpsert) SetUpdated(v time.Time) *UserFieldPermissionUpsert {
	u.Set(userfieldpermission.FieldUpdated, v)
	return u
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *UserFieldPermissionUpsert) UpdateUpdated() *UserFieldPermissionUpsert {
	u.SetExcluded(userfieldpermission.FieldUpdated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserFieldPermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userfieldpermission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserFieldPermissionUpsertOne) UpdateNewValues() *UserFieldPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(userfieldpermission.FieldID)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(userfieldpermission.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserFieldPermission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserFieldPermissionUpsertOne) Ignore() *UserFieldPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserFieldPermissionUpsertOne) DoNothing() *UserFieldPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserFieldPermissionCreate.OnConflict
// documentation for more info.
func (u *UserFieldPermissionUpsertOne) Update(set func(*UserFieldPermissionUpsert)) *UserFieldPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserFieldPermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserFieldPermissionUpsertOne) SetUserID(v int) *UserFieldPermissionUpsertOne {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserFieldPermissionUpsertOne) UpdateUserID() *UserFieldPermissionUpsertOne {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.UpdateUserID()
	})
}

// SetEntity sets the "entity" field.
func (u *UserFieldPermissionUpsertOne) SetEntity(v userfieldpermission.Entity) *UserFieldPermissionUpsertOne {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.SetEntity(v)
	})
}

// UpdateEntity sets the "entity" field to the value that was provided on create.
func (u *UserFieldPermissionUpsertOne) UpdateEntity() *UserFieldPermissionUpsertOne {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.UpdateEntity()
	})
}

// SetAllowMask sets the "allow_mask" field.
func (u *UserFieldPermissionUpsertOne) SetAllowMask(v int64) *UserFieldPermissionUpsertOne {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.SetAllowMask(v)
	})
}

// AddAllowMask adds v to the "allow_mask" field.
func (u *UserFieldPermissionUpsertOne) AddAllowMask(v int64) *UserFieldPermissionUpsertOne {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.AddAllowMask(v)
	})
}

// UpdateAllowMask sets the "allow_mask" field to the value that was provided on create.
func (u *UserFieldPermissionUpsertOne) UpdateAllowMask() *UserFieldPermissionUpsertOne {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.UpdateAllowMask()
	})
}

// SetUpdated sets the "updated" field.
func (u *UserFieldPermissionUpsertOne) SetUpdated(v time.Time) *UserFieldPermissionUpsertOne {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *UserFieldPermissionUpsertOne) UpdateUpdated() *UserFieldPermissionUpsertOne {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *UserFieldPermissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserFieldPermissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserFieldPermissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserFieldPermissionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserFieldPermissionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserFieldPermissionCreateBulk is the builder for creating many UserFieldPermission entities in bulk.
type UserFieldPermissionCreateBulk struct {
	config
	err      error
	builders []*UserFieldPermissionCreate
	conflict []sql.ConflictOption
}

// Save creates the UserFieldPermission entities in the database.
func (_c *UserFieldPermissionCreateBulk) Save(ctx context.Context) ([]*UserFieldPermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserFieldPermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserFieldPermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserFieldPermissionCreateBulk) SaveX(ctx context.Context) []*UserFieldPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserFieldPermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserFieldPermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserFieldPermission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserFieldPermissionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserFieldPermissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserFieldPermissionUpsertBulk {
	_c.conflict = opts
	return &UserFieldPermissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserFieldPermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserFieldPermissionCreateBulk) OnConflictColumns(columns ...string) *UserFieldPermissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserFieldPermissionUpsertBulk{
		create: _c,
	}
}

// UserFieldPermissionUpsertBulk is the builder for "upsert"-ing
// a bulk of UserFieldPermission nodes.
type UserFieldPermissionUpsertBulk struct {
	create *UserFieldPermissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserFieldPermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userfieldpermission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserFieldPermissionUpsertBulk) UpdateNewValues() *UserFieldPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(userfieldpermission.FieldID)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(userfieldpermission.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserFieldPermission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserFieldPermissionUpsertBulk) Ignore() *UserFieldPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserFieldPermissionUpsertBulk) DoNothing() *UserFieldPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserFieldPermissionCreateBulk.OnConflict
// documentation for more info.
func (u *UserFieldPermissionUpsertBulk) Update(set func(*UserFieldPermissionUpsert)) *UserFieldPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserFieldPermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserFieldPermissionUpsertBulk) SetUserID(v int) *UserFieldPermissionUpsertBulk {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserFieldPermissionUpsertBulk) UpdateUserID() *UserFieldPermissionUpsertBulk {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.UpdateUserID()
	})
}

// SetEntity sets the "entity" field.
func (u *UserFieldPermissionUpsertBulk) SetEntity(v userfieldpermission.Entity) *UserFieldPermissionUpsertBulk {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.SetEntity(v)
	})
}

// UpdateEntity sets the "entity" field to the value that was provided on create.
func (u *UserFieldPermissionUpsertBulk) UpdateEntity() *UserFieldPermissionUpsertBulk {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.UpdateEntity()
	})
}

// SetAllowMask sets the "allow_mask" field.
func (u *UserFieldPermissionUpsertBulk) SetAllowMask(v int64) *UserFieldPermissionUpsertBulk {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.SetAllowMask(v)
	})
}

// AddAllowMask adds v to the "allow_mask" field.
func (u *UserFieldPermissionUpsertBulk) AddAllowMask(v int64) *UserFieldPermissionUpsertBulk {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.AddAllowMask(v)
	})
}

// UpdateAllowMask sets the "allow_mask" field to the value that was provided on create.
func (u *UserFieldPermissionUpsertBulk) UpdateAllowMask() *UserFieldPermissionUpsertBulk {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.UpdateAllowMask()
	})
}

// SetUpdated sets the "updated" field.
func (u *UserFieldPermissionUpsertBulk) SetUpdated(v time.Time) *UserFieldPermissionUpsertBulk {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *UserFieldPermissionUpsertBulk) UpdateUpdated() *UserFieldPermissionUpsertBulk {
	return u.Update(func(s *UserFieldPermissionUpsert) {
		s.UpdateUpdated()
	})
}

// Exec executes the query.
func (u *UserFieldPermissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserFieldPermissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserFieldPermissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserFieldPermissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
