// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/gameuploadsession"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/predicate"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/useruploadquota"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/useruploadquotarecord"
)

// UserUploadQuotaRecordUpdate is the builder for updating UserUploadQuotaRecord entities.
type UserUploadQuotaRecordUpdate struct {
	config
	hooks     []Hook
	mutation  *UserUploadQuotaRecordMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserUploadQuotaRecordUpdate builder.
func (_u *UserUploadQuotaRecordUpdate) Where(ps ...predicate.UserUploadQuotaRecord) *UserUploadQuotaRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetField sets the "field" field.
func (_u *UserUploadQuotaRecordUpdate) SetField(v useruploadquotarecord.Field) *UserUploadQuotaRecordUpdate {
	_u.mutation.SetFieldField(v)
	return _u
}

// SetNillableField sets the "field" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdate) SetNillableField(v *useruploadquotarecord.Field) *UserUploadQuotaRecordUpdate {
	if v != nil {
		_u.SetField(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserUploadQuotaRecordUpdate) SetAmount(v int64) *UserUploadQuotaRecordUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdate) SetNillableAmount(v *int64) *UserUploadQuotaRecordUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserUploadQuotaRecordUpdate) AddAmount(v int64) *UserUploadQuotaRecordUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *UserUploadQuotaRecordUpdate) SetAction(v useruploadquotarecord.Action) *UserUploadQuotaRecordUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdate) SetNillableAction(v *useruploadquotarecord.Action) *UserUploadQuotaRecordUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetActionReason sets the "action_reason" field.
func (_u *UserUploadQuotaRecordUpdate) SetActionReason(v string) *UserUploadQuotaRecordUpdate {
	_u.mutation.SetActionReason(v)
	return _u
}

// SetNillableActionReason sets the "action_reason" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdate) SetNillableActionReason(v *string) *UserUploadQuotaRecordUpdate {
	if v != nil {
		_u.SetActionReason(*v)
	}
	return _u
}

// ClearActionReason clears the value of the "action_reason" field.
func (_u *UserUploadQuotaRecordUpdate) ClearActionReason() *UserUploadQuotaRecordUpdate {
	_u.mutation.ClearActionReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUploadQuotaRecordUpdate) SetStatus(v useruploadquotarecord.Status) *UserUploadQuotaRecordUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdate) SetNillableStatus(v *useruploadquotarecord.Status) *UserUploadQuotaRecordUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUploadSessionID sets the "upload_session_id" field.
func (_u *UserUploadQuotaRecordUpdate) SetUploadSessionID(v int) *UserUploadQuotaRecordUpdate {
	_u.mutation.SetUploadSessionID(v)
	return _u
}

// SetNillableUploadSessionID sets the "upload_session_id" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdate) SetNillableUploadSessionID(v *int) *UserUploadQuotaRecordUpdate {
	if v != nil {
		_u.SetUploadSessionID(*v)
	}
	return _u
}

// ClearUploadSessionID clears the value of the "upload_session_id" field.
func (_u *UserUploadQuotaRecordUpdate) ClearUploadSessionID() *UserUploadQuotaRecordUpdate {
	_u.mutation.ClearUploadSessionID()
	return _u
}

// SetUserUploadQuotaID sets the "user_upload_quota_id" field.
func (_u *UserUploadQuotaRecordUpdate) SetUserUploadQuotaID(v int) *UserUploadQuotaRecordUpdate {
	_u.mutation.SetUserUploadQuotaID(v)
	return _u
}

// SetNillableUserUploadQuotaID sets the "user_upload_quota_id" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdate) SetNillableUserUploadQuotaID(v *int) *UserUploadQuotaRecordUpdate {
	if v != nil {
		_u.SetUserUploadQuotaID(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *UserUploadQuotaRecordUpdate) SetUpdated(v time.Time) *UserUploadQuotaRecordUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetUploadSession sets the "upload_session" edge to the GameUploadSession entity.
func (_u *UserUploadQuotaRecordUpdate) SetUploadSession(v *GameUploadSession) *UserUploadQuotaRecordUpdate {
	return _u.SetUploadSessionID(v.ID)
}

// SetUserUploadQuota sets the "user_upload_quota" edge to the UserUploadQuota entity.
func (_u *UserUploadQuotaRecordUpdate) SetUserUploadQuota(v *UserUploadQuota) *UserUploadQuotaRecordUpdate {
	return _u.SetUserUploadQuotaID(v.ID)
}

// Mutation returns the UserUploadQuotaRecordMutation object of the builder.
func (_u *UserUploadQuotaRecordUpdate) Mutation() *UserUploadQuotaRecordMutation {
	return _u.mutation
}

// ClearUploadSession clears the "upload_session" edge to the GameUploadSession entity.
func (_u *UserUploadQuotaRecordUpdate) ClearUploadSession() *UserUploadQuotaRecordUpdate {
	_u.mutation.ClearUploadSession()
	return _u
}

// ClearUserUploadQuota clears the "user_upload_quota" edge to the UserUploadQuota entity.
func (_u *UserUploadQuotaRecordUpdate) ClearUserUploadQuota() *UserUploadQuotaRecordUpdate {
	_u.mutation.ClearUserUploadQuota()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUploadQuotaRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUploadQuotaRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUploadQuotaRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUploadQuotaRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUploadQuotaRecordUpdate) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := useruploadquotarecord.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUploadQuotaRecordUpdate) check() error {
	if v, ok := _u.mutation.GetField(); ok {
		if err := useruploadquotarecord.FieldValidator(v); err != nil {
			return &ValidationError{Name: "field", err: fmt.Errorf(`ent: validator failed for field "UserUploadQuotaRecord.field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := useruploadquotarecord.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "UserUploadQuotaRecord.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionReason(); ok {
		if err := useruploadquotarecord.ActionReasonValidator(v); err != nil {
			return &ValidationError{Name: "action_reason", err: fmt.Errorf(`ent: validator failed for field "UserUploadQuotaRecord.action_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := useruploadquotarecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserUploadQuotaRecord.status": %w`, err)}
		}
	}
	if _u.mutation.UserUploadQuotaCleared() && len(_u.mutation.UserUploadQuotaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserUploadQuotaRecord.user_upload_quota"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserUploadQuotaRecordUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserUploadQuotaRecordUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserUploadQuotaRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useruploadquotarecord.Table, useruploadquotarecord.Columns, sqlgraph.NewFieldSpec(useruploadquotarecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetField(); ok {
		_spec.SetField(useruploadquotarecord.FieldField, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(useruploadquotarecord.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(useruploadquotarecord.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(useruploadquotarecord.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ActionReason(); ok {
		_spec.SetField(useruploadquotarecord.FieldActionReason, field.TypeString, value)
	}
	if _u.mutation.ActionReasonCleared() {
		_spec.ClearField(useruploadquotarecord.FieldActionReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(useruploadquotarecord.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(useruploadquotarecord.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UploadSessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useruploadquotarecord.UploadSessionTable,
			Columns: []string{useruploadquotarecord.UploadSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameuploadsession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploadSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useruploadquotarecord.UploadSessionTable,
			Columns: []string{useruploadquotarecord.UploadSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameuploadsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserUploadQuotaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useruploadquotarecord.UserUploadQuotaTable,
			Columns: []string{useruploadquotarecord.UserUploadQuotaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useruploadquota.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserUploadQuotaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useruploadquotarecord.UserUploadQuotaTable,
			Columns: []string{useruploadquotarecord.UserUploadQuotaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useruploadquota.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useruploadquotarecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUploadQuotaRecordUpdateOne is the builder for updating a single UserUploadQuotaRecord entity.
type UserUploadQuotaRecordUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserUploadQuotaRecordMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetField sets the "field" field.
func (_u *UserUploadQuotaRecordUpdateOne) SetField(v useruploadquotarecord.Field) *UserUploadQuotaRecordUpdateOne {
	_u.mutation.SetFieldField(v)
	return _u
}

// SetNillableField sets the "field" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdateOne) SetNillableField(v *useruploadquotarecord.Field) *UserUploadQuotaRecordUpdateOne {
	if v != nil {
		_u.SetField(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserUploadQuotaRecordUpdateOne) SetAmount(v int64) *UserUploadQuotaRecordUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdateOne) SetNillableAmount(v *int64) *UserUploadQuotaRecordUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserUploadQuotaRecordUpdateOne) AddAmount(v int64) *UserUploadQuotaRecordUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *UserUploadQuotaRecordUpdateOne) SetAction(v useruploadquotarecord.Action) *UserUploadQuotaRecordUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdateOne) SetNillableAction(v *useruploadquotarecord.Action) *UserUploadQuotaRecordUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetActionReason sets the "action_reason" field.
func (_u *UserUploadQuotaRecordUpdateOne) SetActionReason(v string) *UserUploadQuotaRecordUpdateOne {
	_u.mutation.SetActionReason(v)
	return _u
}

// SetNillableActionReason sets the "action_reason" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdateOne) SetNillableActionReason(v *string) *UserUploadQuotaRecordUpdateOne {
	if v != nil {
		_u.SetActionReason(*v)
	}
	return _u
}

// ClearActionReason clears the value of the "action_reason" field.
func (_u *UserUploadQuotaRecordUpdateOne) ClearActionReason() *UserUploadQuotaRecordUpdateOne {
	_u.mutation.ClearActionReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUploadQuotaRecordUpdateOne) SetStatus(v useruploadquotarecord.Status) *UserUploadQuotaRecordUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdateOne) SetNillableStatus(v *useruploadquotarecord.Status) *UserUploadQuotaRecordUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUploadSessionID sets the "upload_session_id" field.
func (_u *UserUploadQuotaRecordUpdateOne) SetUploadSessionID(v int) *UserUploadQuotaRecordUpdateOne {
	_u.mutation.SetUploadSessionID(v)
	return _u
}

// SetNillableUploadSessionID sets the "upload_session_id" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdateOne) SetNillableUploadSessionID(v *int) *UserUploadQuotaRecordUpdateOne {
	if v != nil {
		_u.SetUploadSessionID(*v)
	}
	return _u
}

// ClearUploadSessionID clears the value of the "upload_session_id" field.
func (_u *UserUploadQuotaRecordUpdateOne) ClearUploadSessionID() *UserUploadQuotaRecordUpdateOne {
	_u.mutation.ClearUploadSessionID()
	return _u
}

// SetUserUploadQuotaID sets the "user_upload_quota_id" field.
func (_u *UserUploadQuotaRecordUpdateOne) SetUserUploadQuotaID(v int) *UserUploadQuotaRecordUpdateOne {
	_u.mutation.SetUserUploadQuotaID(v)
	return _u
}

// SetNillableUserUploadQuotaID sets the "user_upload_quota_id" field if the given value is not nil.
func (_u *UserUploadQuotaRecordUpdateOne) SetNillableUserUploadQuotaID(v *int) *UserUploadQuotaRecordUpdateOne {
	if v != nil {
		_u.SetUserUploadQuotaID(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *UserUploadQuotaRecordUpdateOne) SetUpdated(v time.Time) *UserUploadQuotaRecordUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetUploadSession sets the "upload_session" edge to the GameUploadSession entity.
func (_u *UserUploadQuotaRecordUpdateOne) SetUploadSession(v *GameUploadSession) *UserUploadQuotaRecordUpdateOne {
	return _u.SetUploadSessionID(v.ID)
}

// SetUserUploadQuota sets the "user_upload_quota" edge to the UserUploadQuota entity.
func (_u *UserUploadQuotaRecordUpdateOne) SetUserUploadQuota(v *UserUploadQuota) *UserUploadQuotaRecordUpdateOne {
	return _u.SetUserUploadQuotaID(v.ID)
}

// Mutation returns the UserUploadQuotaRecordMutation object of the builder.
func (_u *UserUploadQuotaRecordUpdateOne) Mutation() *UserUploadQuotaRecordMutation {
	return _u.mutation
}

// ClearUploadSession clears the "upload_session" edge to the GameUploadSession entity.
func (_u *UserUploadQuotaRecordUpdateOne) ClearUploadSession() *UserUploadQuotaRecordUpdateOne {
	_u.mutation.ClearUploadSession()
	return _u
}

// ClearUserUploadQuota clears the "user_upload_quota" edge to the UserUploadQuota entity.
func (_u *UserUploadQuotaRecordUpdateOne) ClearUserUploadQuota() *UserUploadQuotaRecordUpdateOne {
	_u.mutation.ClearUserUploadQuota()
	return _u
}

// Where appends a list predicates to the UserUploadQuotaRecordUpdate builder.
func (_u *UserUploadQuotaRecordUpdateOne) Where(ps ...predicate.UserUploadQuotaRecord) *UserUploadQuotaRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUploadQuotaRecordUpdateOne) Select(field string, fields ...string) *UserUploadQuotaRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserUploadQuotaRecord entity.
func (_u *UserUploadQuotaRecordUpdateOne) Save(ctx context.Context) (*UserUploadQuotaRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUploadQuotaRecordUpdateOne) SaveX(ctx context.Context) *UserUploadQuotaRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUploadQuotaRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUploadQuotaRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUploadQuotaRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.Updated(); !ok {
		v := useruploadquotarecord.UpdateDefaultUpdated()
		_u.mutation.SetUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUploadQuotaRecordUpdateOne) check() error {
	if v, ok := _u.mutation.GetField(); ok {
		if err := useruploadquotarecord.FieldValidator(v); err != nil {
			return &ValidationError{Name: "field", err: fmt.Errorf(`ent: validator failed for field "UserUploadQuotaRecord.field": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := useruploadquotarecord.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "UserUploadQuotaRecord.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionReason(); ok {
		if err := useruploadquotarecord.ActionReasonValidator(v); err != nil {
			return &ValidationError{Name: "action_reason", err: fmt.Errorf(`ent: validator failed for field "UserUploadQuotaRecord.action_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := useruploadquotarecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserUploadQuotaRecord.status": %w`, err)}
		}
	}
	if _u.mutation.UserUploadQuotaCleared() && len(_u.mutation.UserUploadQuotaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserUploadQuotaRecord.user_upload_quota"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserUploadQuotaRecordUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserUploadQuotaRecordUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserUploadQuotaRecordUpdateOne) sqlSave(ctx context.Context) (_node *UserUploadQuotaRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useruploadquotarecord.Table, useruploadquotarecord.Columns, sqlgraph.NewFieldSpec(useruploadquotarecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserUploadQuotaRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useruploadquotarecord.FieldID)
		for _, f := range fields {
			if !useruploadquotarecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useruploadquotarecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetField(); ok {
		_spec.SetField(useruploadquotarecord.FieldField, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(useruploadquotarecord.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(useruploadquotarecord.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(useruploadquotarecord.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ActionReason(); ok {
		_spec.SetField(useruploadquotarecord.FieldActionReason, field.TypeString, value)
	}
	if _u.mutation.ActionReasonCleared() {
		_spec.ClearField(useruploadquotarecord.FieldActionReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(useruploadquotarecord.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(useruploadquotarecord.FieldUpdated, field.TypeTime, value)
	}
	if _u.mutation.UploadSessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useruploadquotarecord.UploadSessionTable,
			Columns: []string{useruploadquotarecord.UploadSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameuploadsession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploadSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useruploadquotarecord.UploadSessionTable,
			Columns: []string{useruploadquotarecord.UploadSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameuploadsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserUploadQuotaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useruploadquotarecord.UserUploadQuotaTable,
			Columns: []string{useruploadquotarecord.UserUploadQuotaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useruploadquota.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserUploadQuotaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useruploadquotarecord.UserUploadQuotaTable,
			Columns: []string{useruploadquotarecord.UserUploadQuotaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useruploadquota.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserUploadQuotaRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useruploadquotarecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
