// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent"
)

// The ActivityFunc type is an adapter to allow the use of ordinary
// function as Activity mutator.
type ActivityFunc func(context.Context, *ent.ActivityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ActivityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ActivityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ActivityMutation", m)
}

// The AdFunc type is an adapter to allow the use of ordinary
// function as Ad mutator.
type AdFunc func(context.Context, *ent.AdMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AdFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AdMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AdMutation", m)
}

// The CommentFunc type is an adapter to allow the use of ordinary
// function as Comment mutator.
type CommentFunc func(context.Context, *ent.CommentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommentMutation", m)
}

// The CommentLikeFunc type is an adapter to allow the use of ordinary
// function as CommentLike mutator.
type CommentLikeFunc func(context.Context, *ent.CommentLikeMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommentLikeFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommentLikeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommentLikeMutation", m)
}

// The EditRecordFunc type is an adapter to allow the use of ordinary
// function as EditRecord mutator.
type EditRecordFunc func(context.Context, *ent.EditRecordMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f EditRecordFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.EditRecordMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.EditRecordMutation", m)
}

// The FavoriteFunc type is an adapter to allow the use of ordinary
// function as Favorite mutator.
type FavoriteFunc func(context.Context, *ent.FavoriteMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FavoriteFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FavoriteMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FavoriteMutation", m)
}

// The FavoriteItemFunc type is an adapter to allow the use of ordinary
// function as FavoriteItem mutator.
type FavoriteItemFunc func(context.Context, *ent.FavoriteItemMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FavoriteItemFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FavoriteItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FavoriteItemMutation", m)
}

// The FieldPermissionMappingFunc type is an adapter to allow the use of ordinary
// function as FieldPermissionMapping mutator.
type FieldPermissionMappingFunc func(context.Context, *ent.FieldPermissionMappingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FieldPermissionMappingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FieldPermissionMappingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FieldPermissionMappingMutation", m)
}

// The GameFunc type is an adapter to allow the use of ordinary
// function as Game mutator.
type GameFunc func(context.Context, *ent.GameMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameMutation", m)
}

// The GameCharacterFunc type is an adapter to allow the use of ordinary
// function as GameCharacter mutator.
type GameCharacterFunc func(context.Context, *ent.GameCharacterMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameCharacterFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameCharacterMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameCharacterMutation", m)
}

// The GameCharacterRelationFunc type is an adapter to allow the use of ordinary
// function as GameCharacterRelation mutator.
type GameCharacterRelationFunc func(context.Context, *ent.GameCharacterRelationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameCharacterRelationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameCharacterRelationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameCharacterRelationMutation", m)
}

// The GameCoverFunc type is an adapter to allow the use of ordinary
// function as GameCover mutator.
type GameCoverFunc func(context.Context, *ent.GameCoverMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameCoverFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameCoverMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameCoverMutation", m)
}

// The GameDeveloperFunc type is an adapter to allow the use of ordinary
// function as GameDeveloper mutator.
type GameDeveloperFunc func(context.Context, *ent.GameDeveloperMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameDeveloperFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameDeveloperMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameDeveloperMutation", m)
}

// The GameDeveloperRelationFunc type is an adapter to allow the use of ordinary
// function as GameDeveloperRelation mutator.
type GameDeveloperRelationFunc func(context.Context, *ent.GameDeveloperRelationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameDeveloperRelationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameDeveloperRelationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameDeveloperRelationMutation", m)
}

// The GameDownloadResourceFunc type is an adapter to allow the use of ordinary
// function as GameDownloadResource mutator.
type GameDownloadResourceFunc func(context.Context, *ent.GameDownloadResourceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameDownloadResourceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameDownloadResourceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameDownloadResourceMutation", m)
}

// The GameDownloadResourceFileFunc type is an adapter to allow the use of ordinary
// function as GameDownloadResourceFile mutator.
type GameDownloadResourceFileFunc func(context.Context, *ent.GameDownloadResourceFileMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameDownloadResourceFileFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameDownloadResourceFileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameDownloadResourceFileMutation", m)
}

// The GameDownloadResourceFileHistoryFunc type is an adapter to allow the use of ordinary
// function as GameDownloadResourceFileHistory mutator.
type GameDownloadResourceFileHistoryFunc func(context.Context, *ent.GameDownloadResourceFileHistoryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameDownloadResourceFileHistoryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameDownloadResourceFileHistoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameDownloadResourceFileHistoryMutation", m)
}

// The GameDownloadResourceReportFunc type is an adapter to allow the use of ordinary
// function as GameDownloadResourceReport mutator.
type GameDownloadResourceReportFunc func(context.Context, *ent.GameDownloadResourceReportMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameDownloadResourceReportFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameDownloadResourceReportMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameDownloadResourceReportMutation", m)
}

// The GameImageFunc type is an adapter to allow the use of ordinary
// function as GameImage mutator.
type GameImageFunc func(context.Context, *ent.GameImageMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameImageFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameImageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameImageMutation", m)
}

// The GameLinkFunc type is an adapter to allow the use of ordinary
// function as GameLink mutator.
type GameLinkFunc func(context.Context, *ent.GameLinkMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameLinkFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameLinkMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameLinkMutation", m)
}

// The GameRelationFunc type is an adapter to allow the use of ordinary
// function as GameRelation mutator.
type GameRelationFunc func(context.Context, *ent.GameRelationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameRelationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameRelationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameRelationMutation", m)
}

// The GameTagRelationFunc type is an adapter to allow the use of ordinary
// function as GameTagRelation mutator.
type GameTagRelationFunc func(context.Context, *ent.GameTagRelationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameTagRelationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameTagRelationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameTagRelationMutation", m)
}

// The GameUploadChunkFunc type is an adapter to allow the use of ordinary
// function as GameUploadChunk mutator.
type GameUploadChunkFunc func(context.Context, *ent.GameUploadChunkMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameUploadChunkFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameUploadChunkMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameUploadChunkMutation", m)
}

// The GameUploadSessionFunc type is an adapter to allow the use of ordinary
// function as GameUploadSession mutator.
type GameUploadSessionFunc func(context.Context, *ent.GameUploadSessionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GameUploadSessionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GameUploadSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GameUploadSessionMutation", m)
}

// The MalwareScanCaseFunc type is an adapter to allow the use of ordinary
// function as MalwareScanCase mutator.
type MalwareScanCaseFunc func(context.Context, *ent.MalwareScanCaseMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MalwareScanCaseFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MalwareScanCaseMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MalwareScanCaseMutation", m)
}

// The MessageFunc type is an adapter to allow the use of ordinary
// function as Message mutator.
type MessageFunc func(context.Context, *ent.MessageMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MessageFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MessageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MessageMutation", m)
}

// The ModerationEventFunc type is an adapter to allow the use of ordinary
// function as ModerationEvent mutator.
type ModerationEventFunc func(context.Context, *ent.ModerationEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ModerationEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ModerationEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ModerationEventMutation", m)
}

// The OidcIdentityFunc type is an adapter to allow the use of ordinary
// function as OidcIdentity mutator.
type OidcIdentityFunc func(context.Context, *ent.OidcIdentityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OidcIdentityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OidcIdentityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OidcIdentityMutation", m)
}

// The RoleFieldPermissionFunc type is an adapter to allow the use of ordinary
// function as RoleFieldPermission mutator.
type RoleFieldPermissionFunc func(context.Context, *ent.RoleFieldPermissionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoleFieldPermissionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoleFieldPermissionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoleFieldPermissionMutation", m)
}

// The SponsorOrderFunc type is an adapter to allow the use of ordinary
// function as SponsorOrder mutator.
type SponsorOrderFunc func(context.Context, *ent.SponsorOrderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SponsorOrderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SponsorOrderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SponsorOrderMutation", m)
}

// The TagFunc type is an adapter to allow the use of ordinary
// function as Tag mutator.
type TagFunc func(context.Context, *ent.TagMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TagFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TagMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TagMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
}

// The UserBannedRecordFunc type is an adapter to allow the use of ordinary
// function as UserBannedRecord mutator.
type UserBannedRecordFunc func(context.Context, *ent.UserBannedRecordMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserBannedRecordFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserBannedRecordMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserBannedRecordMutation", m)
}

// The UserFieldPermissionFunc type is an adapter to allow the use of ordinary
// function as UserFieldPermission mutator.
type UserFieldPermissionFunc func(context.Context, *ent.UserFieldPermissionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFieldPermissionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserFieldPermissionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserFieldPermissionMutation", m)
}

// The UserGamePvnMappingFunc type is an adapter to allow the use of ordinary
// function as UserGamePvnMapping mutator.
type UserGamePvnMappingFunc func(context.Context, *ent.UserGamePvnMappingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserGamePvnMappingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserGamePvnMappingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserGamePvnMappingMutation", m)
}

// The UserLoginSessionFunc type is an adapter to allow the use of ordinary
// function as UserLoginSession mutator.
type UserLoginSessionFunc func(context.Context, *ent.UserLoginSessionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserLoginSessionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserLoginSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserLoginSessionMutation", m)
}

// The UserPasskeyCredentialFunc type is an adapter to allow the use of ordinary
// function as UserPasskeyCredential mutator.
type UserPasskeyCredentialFunc func(context.Context, *ent.UserPasskeyCredentialMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserPasskeyCredentialFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserPasskeyCredentialMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserPasskeyCredentialMutation", m)
}

// The UserPvnBindingFunc type is an adapter to allow the use of ordinary
// function as UserPvnBinding mutator.
type UserPvnBindingFunc func(context.Context, *ent.UserPvnBindingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserPvnBindingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserPvnBindingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserPvnBindingMutation", m)
}

// The UserUploadQuotaFunc type is an adapter to allow the use of ordinary
// function as UserUploadQuota mutator.
type UserUploadQuotaFunc func(context.Context, *ent.UserUploadQuotaMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserUploadQuotaFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserUploadQuotaMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserUploadQuotaMutation", m)
}

// The UserUploadQuotaRecordFunc type is an adapter to allow the use of ordinary
// function as UserUploadQuotaRecord mutator.
type UserUploadQuotaRecordFunc func(context.Context, *ent.UserUploadQuotaRecordMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserUploadQuotaRecordFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserUploadQuotaRecordMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserUploadQuotaRecordMutation", m)
}

// The WalkthroughFunc type is an adapter to allow the use of ordinary
// function as Walkthrough mutator.
type WalkthroughFunc func(context.Context, *ent.WalkthroughMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WalkthroughFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WalkthroughMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WalkthroughMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
