// Code generated by ent, DO NOT EDIT.

package gamedownloadresourcefilehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLTE(FieldID, id))
}

// FileID applies equality check predicate on the "file_id" field. It's identical to FileIDEQ.
func FileID(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldFileID, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int64) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldFileSize, v))
}

// FileHash applies equality check predicate on the "file_hash" field. It's identical to FileHashEQ.
func FileHash(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldFileHash, v))
}

// S3FileKey applies equality check predicate on the "s3_file_key" field. It's identical to S3FileKeyEQ.
func S3FileKey(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldS3FileKey, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldReason, v))
}

// UploadSessionID applies equality check predicate on the "upload_session_id" field. It's identical to UploadSessionIDEQ.
func UploadSessionID(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldUploadSessionID, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldOperatorID, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldCreated, v))
}

// FileIDEQ applies the EQ predicate on the "file_id" field.
func FileIDEQ(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldFileID, v))
}

// FileIDNEQ applies the NEQ predicate on the "file_id" field.
func FileIDNEQ(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNEQ(FieldFileID, v))
}

// FileIDIn applies the In predicate on the "file_id" field.
func FileIDIn(vs ...int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIn(FieldFileID, vs...))
}

// FileIDNotIn applies the NotIn predicate on the "file_id" field.
func FileIDNotIn(vs ...int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotIn(FieldFileID, vs...))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int64) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int64) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int64) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int64) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int64) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int64) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int64) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int64) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLTE(FieldFileSize, v))
}

// HashAlgorithmEQ applies the EQ predicate on the "hash_algorithm" field.
func HashAlgorithmEQ(v HashAlgorithm) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldHashAlgorithm, v))
}

// HashAlgorithmNEQ applies the NEQ predicate on the "hash_algorithm" field.
func HashAlgorithmNEQ(v HashAlgorithm) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNEQ(FieldHashAlgorithm, v))
}

// HashAlgorithmIn applies the In predicate on the "hash_algorithm" field.
func HashAlgorithmIn(vs ...HashAlgorithm) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIn(FieldHashAlgorithm, vs...))
}

// HashAlgorithmNotIn applies the NotIn predicate on the "hash_algorithm" field.
func HashAlgorithmNotIn(vs ...HashAlgorithm) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotIn(FieldHashAlgorithm, vs...))
}

// FileHashEQ applies the EQ predicate on the "file_hash" field.
func FileHashEQ(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldFileHash, v))
}

// FileHashNEQ applies the NEQ predicate on the "file_hash" field.
func FileHashNEQ(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNEQ(FieldFileHash, v))
}

// FileHashIn applies the In predicate on the "file_hash" field.
func FileHashIn(vs ...string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIn(FieldFileHash, vs...))
}

// FileHashNotIn applies the NotIn predicate on the "file_hash" field.
func FileHashNotIn(vs ...string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotIn(FieldFileHash, vs...))
}

// FileHashGT applies the GT predicate on the "file_hash" field.
func FileHashGT(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGT(FieldFileHash, v))
}

// FileHashGTE applies the GTE predicate on the "file_hash" field.
func FileHashGTE(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGTE(FieldFileHash, v))
}

// FileHashLT applies the LT predicate on the "file_hash" field.
func FileHashLT(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLT(FieldFileHash, v))
}

// FileHashLTE applies the LTE predicate on the "file_hash" field.
func FileHashLTE(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLTE(FieldFileHash, v))
}

// FileHashContains applies the Contains predicate on the "file_hash" field.
func FileHashContains(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldContains(FieldFileHash, v))
}

// FileHashHasPrefix applies the HasPrefix predicate on the "file_hash" field.
func FileHashHasPrefix(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldHasPrefix(FieldFileHash, v))
}

// FileHashHasSuffix applies the HasSuffix predicate on the "file_hash" field.
func FileHashHasSuffix(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldHasSuffix(FieldFileHash, v))
}

// FileHashEqualFold applies the EqualFold predicate on the "file_hash" field.
func FileHashEqualFold(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEqualFold(FieldFileHash, v))
}

// FileHashContainsFold applies the ContainsFold predicate on the "file_hash" field.
func FileHashContainsFold(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldContainsFold(FieldFileHash, v))
}

// S3FileKeyEQ applies the EQ predicate on the "s3_file_key" field.
func S3FileKeyEQ(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldS3FileKey, v))
}

// S3FileKeyNEQ applies the NEQ predicate on the "s3_file_key" field.
func S3FileKeyNEQ(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNEQ(FieldS3FileKey, v))
}

// S3FileKeyIn applies the In predicate on the "s3_file_key" field.
func S3FileKeyIn(vs ...string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIn(FieldS3FileKey, vs...))
}

// S3FileKeyNotIn applies the NotIn predicate on the "s3_file_key" field.
func S3FileKeyNotIn(vs ...string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotIn(FieldS3FileKey, vs...))
}

// S3FileKeyGT applies the GT predicate on the "s3_file_key" field.
func S3FileKeyGT(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGT(FieldS3FileKey, v))
}

// S3FileKeyGTE applies the GTE predicate on the "s3_file_key" field.
func S3FileKeyGTE(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGTE(FieldS3FileKey, v))
}

// S3FileKeyLT applies the LT predicate on the "s3_file_key" field.
func S3FileKeyLT(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLT(FieldS3FileKey, v))
}

// S3FileKeyLTE applies the LTE predicate on the "s3_file_key" field.
func S3FileKeyLTE(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLTE(FieldS3FileKey, v))
}

// S3FileKeyContains applies the Contains predicate on the "s3_file_key" field.
func S3FileKeyContains(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldContains(FieldS3FileKey, v))
}

// S3FileKeyHasPrefix applies the HasPrefix predicate on the "s3_file_key" field.
func S3FileKeyHasPrefix(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldHasPrefix(FieldS3FileKey, v))
}

// S3FileKeyHasSuffix applies the HasSuffix predicate on the "s3_file_key" field.
func S3FileKeyHasSuffix(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldHasSuffix(FieldS3FileKey, v))
}

// S3FileKeyIsNil applies the IsNil predicate on the "s3_file_key" field.
func S3FileKeyIsNil() predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIsNull(FieldS3FileKey))
}

// S3FileKeyNotNil applies the NotNil predicate on the "s3_file_key" field.
func S3FileKeyNotNil() predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotNull(FieldS3FileKey))
}

// S3FileKeyEqualFold applies the EqualFold predicate on the "s3_file_key" field.
func S3FileKeyEqualFold(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEqualFold(FieldS3FileKey, v))
}

// S3FileKeyContainsFold applies the ContainsFold predicate on the "s3_file_key" field.
func S3FileKeyContainsFold(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldContainsFold(FieldS3FileKey, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldContainsFold(FieldReason, v))
}

// UploadSessionIDEQ applies the EQ predicate on the "upload_session_id" field.
func UploadSessionIDEQ(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldUploadSessionID, v))
}

// UploadSessionIDNEQ applies the NEQ predicate on the "upload_session_id" field.
func UploadSessionIDNEQ(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNEQ(FieldUploadSessionID, v))
}

// UploadSessionIDIn applies the In predicate on the "upload_session_id" field.
func UploadSessionIDIn(vs ...int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIn(FieldUploadSessionID, vs...))
}

// UploadSessionIDNotIn applies the NotIn predicate on the "upload_session_id" field.
func UploadSessionIDNotIn(vs ...int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotIn(FieldUploadSessionID, vs...))
}

// UploadSessionIDGT applies the GT predicate on the "upload_session_id" field.
func UploadSessionIDGT(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGT(FieldUploadSessionID, v))
}

// UploadSessionIDGTE applies the GTE predicate on the "upload_session_id" field.
func UploadSessionIDGTE(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGTE(FieldUploadSessionID, v))
}

// UploadSessionIDLT applies the LT predicate on the "upload_session_id" field.
func UploadSessionIDLT(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLT(FieldUploadSessionID, v))
}

// UploadSessionIDLTE applies the LTE predicate on the "upload_session_id" field.
func UploadSessionIDLTE(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLTE(FieldUploadSessionID, v))
}

// UploadSessionIDIsNil applies the IsNil predicate on the "upload_session_id" field.
func UploadSessionIDIsNil() predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIsNull(FieldUploadSessionID))
}

// UploadSessionIDNotNil applies the NotNil predicate on the "upload_session_id" field.
func UploadSessionIDNotNil() predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotNull(FieldUploadSessionID))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotIn(FieldOperatorID, vs...))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.FieldLTE(FieldCreated, v))
}

// HasFile applies the HasEdge predicate on the "file" edge.
func HasFile() predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FileTable, FileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFileWith applies the HasEdge predicate on the "file" edge with a given conditions (other predicates).
func HasFileWith(preds ...predicate.GameDownloadResourceFile) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(func(s *sql.Selector) {
		step := newFileStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOperator applies the HasEdge predicate on the "operator" edge.
func HasOperator() predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OperatorTable, OperatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOperatorWith applies the HasEdge predicate on the "operator" edge with a given conditions (other predicates).
func HasOperatorWith(preds ...predicate.User) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(func(s *sql.Selector) {
		step := newOperatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GameDownloadResourceFileHistory) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GameDownloadResourceFileHistory) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GameDownloadResourceFileHistory) predicate.GameDownloadResourceFileHistory {
	return predicate.GameDownloadResourceFileHistory(sql.NotPredicates(p))
}
