// Code generated by ent, DO NOT EDIT.

package fieldpermissionmapping

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldLTE(FieldID, id))
}

// Field applies equality check predicate on the "field" field. It's identical to FieldEQ.
func Field(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldField, v))
}

// BitIndex applies equality check predicate on the "bit_index" field. It's identical to BitIndexEQ.
func BitIndex(v int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldBitIndex, v))
}

// IsRelation applies equality check predicate on the "is_relation" field. It's identical to IsRelationEQ.
func IsRelation(v bool) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldIsRelation, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldCreated, v))
}

// Updated applies equality check predicate on the "updated" field. It's identical to UpdatedEQ.
func Updated(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldUpdated, v))
}

// EntityEQ applies the EQ predicate on the "entity" field.
func EntityEQ(v Entity) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldEntity, v))
}

// EntityNEQ applies the NEQ predicate on the "entity" field.
func EntityNEQ(v Entity) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNEQ(FieldEntity, v))
}

// EntityIn applies the In predicate on the "entity" field.
func EntityIn(vs ...Entity) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldIn(FieldEntity, vs...))
}

// EntityNotIn applies the NotIn predicate on the "entity" field.
func EntityNotIn(vs ...Entity) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNotIn(FieldEntity, vs...))
}

// FieldEQ applies the EQ predicate on the "field" field.
func FieldEQ(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldField, v))
}

// FieldNEQ applies the NEQ predicate on the "field" field.
func FieldNEQ(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNEQ(FieldField, v))
}

// FieldIn applies the In predicate on the "field" field.
func FieldIn(vs ...string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldIn(FieldField, vs...))
}

// FieldNotIn applies the NotIn predicate on the "field" field.
func FieldNotIn(vs ...string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNotIn(FieldField, vs...))
}

// FieldGT applies the GT predicate on the "field" field.
func FieldGT(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldGT(FieldField, v))
}

// FieldGTE applies the GTE predicate on the "field" field.
func FieldGTE(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldGTE(FieldField, v))
}

// FieldLT applies the LT predicate on the "field" field.
func FieldLT(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldLT(FieldField, v))
}

// FieldLTE applies the LTE predicate on the "field" field.
func FieldLTE(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldLTE(FieldField, v))
}

// FieldContains applies the Contains predicate on the "field" field.
func FieldContains(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldContains(FieldField, v))
}

// FieldHasPrefix applies the HasPrefix predicate on the "field" field.
func FieldHasPrefix(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldHasPrefix(FieldField, v))
}

// FieldHasSuffix applies the HasSuffix predicate on the "field" field.
func FieldHasSuffix(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldHasSuffix(FieldField, v))
}

// FieldEqualFold applies the EqualFold predicate on the "field" field.
func FieldEqualFold(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEqualFold(FieldField, v))
}

// FieldContainsFold applies the ContainsFold predicate on the "field" field.
func FieldContainsFold(v string) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldContainsFold(FieldField, v))
}

// BitIndexEQ applies the EQ predicate on the "bit_index" field.
func BitIndexEQ(v int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldBitIndex, v))
}

// BitIndexNEQ applies the NEQ predicate on the "bit_index" field.
func BitIndexNEQ(v int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNEQ(FieldBitIndex, v))
}

// BitIndexIn applies the In predicate on the "bit_index" field.
func BitIndexIn(vs ...int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldIn(FieldBitIndex, vs...))
}

// BitIndexNotIn applies the NotIn predicate on the "bit_index" field.
func BitIndexNotIn(vs ...int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNotIn(FieldBitIndex, vs...))
}

// BitIndexGT applies the GT predicate on the "bit_index" field.
func BitIndexGT(v int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldGT(FieldBitIndex, v))
}

// BitIndexGTE applies the GTE predicate on the "bit_index" field.
func BitIndexGTE(v int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldGTE(FieldBitIndex, v))
}

// BitIndexLT applies the LT predicate on the "bit_index" field.
func BitIndexLT(v int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldLT(FieldBitIndex, v))
}

// BitIndexLTE applies the LTE predicate on the "bit_index" field.
func BitIndexLTE(v int) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldLTE(FieldBitIndex, v))
}

// IsRelationEQ applies the EQ predicate on the "is_relation" field.
func IsRelationEQ(v bool) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldIsRelation, v))
}

// IsRelationNEQ applies the NEQ predicate on the "is_relation" field.
func IsRelationNEQ(v bool) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNEQ(FieldIsRelation, v))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldLTE(FieldCreated, v))
}

// UpdatedEQ applies the EQ predicate on the "updated" field.
func UpdatedEQ(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldEQ(FieldUpdated, v))
}

// UpdatedNEQ applies the NEQ predicate on the "updated" field.
func UpdatedNEQ(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNEQ(FieldUpdated, v))
}

// UpdatedIn applies the In predicate on the "updated" field.
func UpdatedIn(vs ...time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldIn(FieldUpdated, vs...))
}

// UpdatedNotIn applies the NotIn predicate on the "updated" field.
func UpdatedNotIn(vs ...time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldNotIn(FieldUpdated, vs...))
}

// UpdatedGT applies the GT predicate on the "updated" field.
func UpdatedGT(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldGT(FieldUpdated, v))
}

// UpdatedGTE applies the GTE predicate on the "updated" field.
func UpdatedGTE(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldGTE(FieldUpdated, v))
}

// UpdatedLT applies the LT predicate on the "updated" field.
func UpdatedLT(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldLT(FieldUpdated, v))
}

// UpdatedLTE applies the LTE predicate on the "updated" field.
func UpdatedLTE(v time.Time) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.FieldLTE(FieldUpdated, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FieldPermissionMapping) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FieldPermissionMapping) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FieldPermissionMapping) predicate.FieldPermissionMapping {
	return predicate.FieldPermissionMapping(sql.NotPredicates(p))
}
