// Code generated by ent, DO NOT EDIT.

package gamedownloadresourcereport

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the gamedownloadresourcereport type in the database.
	Label = "game_download_resource_report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldReporterID holds the string denoting the reporter_id field in the database.
	FieldReporterID = "reporter_id"
	// FieldReportedUserID holds the string denoting the reported_user_id field in the database.
	FieldReportedUserID = "reported_user_id"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMaliciousLevel holds the string denoting the malicious_level field in the database.
	FieldMaliciousLevel = "malicious_level"
	// FieldProcessedBy holds the string denoting the processed_by field in the database.
	FieldProcessedBy = "processed_by"
	// FieldProcessedAt holds the string denoting the processed_at field in the database.
	FieldProcessedAt = "processed_at"
	// FieldProcessNote holds the string denoting the process_note field in the database.
	FieldProcessNote = "process_note"
	// FieldReporterPenaltyApplied holds the string denoting the reporter_penalty_applied field in the database.
	FieldReporterPenaltyApplied = "reporter_penalty_applied"
	// FieldReportedPenaltyApplied holds the string denoting the reported_penalty_applied field in the database.
	FieldReportedPenaltyApplied = "reported_penalty_applied"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldUpdated holds the string denoting the updated field in the database.
	FieldUpdated = "updated"
	// EdgeResource holds the string denoting the resource edge name in mutations.
	EdgeResource = "resource"
	// EdgeReporter holds the string denoting the reporter edge name in mutations.
	EdgeReporter = "reporter"
	// EdgeReportedUser holds the string denoting the reported_user edge name in mutations.
	EdgeReportedUser = "reported_user"
	// EdgeProcessor holds the string denoting the processor edge name in mutations.
	EdgeProcessor = "processor"
	// Table holds the table name of the gamedownloadresourcereport in the database.
	Table = "game_download_resource_reports"
	// ResourceTable is the table that holds the resource relation/edge.
	ResourceTable = "game_download_resource_reports"
	// ResourceInverseTable is the table name for the GameDownloadResource entity.
	// It exists in this package in order to avoid circular dependency with the "gamedownloadresource" package.
	ResourceInverseTable = "game_download_resources"
	// ResourceColumn is the table column denoting the resource relation/edge.
	ResourceColumn = "resource_id"
	// ReporterTable is the table that holds the reporter relation/edge.
	ReporterTable = "game_download_resource_reports"
	// ReporterInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReporterInverseTable = "users"
	// ReporterColumn is the table column denoting the reporter relation/edge.
	ReporterColumn = "reporter_id"
	// ReportedUserTable is the table that holds the reported_user relation/edge.
	ReportedUserTable = "game_download_resource_reports"
	// ReportedUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReportedUserInverseTable = "users"
	// ReportedUserColumn is the table column denoting the reported_user relation/edge.
	ReportedUserColumn = "reported_user_id"
	// ProcessorTable is the table that holds the processor relation/edge.
	ProcessorTable = "game_download_resource_reports"
	// ProcessorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ProcessorInverseTable = "users"
	// ProcessorColumn is the table column denoting the processor relation/edge.
	ProcessorColumn = "processed_by"
)

// Columns holds all SQL columns for gamedownloadresourcereport fields.
var Columns = []string{
	FieldID,
	FieldResourceID,
	FieldReporterID,
	FieldReportedUserID,
	FieldReason,
	FieldDetail,
	FieldStatus,
	FieldMaliciousLevel,
	FieldProcessedBy,
	FieldProcessedAt,
	FieldProcessNote,
	FieldReporterPenaltyApplied,
	FieldReportedPenaltyApplied,
	FieldCreated,
	FieldUpdated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DetailValidator is a validator for the "detail" field. It is called by the builders before save.
	DetailValidator func(string) error
	// ProcessNoteValidator is a validator for the "process_note" field. It is called by the builders before save.
	ProcessNoteValidator func(string) error
	// DefaultReporterPenaltyApplied holds the default value on creation for the "reporter_penalty_applied" field.
	DefaultReporterPenaltyApplied bool
	// DefaultReportedPenaltyApplied holds the default value on creation for the "reported_penalty_applied" field.
	DefaultReportedPenaltyApplied bool
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
	// DefaultUpdated holds the default value on creation for the "updated" field.
	DefaultUpdated func() time.Time
	// UpdateDefaultUpdated holds the default value on update for the "updated" field.
	UpdateDefaultUpdated func() time.Time
)

// Reason defines the type for the "reason" enum field.
type Reason string

// Reason values.
const (
	ReasonMALWARE            Reason = "MALWARE"
	ReasonIRRELEVANT         Reason = "IRRELEVANT"
	ReasonBROKEN_LINK        Reason = "BROKEN_LINK"
	ReasonMISLEADING_CONTENT Reason = "MISLEADING_CONTENT"
	ReasonOTHER              Reason = "OTHER"
)

func (r Reason) String() string {
	return string(r)
}

// ReasonValidator is a validator for the "reason" field enum values. It is called by the builders before save.
func ReasonValidator(r Reason) error {
	switch r {
	case ReasonMALWARE, ReasonIRRELEVANT, ReasonBROKEN_LINK, ReasonMISLEADING_CONTENT, ReasonOTHER:
		return nil
	default:
		return fmt.Errorf("gamedownloadresourcereport: invalid enum value for reason field: %q", r)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING Status = "PENDING"
	StatusVALID   Status = "VALID"
	StatusINVALID Status = "INVALID"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusVALID, StatusINVALID:
		return nil
	default:
		return fmt.Errorf("gamedownloadresourcereport: invalid enum value for status field: %q", s)
	}
}

// MaliciousLevel defines the type for the "malicious_level" enum field.
type MaliciousLevel string

// MaliciousLevel values.
const (
	MaliciousLevelLOW      MaliciousLevel = "LOW"
	MaliciousLevelMEDIUM   MaliciousLevel = "MEDIUM"
	MaliciousLevelHIGH     MaliciousLevel = "HIGH"
	MaliciousLevelCRITICAL MaliciousLevel = "CRITICAL"
)

func (ml MaliciousLevel) String() string {
	return string(ml)
}

// MaliciousLevelValidator is a validator for the "malicious_level" field enum values. It is called by the builders before save.
func MaliciousLevelValidator(ml MaliciousLevel) error {
	switch ml {
	case MaliciousLevelLOW, MaliciousLevelMEDIUM, MaliciousLevelHIGH, MaliciousLevelCRITICAL:
		return nil
	default:
		return fmt.Errorf("gamedownloadresourcereport: invalid enum value for malicious_level field: %q", ml)
	}
}

// OrderOption defines the ordering options for the GameDownloadResourceReport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByReporterID orders the results by the reporter_id field.
func ByReporterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReporterID, opts...).ToFunc()
}

// ByReportedUserID orders the results by the reported_user_id field.
func ByReportedUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportedUserID, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByDetail orders the results by the detail field.
func ByDetail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetail, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMaliciousLevel orders the results by the malicious_level field.
func ByMaliciousLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaliciousLevel, opts...).ToFunc()
}

// ByProcessedBy orders the results by the processed_by field.
func ByProcessedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedBy, opts...).ToFunc()
}

// ByProcessedAt orders the results by the processed_at field.
func ByProcessedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedAt, opts...).ToFunc()
}

// ByProcessNote orders the results by the process_note field.
func ByProcessNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessNote, opts...).ToFunc()
}

// ByReporterPenaltyApplied orders the results by the reporter_penalty_applied field.
func ByReporterPenaltyApplied(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReporterPenaltyApplied, opts...).ToFunc()
}

// ByReportedPenaltyApplied orders the results by the reported_penalty_applied field.
func ByReportedPenaltyApplied(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportedPenaltyApplied, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}

// ByUpdated orders the results by the updated field.
func ByUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdated, opts...).ToFunc()
}

// ByResourceField orders the results by resource field.
func ByResourceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResourceStep(), sql.OrderByField(field, opts...))
	}
}

// ByReporterField orders the results by reporter field.
func ByReporterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReporterStep(), sql.OrderByField(field, opts...))
	}
}

// ByReportedUserField orders the results by reported_user field.
func ByReportedUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReportedUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByProcessorField orders the results by processor field.
func ByProcessorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProcessorStep(), sql.OrderByField(field, opts...))
	}
}
func newResourceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResourceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ResourceTable, ResourceColumn),
	)
}
func newReporterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReporterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReporterTable, ReporterColumn),
	)
}
func newReportedUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReportedUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReportedUserTable, ReportedUserColumn),
	)
}
func newProcessorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProcessorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProcessorTable, ProcessorColumn),
	)
}
