// Code generated by ent, DO NOT EDIT.

package airoute

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the airoute type in the database.
	Label = "ai_route"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldUpstreamID holds the string denoting the upstream_id field in the database.
	FieldUpstreamID = "upstream_id"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldPriceManual holds the string denoting the price_manual field in the database.
	FieldPriceManual = "price_manual"
	// FieldInputPrice holds the string denoting the input_price field in the database.
	FieldInputPrice = "input_price"
	// FieldOutputPrice holds the string denoting the output_price field in the database.
	FieldOutputPrice = "output_price"
	// FieldCacheReadPrice holds the string denoting the cache_read_price field in the database.
	FieldCacheReadPrice = "cache_read_price"
	// FieldCacheWritePrice holds the string denoting the cache_write_price field in the database.
	FieldCacheWritePrice = "cache_write_price"
	// FieldPriceTiers holds the string denoting the price_tiers field in the database.
	FieldPriceTiers = "price_tiers"
	// FieldDroppedParams holds the string denoting the dropped_params field in the database.
	FieldDroppedParams = "dropped_params"
	// FieldJSONMode holds the string denoting the json_mode field in the database.
	FieldJSONMode = "json_mode"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStatusKind holds the string denoting the status_kind field in the database.
	FieldStatusKind = "status_kind"
	// FieldStatusMessage holds the string denoting the status_message field in the database.
	FieldStatusMessage = "status_message"
	// FieldStatusAt holds the string denoting the status_at field in the database.
	FieldStatusAt = "status_at"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldUpdated holds the string denoting the updated field in the database.
	FieldUpdated = "updated"
	// EdgeModel holds the string denoting the model edge name in mutations.
	EdgeModel = "model"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// EdgeAdjustments holds the string denoting the adjustments edge name in mutations.
	EdgeAdjustments = "adjustments"
	// EdgeRequests holds the string denoting the requests edge name in mutations.
	EdgeRequests = "requests"
	// Table holds the table name of the airoute in the database.
	Table = "ai_routes"
	// ModelTable is the table that holds the model relation/edge.
	ModelTable = "ai_routes"
	// ModelInverseTable is the table name for the AIModel entity.
	// It exists in this package in order to avoid circular dependency with the "aimodel" package.
	ModelInverseTable = "ai_models"
	// ModelColumn is the table column denoting the model relation/edge.
	ModelColumn = "model_id"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "ai_routes"
	// ProviderInverseTable is the table name for the AIProvider entity.
	// It exists in this package in order to avoid circular dependency with the "aiprovider" package.
	ProviderInverseTable = "ai_providers"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_id"
	// AdjustmentsTable is the table that holds the adjustments relation/edge.
	AdjustmentsTable = "ai_route_adjustments"
	// AdjustmentsInverseTable is the table name for the AIRouteAdjustment entity.
	// It exists in this package in order to avoid circular dependency with the "airouteadjustment" package.
	AdjustmentsInverseTable = "ai_route_adjustments"
	// AdjustmentsColumn is the table column denoting the adjustments relation/edge.
	AdjustmentsColumn = "route_id"
	// RequestsTable is the table that holds the requests relation/edge.
	RequestsTable = "ai_requests"
	// RequestsInverseTable is the table name for the AIRequest entity.
	// It exists in this package in order to avoid circular dependency with the "airequest" package.
	RequestsInverseTable = "ai_requests"
	// RequestsColumn is the table column denoting the requests relation/edge.
	RequestsColumn = "route_id"
)

// Columns holds all SQL columns for airoute fields.
var Columns = []string{
	FieldID,
	FieldModelID,
	FieldProviderID,
	FieldUpstreamID,
	FieldProtocol,
	FieldPriceManual,
	FieldInputPrice,
	FieldOutputPrice,
	FieldCacheReadPrice,
	FieldCacheWritePrice,
	FieldPriceTiers,
	FieldDroppedParams,
	FieldJSONMode,
	FieldPriority,
	FieldStatus,
	FieldStatusKind,
	FieldStatusMessage,
	FieldStatusAt,
	FieldCreated,
	FieldUpdated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UpstreamIDValidator is a validator for the "upstream_id" field. It is called by the builders before save.
	UpstreamIDValidator func(string) error
	// ProtocolValidator is a validator for the "protocol" field. It is called by the builders before save.
	ProtocolValidator func(string) error
	// DefaultPriceManual holds the default value on creation for the "price_manual" field.
	DefaultPriceManual bool
	// DefaultInputPrice holds the default value on creation for the "input_price" field.
	DefaultInputPrice float64
	// DefaultOutputPrice holds the default value on creation for the "output_price" field.
	DefaultOutputPrice float64
	// DefaultJSONMode holds the default value on creation for the "json_mode" field.
	DefaultJSONMode bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// StatusKindValidator is a validator for the "status_kind" field. It is called by the builders before save.
	StatusKindValidator func(string) error
	// StatusMessageValidator is a validator for the "status_message" field. It is called by the builders before save.
	StatusMessageValidator func(string) error
	// DefaultCreated holds the default value on creation for the "created" field.
	DefaultCreated func() time.Time
	// DefaultUpdated holds the default value on creation for the "updated" field.
	DefaultUpdated func() time.Time
	// UpdateDefaultUpdated holds the default value on update for the "updated" field.
	UpdateDefaultUpdated func() time.Time
)

// OrderOption defines the ordering options for the AIRoute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByUpstreamID orders the results by the upstream_id field.
func ByUpstreamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamID, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByPriceManual orders the results by the price_manual field.
func ByPriceManual(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceManual, opts...).ToFunc()
}

// ByInputPrice orders the results by the input_price field.
func ByInputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputPrice, opts...).ToFunc()
}

// ByOutputPrice orders the results by the output_price field.
func ByOutputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputPrice, opts...).ToFunc()
}

// ByCacheReadPrice orders the results by the cache_read_price field.
func ByCacheReadPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadPrice, opts...).ToFunc()
}

// ByCacheWritePrice orders the results by the cache_write_price field.
func ByCacheWritePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheWritePrice, opts...).ToFunc()
}

// ByDroppedParams orders the results by the dropped_params field.
func ByDroppedParams(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDroppedParams, opts...).ToFunc()
}

// ByJSONMode orders the results by the json_mode field.
func ByJSONMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJSONMode, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStatusKind orders the results by the status_kind field.
func ByStatusKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusKind, opts...).ToFunc()
}

// ByStatusMessage orders the results by the status_message field.
func ByStatusMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusMessage, opts...).ToFunc()
}

// ByStatusAt orders the results by the status_at field.
func ByStatusAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusAt, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}

// ByUpdated orders the results by the updated field.
func ByUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdated, opts...).ToFunc()
}

// ByModelField orders the results by model field.
func ByModelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelStep(), sql.OrderByField(field, opts...))
	}
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}

// ByAdjustmentsCount orders the results by adjustments count.
func ByAdjustmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAdjustmentsStep(), opts...)
	}
}

// ByAdjustments orders the results by adjustments terms.
func ByAdjustments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdjustmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRequestsCount orders the results by requests count.
func ByRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRequestsStep(), opts...)
	}
}

// ByRequests orders the results by requests terms.
func ByRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newModelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModelTable, ModelColumn),
	)
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
	)
}
func newAdjustmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdjustmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AdjustmentsTable, AdjustmentsColumn),
	)
}
func newRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RequestsTable, RequestsColumn),
	)
}
