// Code generated by ent, DO NOT EDIT.

package gameuploadsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/ent/predicate"
	"github.com/Ringyuki/shionlib/apps/api/internal/adapter/postgres/pgvalue"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldID, id))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldFileName, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldMimeType, v))
}

// TotalSize applies equality check predicate on the "total_size" field. It's identical to TotalSizeEQ.
func TotalSize(v int64) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldTotalSize, v))
}

// ChunkSize applies equality check predicate on the "chunk_size" field. It's identical to ChunkSizeEQ.
func ChunkSize(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldChunkSize, v))
}

// TotalChunks applies equality check predicate on the "total_chunks" field. It's identical to TotalChunksEQ.
func TotalChunks(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldTotalChunks, v))
}

// UploadedChunks applies equality check predicate on the "uploaded_chunks" field. It's identical to UploadedChunksEQ.
func UploadedChunks(v pgvalue.Ints) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldUploadedChunks, v))
}

// FileSha256 applies equality check predicate on the "file_sha256" field. It's identical to FileSha256EQ.
func FileSha256(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldFileSha256, v))
}

// StoragePath applies equality check predicate on the "storage_path" field. It's identical to StoragePathEQ.
func StoragePath(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldStoragePath, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatorID applies equality check predicate on the "creator_id" field. It's identical to CreatorIDEQ.
func CreatorID(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldCreatorID, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldCreated, v))
}

// Updated applies equality check predicate on the "updated" field. It's identical to UpdatedEQ.
func Updated(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldUpdated, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldContainsFold(FieldFileName, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeIsNil applies the IsNil predicate on the "mime_type" field.
func MimeTypeIsNil() predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIsNull(FieldMimeType))
}

// MimeTypeNotNil applies the NotNil predicate on the "mime_type" field.
func MimeTypeNotNil() predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotNull(FieldMimeType))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldContainsFold(FieldMimeType, v))
}

// TotalSizeEQ applies the EQ predicate on the "total_size" field.
func TotalSizeEQ(v int64) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldTotalSize, v))
}

// TotalSizeNEQ applies the NEQ predicate on the "total_size" field.
func TotalSizeNEQ(v int64) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldTotalSize, v))
}

// TotalSizeIn applies the In predicate on the "total_size" field.
func TotalSizeIn(vs ...int64) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldTotalSize, vs...))
}

// TotalSizeNotIn applies the NotIn predicate on the "total_size" field.
func TotalSizeNotIn(vs ...int64) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldTotalSize, vs...))
}

// TotalSizeGT applies the GT predicate on the "total_size" field.
func TotalSizeGT(v int64) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldTotalSize, v))
}

// TotalSizeGTE applies the GTE predicate on the "total_size" field.
func TotalSizeGTE(v int64) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldTotalSize, v))
}

// TotalSizeLT applies the LT predicate on the "total_size" field.
func TotalSizeLT(v int64) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldTotalSize, v))
}

// TotalSizeLTE applies the LTE predicate on the "total_size" field.
func TotalSizeLTE(v int64) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldTotalSize, v))
}

// ChunkSizeEQ applies the EQ predicate on the "chunk_size" field.
func ChunkSizeEQ(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldChunkSize, v))
}

// ChunkSizeNEQ applies the NEQ predicate on the "chunk_size" field.
func ChunkSizeNEQ(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldChunkSize, v))
}

// ChunkSizeIn applies the In predicate on the "chunk_size" field.
func ChunkSizeIn(vs ...int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldChunkSize, vs...))
}

// ChunkSizeNotIn applies the NotIn predicate on the "chunk_size" field.
func ChunkSizeNotIn(vs ...int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldChunkSize, vs...))
}

// ChunkSizeGT applies the GT predicate on the "chunk_size" field.
func ChunkSizeGT(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldChunkSize, v))
}

// ChunkSizeGTE applies the GTE predicate on the "chunk_size" field.
func ChunkSizeGTE(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldChunkSize, v))
}

// ChunkSizeLT applies the LT predicate on the "chunk_size" field.
func ChunkSizeLT(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldChunkSize, v))
}

// ChunkSizeLTE applies the LTE predicate on the "chunk_size" field.
func ChunkSizeLTE(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldChunkSize, v))
}

// TotalChunksEQ applies the EQ predicate on the "total_chunks" field.
func TotalChunksEQ(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldTotalChunks, v))
}

// TotalChunksNEQ applies the NEQ predicate on the "total_chunks" field.
func TotalChunksNEQ(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldTotalChunks, v))
}

// TotalChunksIn applies the In predicate on the "total_chunks" field.
func TotalChunksIn(vs ...int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldTotalChunks, vs...))
}

// TotalChunksNotIn applies the NotIn predicate on the "total_chunks" field.
func TotalChunksNotIn(vs ...int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldTotalChunks, vs...))
}

// TotalChunksGT applies the GT predicate on the "total_chunks" field.
func TotalChunksGT(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldTotalChunks, v))
}

// TotalChunksGTE applies the GTE predicate on the "total_chunks" field.
func TotalChunksGTE(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldTotalChunks, v))
}

// TotalChunksLT applies the LT predicate on the "total_chunks" field.
func TotalChunksLT(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldTotalChunks, v))
}

// TotalChunksLTE applies the LTE predicate on the "total_chunks" field.
func TotalChunksLTE(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldTotalChunks, v))
}

// UploadedChunksEQ applies the EQ predicate on the "uploaded_chunks" field.
func UploadedChunksEQ(v pgvalue.Ints) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldUploadedChunks, v))
}

// UploadedChunksNEQ applies the NEQ predicate on the "uploaded_chunks" field.
func UploadedChunksNEQ(v pgvalue.Ints) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldUploadedChunks, v))
}

// UploadedChunksIn applies the In predicate on the "uploaded_chunks" field.
func UploadedChunksIn(vs ...pgvalue.Ints) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldUploadedChunks, vs...))
}

// UploadedChunksNotIn applies the NotIn predicate on the "uploaded_chunks" field.
func UploadedChunksNotIn(vs ...pgvalue.Ints) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldUploadedChunks, vs...))
}

// UploadedChunksGT applies the GT predicate on the "uploaded_chunks" field.
func UploadedChunksGT(v pgvalue.Ints) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldUploadedChunks, v))
}

// UploadedChunksGTE applies the GTE predicate on the "uploaded_chunks" field.
func UploadedChunksGTE(v pgvalue.Ints) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldUploadedChunks, v))
}

// UploadedChunksLT applies the LT predicate on the "uploaded_chunks" field.
func UploadedChunksLT(v pgvalue.Ints) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldUploadedChunks, v))
}

// UploadedChunksLTE applies the LTE predicate on the "uploaded_chunks" field.
func UploadedChunksLTE(v pgvalue.Ints) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldUploadedChunks, v))
}

// UploadedChunksIsNil applies the IsNil predicate on the "uploaded_chunks" field.
func UploadedChunksIsNil() predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIsNull(FieldUploadedChunks))
}

// UploadedChunksNotNil applies the NotNil predicate on the "uploaded_chunks" field.
func UploadedChunksNotNil() predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotNull(FieldUploadedChunks))
}

// HashAlgorithmEQ applies the EQ predicate on the "hash_algorithm" field.
func HashAlgorithmEQ(v HashAlgorithm) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldHashAlgorithm, v))
}

// HashAlgorithmNEQ applies the NEQ predicate on the "hash_algorithm" field.
func HashAlgorithmNEQ(v HashAlgorithm) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldHashAlgorithm, v))
}

// HashAlgorithmIn applies the In predicate on the "hash_algorithm" field.
func HashAlgorithmIn(vs ...HashAlgorithm) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldHashAlgorithm, vs...))
}

// HashAlgorithmNotIn applies the NotIn predicate on the "hash_algorithm" field.
func HashAlgorithmNotIn(vs ...HashAlgorithm) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldHashAlgorithm, vs...))
}

// FileSha256EQ applies the EQ predicate on the "file_sha256" field.
func FileSha256EQ(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldFileSha256, v))
}

// FileSha256NEQ applies the NEQ predicate on the "file_sha256" field.
func FileSha256NEQ(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldFileSha256, v))
}

// FileSha256In applies the In predicate on the "file_sha256" field.
func FileSha256In(vs ...string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldFileSha256, vs...))
}

// FileSha256NotIn applies the NotIn predicate on the "file_sha256" field.
func FileSha256NotIn(vs ...string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldFileSha256, vs...))
}

// FileSha256GT applies the GT predicate on the "file_sha256" field.
func FileSha256GT(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldFileSha256, v))
}

// FileSha256GTE applies the GTE predicate on the "file_sha256" field.
func FileSha256GTE(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldFileSha256, v))
}

// FileSha256LT applies the LT predicate on the "file_sha256" field.
func FileSha256LT(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldFileSha256, v))
}

// FileSha256LTE applies the LTE predicate on the "file_sha256" field.
func FileSha256LTE(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldFileSha256, v))
}

// FileSha256Contains applies the Contains predicate on the "file_sha256" field.
func FileSha256Contains(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldContains(FieldFileSha256, v))
}

// FileSha256HasPrefix applies the HasPrefix predicate on the "file_sha256" field.
func FileSha256HasPrefix(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldHasPrefix(FieldFileSha256, v))
}

// FileSha256HasSuffix applies the HasSuffix predicate on the "file_sha256" field.
func FileSha256HasSuffix(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldHasSuffix(FieldFileSha256, v))
}

// FileSha256EqualFold applies the EqualFold predicate on the "file_sha256" field.
func FileSha256EqualFold(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEqualFold(FieldFileSha256, v))
}

// FileSha256ContainsFold applies the ContainsFold predicate on the "file_sha256" field.
func FileSha256ContainsFold(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldContainsFold(FieldFileSha256, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StoragePathEQ applies the EQ predicate on the "storage_path" field.
func StoragePathEQ(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldStoragePath, v))
}

// StoragePathNEQ applies the NEQ predicate on the "storage_path" field.
func StoragePathNEQ(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldStoragePath, v))
}

// StoragePathIn applies the In predicate on the "storage_path" field.
func StoragePathIn(vs ...string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldStoragePath, vs...))
}

// StoragePathNotIn applies the NotIn predicate on the "storage_path" field.
func StoragePathNotIn(vs ...string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldStoragePath, vs...))
}

// StoragePathGT applies the GT predicate on the "storage_path" field.
func StoragePathGT(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldStoragePath, v))
}

// StoragePathGTE applies the GTE predicate on the "storage_path" field.
func StoragePathGTE(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldStoragePath, v))
}

// StoragePathLT applies the LT predicate on the "storage_path" field.
func StoragePathLT(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldStoragePath, v))
}

// StoragePathLTE applies the LTE predicate on the "storage_path" field.
func StoragePathLTE(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldStoragePath, v))
}

// StoragePathContains applies the Contains predicate on the "storage_path" field.
func StoragePathContains(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldContains(FieldStoragePath, v))
}

// StoragePathHasPrefix applies the HasPrefix predicate on the "storage_path" field.
func StoragePathHasPrefix(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldHasPrefix(FieldStoragePath, v))
}

// StoragePathHasSuffix applies the HasSuffix predicate on the "storage_path" field.
func StoragePathHasSuffix(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldHasSuffix(FieldStoragePath, v))
}

// StoragePathEqualFold applies the EqualFold predicate on the "storage_path" field.
func StoragePathEqualFold(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEqualFold(FieldStoragePath, v))
}

// StoragePathContainsFold applies the ContainsFold predicate on the "storage_path" field.
func StoragePathContainsFold(v string) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldContainsFold(FieldStoragePath, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatorIDEQ applies the EQ predicate on the "creator_id" field.
func CreatorIDEQ(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldCreatorID, v))
}

// CreatorIDNEQ applies the NEQ predicate on the "creator_id" field.
func CreatorIDNEQ(v int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldCreatorID, v))
}

// CreatorIDIn applies the In predicate on the "creator_id" field.
func CreatorIDIn(vs ...int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldCreatorID, vs...))
}

// CreatorIDNotIn applies the NotIn predicate on the "creator_id" field.
func CreatorIDNotIn(vs ...int) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldCreatorID, vs...))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldCreated, v))
}

// UpdatedEQ applies the EQ predicate on the "updated" field.
func UpdatedEQ(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldEQ(FieldUpdated, v))
}

// UpdatedNEQ applies the NEQ predicate on the "updated" field.
func UpdatedNEQ(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNEQ(FieldUpdated, v))
}

// UpdatedIn applies the In predicate on the "updated" field.
func UpdatedIn(vs ...time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldIn(FieldUpdated, vs...))
}

// UpdatedNotIn applies the NotIn predicate on the "updated" field.
func UpdatedNotIn(vs ...time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldNotIn(FieldUpdated, vs...))
}

// UpdatedGT applies the GT predicate on the "updated" field.
func UpdatedGT(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGT(FieldUpdated, v))
}

// UpdatedGTE applies the GTE predicate on the "updated" field.
func UpdatedGTE(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldGTE(FieldUpdated, v))
}

// UpdatedLT applies the LT predicate on the "updated" field.
func UpdatedLT(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLT(FieldUpdated, v))
}

// UpdatedLTE applies the LTE predicate on the "updated" field.
func UpdatedLTE(v time.Time) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.FieldLTE(FieldUpdated, v))
}

// HasGameDownloadResources applies the HasEdge predicate on the "game_download_resources" edge.
func HasGameDownloadResources() predicate.GameUploadSession {
	return predicate.GameUploadSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GameDownloadResourcesTable, GameDownloadResourcesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameDownloadResourcesWith applies the HasEdge predicate on the "game_download_resources" edge with a given conditions (other predicates).
func HasGameDownloadResourcesWith(preds ...predicate.GameDownloadResource) predicate.GameUploadSession {
	return predicate.GameUploadSession(func(s *sql.Selector) {
		step := newGameDownloadResourcesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGameDownloadResourceFile applies the HasEdge predicate on the "game_download_resource_file" edge.
func HasGameDownloadResourceFile() predicate.GameUploadSession {
	return predicate.GameUploadSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, GameDownloadResourceFileTable, GameDownloadResourceFileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameDownloadResourceFileWith applies the HasEdge predicate on the "game_download_resource_file" edge with a given conditions (other predicates).
func HasGameDownloadResourceFileWith(preds ...predicate.GameDownloadResourceFile) predicate.GameUploadSession {
	return predicate.GameUploadSession(func(s *sql.Selector) {
		step := newGameDownloadResourceFileStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGameUploadChunks applies the HasEdge predicate on the "game_upload_chunks" edge.
func HasGameUploadChunks() predicate.GameUploadSession {
	return predicate.GameUploadSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GameUploadChunksTable, GameUploadChunksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameUploadChunksWith applies the HasEdge predicate on the "game_upload_chunks" edge with a given conditions (other predicates).
func HasGameUploadChunksWith(preds ...predicate.GameUploadChunk) predicate.GameUploadSession {
	return predicate.GameUploadSession(func(s *sql.Selector) {
		step := newGameUploadChunksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserUploadQuotaRecord applies the HasEdge predicate on the "user_upload_quota_record" edge.
func HasUserUploadQuotaRecord() predicate.GameUploadSession {
	return predicate.GameUploadSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, UserUploadQuotaRecordTable, UserUploadQuotaRecordColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserUploadQuotaRecordWith applies the HasEdge predicate on the "user_upload_quota_record" edge with a given conditions (other predicates).
func HasUserUploadQuotaRecordWith(preds ...predicate.UserUploadQuotaRecord) predicate.GameUploadSession {
	return predicate.GameUploadSession(func(s *sql.Selector) {
		step := newUserUploadQuotaRecordStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.GameUploadSession {
	return predicate.GameUploadSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.GameUploadSession {
	return predicate.GameUploadSession(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GameUploadSession) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GameUploadSession) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GameUploadSession) predicate.GameUploadSession {
	return predicate.GameUploadSession(sql.NotPredicates(p))
}
